### ISSUE TITLE
Deploy bot to azure always complains "Operation failed. Only one free account is allowed for account type 'LUIS.Authoring'

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1314]
## Version
master

## Describe the bug
Go to publish page and click "create azure resource", we got following error:
![image](https://user-images.githubusercontent.com/43408889/67741519-5ca49e80-fa54-11e9-9969-fbf384f8d8d4.png)

1. I create the bot without any recognizer, first time I can deploy to azure successfully.
2. Then I edit the bot with recognizer and redeploy again, I got above error.
3. then I remove the resource in azure which created in step1, redeploy can be proceed.

So two things need to check :
- If only one luis resource could be created with Authoring key, what is the appropriate behavior if user hit this?
- we should not create the luis resource every time in deployment and check if it has been created before as only 1 could be used for free account . @benbrown @zidaneymar 
![image](https://user-images.githubusercontent.com/43408889/67741877-5c58d300-fa55-11e9-8430-6db41f474eb9.png)

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by luhan2017** [comment]
@cwhitten @yochay, @hibrenda  , do you think we need to do the step2 in R7? To me, this is not a high priority. Because, after clarifying with Luis team, the Authoring Resource limitation is 10, we are not so clear how to select one authoring key from the 10 available Luis Authoring Account, and all those 10 are from different resource group, add a lock is not an elegant approach, user don't even know what is happening, it will bring complexity to the user. I think our current solution step1+step3 should be enough to the user. 

We can sync up with Luis team on how to get the Starter_Key which is by default created in the Luis Portal, and it is more natural to use that as the default Authoring key.

**Comment by cwhitten** [comment]
Addressed in https://github.com/microsoft/BotFramework-Composer/pull/1423, https://github.com/microsoft/BotFramework-Composer/pull/1449
