### ISSUE TITLE
Connect to QnA knowledgebase not working

### ISSUE THREAD

**Issue by jelleDK** [microsoft/BotFramework-Composer#1517]
When i try to use the `Connect to QnA Knowledgebase` and fill all the details in the `Settings` i get the following error in my emulator: `Unable to find a QnA Maker service with Knowledge Base ID xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx. Please add a QnA Maker service to your bot.` I tested my knowledgebase through postman and there it works so either I'm doing something wrong in composer or there's a bug.

Version: `Application SHA 9e3347c4`

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
I just added the option in my `dialog` and filled in the `settings`

## Screenshots
![image](https://user-images.githubusercontent.com/57387033/68300719-9f8ef380-009e-11ea-9324-85ba1ccad550.png)
![image](https://user-images.githubusercontent.com/57387033/68300796-ca794780-009e-11ea-8f24-7c085991fb34.png)

**Comment by cwhitten** [comment]
hello @jelleDK and thank you for raising the issue. A known issue is causing this:

https://github.com/microsoft/BotFramework-Composer/issues/483

Restarting Composer by killing the running processes and invoking another `yarn startall` should fix this. Can you try and report back?

Addressing this issue is being tracked here: https://github.com/microsoft/BotFramework-Composer/issues/1516

**Comment by jelleDK** [comment]
> hello @jelleDK and thank you for raising the issue. A known issue is causing this:
> 
> #483
> 
> Restarting Composer by killing the running processes and invoking another `yarn startall` should fix this. Can you try and report back?
> 
> Addressing this issue is being tracked here: #1516

This did the job for me thanks!
