### ISSUE TITLE
[Inline LU] Create an intent with utterances when creating tigger

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#1641]
When creating a trigger, allow the user to provide a name for the trigger and sample utterances.

https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19-?node-id=1799%3A488

**Comment by liweitian** [comment]
@sangwoohaan @mareekuh  Talked with @hibrenda today, I want to confirm some design details for the trigger modal. For now, when we create a trigger to handle an intent, we have a drop down list including all defined intent, says which intent do you want to handle. But in the figma, we have the intent name field. Do we still need the name field? And what if users fill a duplicated intent name into the name field, probably we should prefill the intent info into the trigger phrases editor form? And at this time the user can update the intent info rather than creating a new one?

Another thing is about creating a trigger to handle an event type trigger. There is only a drop down list on the right when creating an event type trigger. It would be leaving too much empty space on the right side. Do we need to update the UX design?

**Comment by sangwoohaan** [comment]
Yes, we need to revisit the design since our naming rules have been changed. 
- The intent is dropdown for intent triggers, but this would be removed and replaced with custom naming + sample phrase editor in the context of managed LU. The only thing is that we would call this custom name field whether trigger name or intent name. I think it should be a trigger name.
- if the user put a duplicated name in the name field, the options would be 1) create the trigger and the intent with _0, _1, _2.. 2) return an error so that the user has to give it a unique name.
- The event trigger page needs a redesign, it was designed with the assumption that an event trigger could have multiple events back then. An event trigger can have only one event now.

I will revisit the design and get it ready for review.

**Comment by sangwoohaan** [comment]
Design has been updated.
https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=1600%3A9

**Comment by boydc2014** [comment]
reopen this to track the engineering effort by @liweitian

**Comment by mareekuh** [comment]
@sangwoohaan  see suggested updates to consider: https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=4066%3A35855

**Comment by mareekuh** [comment]
Adding utterances for an intent-trigger is nice indeed.
The other updates for the Trigger dialog are higher priority.
https://www.figma.com/file/HLtKaKHctLldivPnzQ7BqQOI/Composer-MI-lotsotings?node-id=2134%3A0

<img width="885" alt="Screen Shot 2020-02-03 at 6 56 34 PM" src="https://user-images.githubusercontent.com/48503434/73709796-ec429480-46b6-11ea-82ff-10462af97a38.png">

**Comment by liweitian** [comment]
Hi @mareekuh @sangwoohaan,
I have some questions on the design.
1. Currently, we have a new trigger and new dialog button. So do I need to delete them after applying the new design.    
2. For a dialog, if a dialog's recognizer type is set to None or regex rather than LUIS. Do we need to disable the **trigger phrases editor** in the old design as well as the **User input example editor** in the new design, which means we should not create a new trigger to handle a new intent at this time.

**Comment by cwhitten** [comment]
@mareekuh the R8 P0 is the ability to supply utterances when creating the intent via the wizard. Updating the IA/visual hierarchy of the modal entirely is not. We'll revisit this in R9. When you can, please follow-up with @liweitian's questions and we'll book the dev work accordingly.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/1786
