### ISSUE TITLE
[Inline LU] handle intent name changes from all up LU editor

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#1643]
If a user edits an intent name in the all up LU editor, update the dialog data (`triggers[OnIntent].trigger`) to reference the new name.

**Comment by boydc2014** [comment]
@a-b-r-o-w-n are you refer to the editor view of all up view right?

It's really hard for us to do this in a right way and automatically way.

1. It's hard to detect such change (which intent name is updated to which) in a free text editor.

For example, user selected two intents (a,b) and replaced with two intents(c, d), there is no way to know which specific intent is replaced by which, right?

2. Even though if we can the changes, it's hard to update all the references, because not just the `.trigger` is using this, it's also been used in some other fields like condition, or other expressions. 

So i prefer leave it for now, as long as our linting and validation reports that referencing mismatch, users should be able to know what happened.

**Comment by a-b-r-o-w-n** [comment]
@boydc2014 This will cause a UX gap. If we already can tell if there is a reference mis-match by linting, we should be able to at least warn the user when this change happens right?

**Comment by boydc2014** [comment]
> @boydc2014 This will cause a UX gap. If we already can tell if there is a reference mis-match by linting, we should be able to at least warn the user when this change happens right?

Yes, definitely, we should warn user more more `proactively`, right after this change happened.

**Comment by liweitian** [comment]
closed due to out-of-date
