### ISSUE TITLE
[Linting & Validation] Error notification for inline lg should navigate to form instead of all up view

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#1742]

**Comment by cwhitten** [comment]
If there is an error in an .lg template, the notifications/linking heuristic should be:

- if if the error is in an inline lg template, link to the form
- if the error is a custom crafted lg template, link to the .lg file

**Comment by zhixzhan** [comment]
> If there is an error in an .lg template, the notifications/linking heuristic should be:
> 
> * if if the error is in an inline lg template, link to the form
I guess we can treat naming-format is `bfd[type]-[id]` is an inline lg template.

> * if the error is a custom crafted lg template, link to the .lg file

By the way, because of our inline editing experience is based on template, can lgParser diagnostic provide a property indicate error belong to which template, or a template level diagnostic ? @Danieladu @boydc2014 

if not we have to repeat write code like this in several place.
```
// filter diagnostics belong to this template.
      lgDiagnostics = checkText(text).filter(lgDialg => {
        return (
          lgDialg.range.start.line >= template.startLineNumber &&
          lgDialg.range.end.line <= template.endLineNumber
        );
      });
```

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/1856
