### ISSUE TITLE
how to configure dispatch model?

### ISSUE THREAD

**Issue by narulasrinivas** [microsoft/BotFramework-Composer#1886]
I've a built a solution using BOT v4 with Visual Studio Template. This solution uses multiple LUIS and QnA models and Dispatch model is managing the user queries.

But seems composer looks more easy to manage as the BOT.

Can somebody point me to the doc or steps to configure dispatch model in composer? So that I can revamp the solution with composer.

**Comment by cwhitten** [comment]
@vishwacsena can you comment as to the current and intended dispatch support in the Adaptive runtime?

**Comment by vishwacsena** [comment]
@narulasrinivas the concept of dispatch is flipped inside out for adaptive dialogs since you get an opportunity to run the recognizer tied to the active dialog on every turn of the conversation. We continue to make several investments to the LU experience for composer where the backing LUIS applications (including QnA content when we support that) will be automatically cross-trained and the recognizers configured appropriately. 

As you consider your move from the existing code based dialog to adaptive/ composer, you should consider refactoring your dialogs such that all LU and QnA content for each dialog is locally defined within that dialog. 

If you really are looking for a 1:1 migration, then you could continue to use the dispatch CLI to create the parent dispatcher dialog and make it the main dialog for your bot with its dispatch produced LU in composer. 

Note: you need to run dispatch followed by bf luis:convert to get the dispatch app in LU. Another alternate is to go to preview.luis.ai and export your dispatch app directly as LU file.

**Comment by narulasrinivas** [comment]
@vishwacsena - Thank you for providing clear direction.

**Comment by andreatosato** [comment]
@vishwacsena Can you create docs for Multiple LUIS and QnA?
I need this feature on Bot Framework Composer, but in LUIS in not clear how to do.
I saw this [docs](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/deploy-assistant/web/7-create-dispatch-model/), but it's not clear how to use .cs file in the composer generated solution.

**Comment by andreatosato** [comment]
@vishwacsena @cwhitten
Can I use this approach also in multi-language LUIS app?
Must I define multiple LUIS app? 
Must I update manually all LUIS except default set in Composer?

**Comment by vishwacsena** [comment]
@andreatosato can you help clarify what exactly you are trying to accomplish?

**Comment by andreatosato** [comment]
@vishwacsena I setup dispatch model, works very well. I spent all yestardy to setup and test this feature.

Dispatch model work for different LUIS but on same culture.

I need to attach on Bot Framework Composer different culture.
How can I setup multilanguage in Composer?
Now works only en-us?

I have Teams bot for 2 client culture:
en-US 
it-IT

**Comment by vishwacsena** [comment]
@cwhitten can you comment on multi-lingual support in composer?
