### ISSUE TITLE
Names of the major/minor areas of the Composer screen - UX

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#1998]
I have a few questions about how to name some of the areas of the Composer screen: 

### The _Home_ page 
How to name these areas of the _Home_ page of the Composer screen?

![Home](https://user-images.githubusercontent.com/32497439/74683495-fd42d980-517d-11ea-9243-52ecc6f1e7f5.png)

1. The bar that contains Composer product name and bot project that was opend last. A **Title bar**?  
2. The triple-line icon which selected will collapse or display the Composer **Menu**. 
3. What do we call this section? **Toolbar**? 
3. What do we call this area? A **Dashboard**? 

### The _Design Flow_ page

How to name these areas of the _Design Flow_ page of the Composer screen?

![Design Flow](https://user-images.githubusercontent.com/32497439/74683850-02ecef00-517f-11ea-996f-d80933e6306d.png)

1. Should we call this area: the dialog **navigation pane** of the **Design Flow** page? 
2. Should we call this area: the **Toolbar** of the **Design Flow** page?
3. What do we call this area? 

### The _Bot Responses_ page and the _User Input_ page

How to name these areas of the _Bot Responses_ page and the _User Input_ page of the Composer screen? 

![Bot Responses](https://user-images.githubusercontent.com/32497439/74684247-46942880-5180-11ea-87f9-d3abd4aa817b.png)

1. Should we call this area: the dialog **navigation pane** of the **Bot Responses**/ **User Input** page? 
2. Should we call this area: the Language Generation (LG) editor / Language Understanding (LU) editor of the **Bot Responses**/ **User Input** page? 

### The _Settings_ page
How to name these areas of the _Settings_ page? 
![Settings](https://user-images.githubusercontent.com/32497439/74685155-80fec500-5182-11ea-8dda-4f9850f7b6df.png)

1. Can we call it the **navigation pane** of the **Settings** page?
2. **Configuration** is confusing here. 
3. **Settings** under the **Settings** option in **Menu** is duplicating in names.  

The **Publish** page should be consistent in wording which means all **deploy** should be replaced by **publish**. This is a known issue - see issue #1688 

![publish](https://user-images.githubusercontent.com/32497439/74685642-fdde6e80-5183-11ea-97c8-d6428ebc2bad.png)

Thanks! 

Yan

**Comment by mareekuh** [comment]
Lookign great!!

Home page
1. Titlebar - Ok
2. Menu - Ok
3. Toolbar - ok
    1. Note: how do we call the title above (maybe eventually below) the toolbar?
**4. Dashboard** - Hmm … does this have to have a name? For ‘Design’ view this is the authoring canvas, for Responses/User Input this is a list… For the home page it is… the home page?

Flow page
**1. Navigation pane** - How about Menu pane instead? 
2. Toolbar - ok
**3. ? -  This is the breadcrumb bar.**

Bot responses
(How about ‘Prompts and responses’?)
**1. Bot Response - Page title** 
2. Navigation pane - ok
**3. Bot responses -** How about List view? Which can be turned into ‘edit mode’.

Settings page
1. Navigation pane - ok
**2. Configuration ->** should be settings. The  menu used to say ‘Configuration’ but the nav didn’t get updated. So good point, this is a ux bug. We can get rid of this altogether as the next item already says ‘Settings’ This one should be selected by default.
3. Settings > Settings - yup, that’s annoying duplication

Publish
**Deploy -> publish :**  Yes please, I’ve already created many bugs for this to be changed throughout the app (nav, title, UX copy, doc, doc titles, doc names, buttons etc.). Hopefully after this update we’re done with them (-;

**Comment by zxyanliu** [comment]
Hey @mareekuh Thanks for your response. I am curious when will the next UX update be as you mentioned above? We writers might need to get prepared for changes in our docs. Thanks!

- Yan

**Comment by WashingtonKayaker** [comment]
My thoughts:
## The Home page
1. In Azure this section is referred to as the "Page header" (See [Azure portal overview](https://docs.microsoft.com/en-us/azure/azure-portal/azure-portal-overview#getting-around-the-portal)).
2. Not sure the name (of the 3 horizontal bars), I'd go with _Menu icon_. The descriptive terminology should be something like:
	- The Composer menu is a flyout panel, it's collapsed until you need it. Select the menu icon to expand or collapse the menu.
	- You can collapse the Composer menu to provide more working space.
3. Toolbar
4. Dashboards are "customizable interactive signboards that provide real-time information. Dashboards are associated with a team or a project and display configurable charts and widgets". See [About dashboards, charts, reports, & widgets](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/overview?view=azure-devops#key-concepts), so I'm not sure that the word _dashboard_ fits.  Perhaps just _home page_, or ???


## The Design Flow page
1. **Navigation** pane.  I think it is OK to refer to it as that regardless of which page  you are in. the _Design Flow_ can have a **Navigation** pane as well as the _Bot Responses_ or _Settings_ page etc.  You do not need to add the full description when referring to it (i.e. "the dialog navigation pane of the Design Flow page"), just **Navigation** pane.
2. Toolbar. You do not need to add the full description when referring to it (i.e. "the Toolbar of the Design Flow page"), just **Toolbar**.
3. Breadcrumb

## The Bot Responses page and the User Input page
1. **Navigation** pane.  I think it is OK to refer to it as that regardless of which page  you are in. the _Bot Responses_ page can have a **Navigation** pane as well as the _User Input_ page etc.  You do not need to add the full description when referring to it (i.e. "the dialog navigation pane of the Bot Responses/ User Input page"), just **Navigation** pane.
2. My vote is LG editor / LU editor.

## The Settings page
1. Just call it "**Navigation** pane".  Alternatively it can be called "The settings menu", although the naming for this page may need revisited, the main Composer menu is named _Settings_ and the option in the navigation pane (or settings menu) is also _Settings_, this is confusing.
2. Yes, Configuration is confusing here... Does this "navigation pane" even need a title?  what purpose does it serve?
3. "App Settings" or "Application" - for the same reason the filename when developing bots using the SDK is _Appsettings.json_.

Question regarding use of the term "Publish".  Is it more accurate to use the term "Publish" or "Deploy" / "Deployment"?  Once that is settled, it needs to be consistent.

The list of items in the "navigation pane" or "settings menu" are all settings: 

 1. **Application** settings
 2. **Deployment** settings
 3. **Onboarding** setting

 The names given should reflect what settings they are, and the word "settings" can be removed because it is implied by the fact that they are all in the _Settings_ menu.  The menu items should be:

 1. **Application** 
 2. **Deployment** 
 3. **Onboarding**

**Comment by zxyanliu** [comment]
Thanks! @mareekuh @WashingtonKayaker. Here is my conclusion and votes: 

## The _Home_ page

![Home](https://user-images.githubusercontent.com/32497439/74694751-28412380-51a6-11ea-9403-930f81ca6e6d.png)

1. Title bar - I searched: [PVA docs](https://docs.microsoft.com/en-us/power-virtual-agents/authoring-first-bot), [Window decoration](https://en.wikipedia.org/wiki/Window_decoration), [Title bar](https://www.computerhope.com/jargon/t/titlebar.htm)
2.  The Menu icon
3. Toolbar
4. Home page (if necessary)

## The _Design Flow_ page

![Design Flow](https://user-images.githubusercontent.com/32497439/74694699-ed3ef000-51a5-11ea-9cd3-dcca83842b21.png)

1. Navigation pane 
2. Toolbar
3. Breadcrumb 

## The _Bot Responses_ page and _User Input page 

![Bot Responses](https://user-images.githubusercontent.com/32497439/74694786-4d359680-51a6-11ea-9562-54735e171395.png)
1. Navigation pane 
2. LG editor / LU editor

## The _Settings_ page 

![Settings](https://user-images.githubusercontent.com/32497439/74694965-1744e200-51a7-11ea-8c43-2840871d0773.png)

1. Navigation pane 
2. Remove **Configuration**
3. Configure, Publish, and Onboard

**Comment by WashingtonKayaker** [comment]
Title Bar Vs Page Header
![Titlebar](https://user-images.githubusercontent.com/52054121/74703797-39e4f400-51c3-11ea-9d30-b2767c6a8308.png)

**Comment by zxyanliu** [comment]
@mareekuh FYI. You might already found this in the trigger menu:

I think the first trigger type in the **Message events** drop-down menu should be **Message received**. What is shown now is 

**Message events**
-> **Message events**
-> **Message deleted**
-> **Message reaction**
-> **Message updated**

What it is supposed to be: 

**Message events**
-> **Message received**
-> **Message deleted**
-> **Message reaction**
-> **Message updated**

![Untitled](https://user-images.githubusercontent.com/32497439/74773981-c802be00-5247-11ea-8f6a-476819cbf459.png)

Thanks.

**Comment by zxyanliu** [comment]
Closing this issue because it is addressed.

**Comment by zxyanliu** [comment]
The _Settings_ page contains repetitive _Settings_, and _Configuration_ seems to be unnecessary.
