### ISSUE TITLE
Refactor LuEditorWidget to function component

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#2138]
Refer to `LgEditorWidget`.

Goals: Convert to function components, create/reference hooks to hoist shared complexity (local state, change management, sync) between `LgEditorWidget` and `LuEditorWidget`.

**Comment by yeze322** [comment]
I want to provide more details about the **'shared complexity'** Chris mentioned.

### Editor Behaviors
In both LU widget and LG widget, they share same behaviors:
1. Only on init, sync props to local state
2. After init, whenever receiving new props, ignore it.
(If reset local state with new props, editor will swallow characters, it's a bug we've addressed)
3. When editing data, submit data to local state; at the same time, call `props.onChange()` who will trigger HTTP call

This is a traditional `uncontrolled component` scenario.

### (Anti)Patterns we are using
To meet those requirements, our editors have some common patterns
#### 1. sync props to local state
- Class Component uses `getDerivedStateFromProps`
- FC uses
  ```ts
  const [state, setState] = useState(props);
  useEffect(() => {
    if (!state) {
      setState(props)
    }
  }, [props])
  ```
Obviously both of them are not suggested pattern. We can find cures from the [official doc](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops)

#### 2. respect local state while ignore props
The motivation of ignoring new props was to avoid an observed bug 'swallow characters' #1748 .
The pattern is
```ts
// In Class Component
static getDerivedStateFromProps(newProps, prevState) {
  if(prevState.lg.text) {
    return null;
  }
}

// In FC
useEffect(() => {
  if (state.lg.text already set) {
    return;
  }
}, [props])
```  
It's still anti-pattern. An unconstrolled component should only care about input props on init; a controlled component should always respect props. We are not in either of them.
#### 3. data submission
To avoid triggering HTTP call too frequently, we use `debounce` to controll api call rate;
to dislay text change in realtime, editors caches the newest value in local state and ignore props.

The pattern is
```ts
const onChange = (newLg) => {
  setLocalState(newLg);
  debounce(() => updateLgViaHttp(newLg), 500);
}
``` 
It's not a good pattern because data is submitted to two layers.

**Comment by yeze322** [comment]
Beyond my suggested pattern, we need to make sure two kinds of sync:
#### 1. Make sure LG/LU editor's loacal state always be synced with Shell store
- If users can edit LG text in either FormEditor's form or VisualEditor's node, if they edited LG text in Visual, the local state of LGEditorWidget in Form should also be synced.
- Imaging a user is editing LG templates `hello` under 'LG all up view' page, he/she made some changes on `hello` but didn't save them. Then the user switched to 'Dialog Flow' page, made some other changes on the `weather` template via FormEditor - LGEditor (changes saved automatically). If the user switch back to 'LG all up view', changes on `weather` should be synced meanwhile the unsaved changes on `hello` should be remained.
#### 2. Make sure LG/LU (even Dialog) data in Shell store always be synced with server store (multi-user scenario)
- User A & B are editing a same file `Main.lg`, they both fetched the intial data.
- Firstly, user A edited the content in `lg.weather` template and submitted, server accepted this change;
- Then user B edited another template `lg.greeting` and submitted, server should accept B's changes without conflicts, server should also return a new file to B with both A & B's changes.
- If either A or B's local LG/LU editor has any unsaved changes, it should be merged as the case described in scenario 1 - lg all up view.

**Comment by yeze322** [comment]
@alanlong9278 there is a suggested hook
```ts
const useEditorApi = (
  editorData,
  submitEditorData,
  mergeStrategy?: (nextData, prevData) => any, // set to undefined if it's fully uncontrolled
  submissionDebounce = 500
) => {
  // local state
  const [ localData, setLocalData ] = useState(editorData);
  
  // apply merge strategy
  useEffect(() => {
    if (mergeStrategy &&) {
      const nextData = mergeStrategy(editorData, localData);
      // We have to make a double rendering here. best practice is a `key` mechanism,
      setLocalData(nextData);
    }
  }, [editorData]);
  
  // submit
  useEffect(() => {
     debounce(() => submitEditorData(localData));
  }, [localData]);
  
  const resetLocalData = () => setLocalData(editorData); // reset to props
  return { data: localData, setData: setLocalData, resetData: resetLocalData  };
}

// usage
const { data: lgData, setData: setLgData, resetData: resetLgData} = useEditor(props.lg, props.updateLg);
```

**Comment by yeze322** [comment]
This issue is outdated, the code has been updated several times. Can be closed.

**Comment by yeze322** [comment]
Hide my oudated comments about implementation details.
