### ISSUE TITLE
Cross-file copy of LU / LG resources

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2207]
## Describe the bug

If a user copies a SendActivity action to another dialog file, the LG content inside that action won't be copied along with the action.

We should also cover the copy behavior of LU resources.

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Additional context
Follows #2199

**Comment by hibrenda** [comment]
As discussed with Ze and Dong, we plan to support shallow copy for LG & LU . we may need further discussion on how to handle the custom template editing. eg. only common.lg could be toggled into edit mode. so that all the referenced templates could only be defined in common.lg. 
for other lg file, user can only get the list view in all up and could do inline editing in list view. This will solve the shallow copy for nested template reference. @cwhitten @sangwoohaan

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2236

**Comment by yeze322** [comment]
> As discussed with Ze and Dong, we plan to support shallow copy for LG & LU . we may need further discussion on how to handle the custom template editing. eg. only common.lg could be toggled into edit mode. so that all the referenced templates could only be defined in common.lg.
> for other lg file, user can only get the list view in all up and could do inline editing in list view. This will solve the shallow copy for nested template reference. @cwhitten @sangwoohaan

Yes, I and came up with a same conclusion that a dialog's correlated lg file shouldn't contain any self-referenced templates. As you said, all the referenced templates should only be defined in common.lg.

The new copy-paste behavior of LG templates in Visual Editor is right based on this policy. I think @zhixzhan can follow up the LGEditor / all-up-view part.
