### ISSUE TITLE
lu validation issue

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2242]
## Describe the bug
Trying to update the [how to use validation](https://docs.microsoft.com/en-us/composer/how-to-use-validation) article. The behavior of lu validation differs as listed here: 

- Lu validation works perfectly in intent trigger creation.

![image](https://user-images.githubusercontent.com/32497439/76453897-eb291500-6390-11ea-9b8a-f46062a39622.png)

- Lu validation not working properly in **User Input**. 
issues:
   - 1. the red line should be under the error in line 5, but it shows in line 6. 
   - 2. only fixes in **User Input** works, fixes in inline editor does not work. 

![lu-issue-in-validation-userinput](https://user-images.githubusercontent.com/32497439/76454133-51ae3300-6391-11ea-87f1-ad32d039b08e.gif)

- Lu validation does not work in lu inline editor. 
issue: 
  - error indicator with details is not show at the buttom of the inline editor
  - error is not synced to **User Input**
  - error is not saved
![lu-issue-in-validation](https://user-images.githubusercontent.com/32497439/76453975-0a27a700-6391-11ea-870b-53be9df4ac98.gif)

**Comment by zhixzhan** [comment]
Hi Yan, see comments bellow
> ## Describe the bug
> Trying to update the [how to use validation](https://docs.microsoft.com/en-us/composer/how-to-use-validation) article. The behavior of lu validation differs as listed here:
> 
> * Lu validation works perfectly in intent trigger creation.
> 
> ![image](https://user-images.githubusercontent.com/32497439/76453897-eb291500-6390-11ea-9b8a-f46062a39622.png)
> 
> * Lu validation not working properly in **User Input**.
>   issues:
>   
>   * 1. the red line should be under the error in line 5, but it shows in line 6.

It's a bug, will fix it soon.

>   * 1. only fixes in **User Input** works, fixes in inline editor does not work.

It's kind of known issue, it's because our current LU parser haven't implement parse/update/save lu file with error, if file haven't been saved, the notification page would also not update. At this moment if user go to another page then go back, would see the invalid content are dropped. because currently LU file doesn't have the ability to save with error.

it happens only in inline editor, in all up view edit file we save whole file, no need to call LU Parser to assembly a new lu file, so has or has not error would always been saved.

It's a temporary solution, we can fix it in future.

> 
> ![lu-issue-in-validation-userinput](https://user-images.githubusercontent.com/32497439/76454133-51ae3300-6391-11ea-87f1-ad32d039b08e.gif)
> 
> * Lu validation does not work in lu inline editor.
>   issue:
>   
>   * error indicator with details is not show at the buttom of the inline editor

will fix soon

>   * error is not synced to **User Input**
>   * error is not saved

explained above, file with error have not been saved.

>     ![lu-issue-in-validation](https://user-images.githubusercontent.com/32497439/76453975-0a27a700-6391-11ea-870b-53be9df4ac98.gif)

**Comment by zhixzhan** [comment]
Addressed via #2272
