### ISSUE TITLE
[Electron] remove unnecessary source files in packaged application

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#2293]

**Comment by srinaath** [comment]
@cwhitten 
We are currently using electron-builder for packaging the app. It's ability to include only build folders from node_modules of all dependancies is very limited. As a result, we have packaged the current app to the best way we can with electron-builder. We need to investigate in the future using electron-forge instead of electron-builder for packaging. I feel the work required for BUILD 2020 is done but leaving this ticket open for a future upgrade from electron-builder to electron-forge.

**Comment by cwhitten** [comment]
Team to investigate `electron-forge` as a way to package electron apps instead of `electron-builder`. Removing from R9, will look to pick it up in a future release.

**Comment by srinaath** [comment]
This is a future work item not planned for R10
