### ISSUE TITLE
Open bot defaults to / for new installs

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#2453]
## Describe the bug

If I have a new install (or deleted my data.json), opening a bot defaults to `/` instead of the default path.

refs #2412 #2445

**Comment by liweitian** [comment]
@a-b-r-o-w-n  Previously, we want to save the last access path. That path is stored in data.json. When you have a new install, it does not influence anything. You will start from the 'path' in data.json. If you delete the data.json, a new data.json will be copied from data.template.json. You will start from the default path since the path in data.template.json is "", not valid.

**Comment by liweitian** [comment]
![aaaaa](https://user-images.githubusercontent.com/24380525/78124303-1360dc80-7442-11ea-97a9-140599b61a52.gif)
