### ISSUE TITLE
Reference in LU editing

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#2523]
For reference, I want to be able to do this in LU content

`- [trogger1](dialogName#triggerName)`

**Comment by xieofxie** [comment]
This is extremely useful. Different inputs in different dialogs could be able to reference to same set of 'Expected responses'.

**Comment by xieofxie** [comment]
A real scenario:
In show todo, mark todo, delete todo dialogs, they all need display todos and local show next, show previous intents are needed.

The related input can't be shared because they also expect something different like 'mark the first item' or 'delete the second item'.

Then if show next, show previous intents are shared, it will make it easier and cleaner

**Comment by hibrenda** [comment]
dup with https://github.com/microsoft/BotFramework-Composer/issues/2241
