### ISSUE TITLE
SetProperties value is often '?' in node and the wrong type in form

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#2877]
See attached. The Value property doesn't appear to serialize correctly. Schema mismatch?
![Screen Shot 2020-05-03 at 8 25 58 PM](https://user-images.githubusercontent.com/1156704/80980671-c627b000-8ddd-11ea-94d6-d57bc269a9bf.png)

Todo:
- [ ] do not remove empty objects/arrays that are user-inputted

**Comment by a-b-r-o-w-n** [comment]
Note:

Today we currently remove any empty object and empty arrays in `sanitizeDialogData`. We could update that function to also look at the schema to determine whether or not we want to do that.

Another option is to have default serializers in the form that do the sanitization work which can be overridden on a per-property basis.

**Comment by yeze322** [comment]
The schema is outdated:
![image](https://user-images.githubusercontent.com/8528761/81263920-23885f00-9073-11ea-90c8-89ac1ece44d9.png)

Two more related problems:
1. The logic is wrong if the value is set to `false` or `0`. in SetProperty, it should be `??` instead of `||`
2. The content displayed inside SetProperty and SetProperties are not consistent.

I will create a PR for fixing that, focusing on optimize the node content of SetProperty(s)

**Comment by yeze322** [comment]
Some other problems I found in Form side
- when the value type is set to 'object' or 'array', `action.value` equals `undefined` rather than the displayed value in JSON editor;
- when the value type is set to 'array', JSON editor displays `{}` which should be `[]`

**Comment by yeze322** [comment]
addressed Visual Editor part in #2936

**Comment by a-b-r-o-w-n** [comment]
Thanks @yeze322, merged. I will try to address the other issue in the coming week.
