### ISSUE TITLE
Changes on bot files won't take effect by refreshing the design page

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2949]
## Describe the bug
![bug-get-cache](https://user-images.githubusercontent.com/8528761/81397752-86a0f100-915a-11ea-8c3c-85c0c66e8c3f.gif)

The behavior of 'open project' and 'get project' are different. 'open project' will always fetch the newest dialog data while 'get project' won't.

What I did here is editing a `main.dialog` file via a plain text editor, then tried 2 approaches to refetch the bot content (1. refresh the page 2. reopen the bot from Home page)

Found that
- 'get project' returns old data, hits cached data
    ![image](https://user-images.githubusercontent.com/8528761/81389754-e4c6d780-914c-11ea-930f-a0c12f0b260f.png)
- 'open' returns new data
    ![image](https://user-images.githubusercontent.com/8528761/81389818-fdcf8880-914c-11ea-9208-7ebe0901af61.png)

Repro steps:
1. Update the bot content file under YOUT_BOT_PRJECT folder, for example, removing an action
2. go back to design page (content not updated)
3. refresh design page (content still not updated)
4. go to home page, open the bot by click the blue text under `Recent Bots` (schema updated)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by yeze322** [comment]
@VanyLaw could you help triaging this issue

**Comment by yeze322** [comment]
This issue affects the behavior of custom schema story. Users have to reopen a bot after they ejected a custom runtime with custom schema files.

**Comment by VanyLaw** [comment]
@yeze322 Currently, after refreshing server will return cache project files instead of geting the bot from disk. Server will get bot from disk only when open/reopen a bot. **And I am not sure is it a bug? because it's a normal way to save time. And I am not sure if it can refresh in electron** 
For the dialog update, it's better to change through dialog editor (click show code).
And I think the better way to handle this situation is add a editor for user to edit or add a button in frontend to support user upload new file. In a word, make composer aware the change.

**However, if it's need to re-get bot files from disk every time we refresh, I can use the open_project api in here.**
![image](https://user-images.githubusercontent.com/21174180/81467973-f4a6f000-920e-11ea-8755-1bc7482ac30f.png)

@benbrown what do you think?

**Comment by yeze322** [comment]
@VanyLaw I'm not quite with you about the motivation to save time. If we really want to avoid reading fisk files frequently, there is a HTTP 304 'Not Modified' to handle that.

Anyway, functionally we need to support one scenario here:
1. User switches to 'Settings' page
2. User enables an ejected(custom) runtime in which contains a custom sdk.schema
3. Then switches back to design page, the 'sdk.schema' needs to be up-to-date (with or without refresh are both fine, shouldn't 'reopen' the bot manually)

**Comment by VanyLaw** [comment]
I update the botproject in server cache after eject, that can return botproject include schema files when user refresh.

**Comment by yeze322** [comment]
Thanks @VanyLaw ! It can support the ejected scenario well
