### ISSUE TITLE
New File dialog is overly non-standard

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#2972]
## Describe the bug

I installed from github release page (0.0.1) 

## Version
0.0.1 (2 days ago)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. New Bot

## Expected behavior

1. It should have windows path, so it it should have \ instead of /
2. It should start in the logged in Users folder, not the root.,
3. It should not have slash before the drive letter.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/81478441-57c66180-91d2-11ea-8233-31dff43c5ece.png)

**Comment by cwhitten** [comment]
@liweitian can you take a look at this please?

In addition to @tomlm's Expected behavior, please also do the following:

- Hide special/hidden directories in the navigation control

Directories with special prefixes like '$' or '.' should be filtered out.

![Screen Shot 2020-05-10 at 10 18 01 AM](https://user-images.githubusercontent.com/1156704/81505905-9e39c000-92a7-11ea-8386-7292cc3a2ccb.png)

**Comment by boydc2014** [comment]
@cwhitten  we were kind of trying to unify the path in unix style to make it more convininent. So we are now getting to have different UI in win vs non-win, right?  that could solve 1 and 3 in @tomlm's request. 

And @tomlm, for 2, i see the default folder is C:\user\myusername\documents\Composer
![image](https://user-images.githubusercontent.com/3829387/81538088-cce79180-93a0-11ea-89fb-6039268bf73c.png)
Is this not the case in your side? what did you see without jumping into other folders, because we will use the location you left last time as the new default.

**Comment by cwhitten** [comment]
I like the consistency of the unix path for internal operations. We can maintain that if it is helpful. When we render the view can we consider a transform to the os path separator? This wouldn't require a change to the internal model of path serialization.

The request is to default to `/Users/${username}` instead `/Users/{username}/Documents`

**Comment by boydc2014** [comment]
> I like the consistency of the unix path for internal operations. We can maintain that if it is helpful. When we render the view can we consider a transform to the os path separator? This wouldn't require a change to the internal model of path serialization.
> 
> The request is to default to `/Users/${username}` instead of `/Users/{username}/Documents`

Sorry for not following up this quickly,  i saw this is closed, 

Our previous our default path is /Users/{username}/Documents/Composer, and now we updated to /User/{username}, which i don't think it's the stardard, @cwhitten @tomlm . 

From what i know, most application write to /Users/{username}/Documents/{appId} like VS, and Github desktop, IIS, and so on, for example
![image](https://user-images.githubusercontent.com/3829387/81907559-87be9c00-95fa-11ea-8255-e570c120da47.png)

I thought this is the convention. 

And there are a few application do write directly into /User/{username}, but they at least use a {appID} instead of create many folder's there, which is annoying and definitely not the standard 
![image](https://user-images.githubusercontent.com/3829387/81907712-c3f1fc80-95fa-11ea-8d0e-7e50c2a2faea.png)


So i think we need to at least have an app identifier like composer, /User/{username}/{appID}, instead of directly writing to /User/{username}. I prefere /User/{username}/Documents/{appID} if possible.
