### ISSUE TITLE
Add semantics are mixed up with create semantics

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#2976]
## Describe the bug

When I pick Add Dialog, I think I'm going to add a dialog to this dialog.  I am completely suprised then it drops me into a creation flow. 

How do I add a dialog I have already created?

When I add a trigger, I get a dialog which is Create a trigger.  Again, semantic mismatch. 

## Version
0.0.1 (2 days ago)

## Browser
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge (chrome)

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. open EmptyBot-01
2. Click Add button
![image](https://user-images.githubusercontent.com/17789481/81478774-49794500-91d4-11ea-869e-8cf038c9dc4c.png)

This confusion is emphasized by the title of the dialog that pops up when I say "add trigger", it correctly labeled "Create trigger" :
![image](https://user-images.githubusercontent.com/17789481/81478989-8abe2480-91d5-11ea-9ccb-a885bae08bad.png)

## Expected behavior
We should use clear semantics, **Add** is to reuse something and **Create** is to create something.  Given the entire declarative file format is about defining things for reuse, we need to have the IA reflect that or we will have confusion.

**Comment by cwhitten** [comment]
@mareekuh as you provided the copy here quite awhile ago -- are you interested in updating this before BUILD?

**Comment by mareekuh** [comment]
When I click 'add dialog' when within a dialog I get the following (see below).
I agree with you 1000% that I want to either create a new one or select one I have already created.
The former is possible - as far as I know the latter (select from existing) is not yet.
The UI to enable both has been designed (it is very similar to create new bot: create new /select from sample) but is not enabled yet.

![Screen Shot 2020-05-09 at 2 46 24 PM](https://user-images.githubusercontent.com/48503434/81485686-f323fa80-9203-11ea-88e4-c920c4c5dd4c.png)

Regarding the 'add > add new trigger' :this is by design.
Instead of having several separate 'add' option, each for a  specific type, the UI has a consistent 'Add' option in every single screen of Composer (not implemented everywhere, but this is the objective) and the dropdown allows to select what specific thing to add, relevant to the context.
If a user is IN A DIALOG in the authoring canvas, relevant options are: 
- adding another dialog as a peer to the current one
- adding a TRIGGER within the currently selected dialog 
So, seeing the 'add trigger within (NOT: ON) Emptybot-0 is expected and correct.

@cwhitten - Unless I am misunderstanding @tomlm 's issue/concern, the design is as-spec'ed. We can discuss but I don't think an urgent update is needed.

**Comment by cwhitten** [comment]
I agree the design is as-spec'd, however @tomlm brings up good points that we mix `Add` and `Create` interchangeably and this isn't clear to users.

**Comment by mareekuh** [comment]
agreed.
Please have a look at this - it addresses [#2977](https://github.com/microsoft/BotFramework-Composer/issues/2977) also:

https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=313%3A2806

Please note - the copy in the dropdown in the build does not match the design spec.

<img width="647" alt="Screen Shot 2020-05-10 at 9 02 49 PM" src="https://user-images.githubusercontent.com/48503434/81523098-a7577b00-9301-11ea-8ae5-6e2544afba91.png">

**Comment by cwhitten** [comment]
I have questions about this:

1. Can you explain the "Bot name" label?
2. When adding an existing dialog, where is it adding it from? Is this supposed to hook into the not yet built Dialog Assets mocks?
3. Can you explain the purpose of the location field?

**Comment by mareekuh** [comment]
1. "Bot name" label - copy paste error. Should be 'Dialog name'
2. Existing dialog - depends on what the user chooses:

-  Sample dialog : sample dialog folder /assets library (soon to come)
- Existing dialog : wherever the user saved it in their file system (possibly part of another bot/dialog)

3.  location field - just a way to allow user to control where to look and find the dialog they want to add.

**Comment by tomlm** [comment]
BTW: The reason I am pushing to be clear about Add/Create, or Add/New semantics is that Add is about reusing an existing defined asset, and New is about defining that asset. Thanks!

**Comment by zxyanliu** [comment]
Thanks for your valuable feedback. Please see https://github.com/microsoft/BotFramework-Composer/issues/3175.
