### ISSUE TITLE
Our dialog text is sometimes questions and sometimes labels and not consistent.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#2978]
## Describe the bug
When I create a trigger the default is intent but the label for the field is **"What is the name for the trigger?"**

This is very non-standard.  GUI Dialogs don't normally use questions on the fields, fields have labels, and tooltips.
Look at excel, labels, not sentences with tooltips to describe what it is.
![image](https://user-images.githubusercontent.com/17789481/81479578-ec33c280-91d8-11ea-9bba-82ac472acd28.png)
Is there a new industry standard I don't know about which says everything should be turned into a full question?

Worse, we are not consistent in the application of questions to input fields.

For example: Create Dialog has simple label **"name".**  Yay.
In Create Trigger we have a field which should be **"Name"** or **"Intent",** but instead it is "What is the name of this trigger?" A full blown question Boo. 

Then the trigger phrases is not a question "What are your trigger phrases?" but a label "Trigger Phrases".  Yay?

And the property sheet for editing nodes uses labels and not questions:
![image](https://user-images.githubusercontent.com/17789481/81480590-7d0d9c80-91df-11ea-91cd-62833b81aa6b.png)

Why are we using sentences everywhere?  Why are we deviating from such a well established norm?

# Expected 
We need to our dialog text to be consistent and I find the full question form non-standard and irritating.

For the Add a new trigger dialog we need to clean up our labels to be consistent.  
1. **Trigger Type** would be a reasonable label for selecting type of trigger.
2. **Intent** because it's not a trigger name, triggers don't have names, it's the name of the intent.
3. **Event Type** instead of "What type of event"

**Comment by mareekuh** [comment]
@tomlm  I agree with you from a 'standards/consistency standpoint' and I am sorry it irritates you. Whenever possible, me and my team will aim for consistency. But this does not mean we'll apply 'constent for consistency sake' treatment.At all times, clarity for the user and doing what is appropriate is more important than consistency.
In this case, there was extensive discussion and thought put into what to do here: 

1. We agreed with PVA to use the word 'trigger' vs 'event'. To respect this agreement, we have updated our copy, across the documentation and UX copy, this dialog included.
2. Using both at the same time in the same dialog caused confusion and led to the current design.  (Please note that besides event and trigger, the SDK also uses 'activity' which increases confusion. Given that 'Activity' is used all over the SDK, we left that as is for minimal intrusion to the SDK).
3. The information we need from the user here are ... confusion to start with, as both of them - in street terms - are 'types': a type of trigger and sub type. And based on this selection we're suggesting a name.

So, we could do the following, to address your request for consistency:
(see design attached below and [here]([url](https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=313%3A2806)))
Input: 
Trigger type: 
Trigger name: 

But, while that is more consistent, I'd argue the this has a negative impact on the user experience an clarity of what we're asking the user to do in this dialog.
As there are more updates to come in coming months to the Trigger, and New dialog flow to improve ease-of-use and alignment with PVA, I would recommend to LEAVE AS IS, BY DESIGN for this request. It's not broken and it requires front-end and Documentation updates within a matter of days. The benefit (consistency) is not worth the effort - imo.

![Screen Shot 2020-05-09 at 2 06 36 PM](https://user-images.githubusercontent.com/48503434/81485001-f668b780-91fe-11ea-8159-e9e4b5c00a50.png)


@cwhitten  **NOTE** it looks###  like the current trigger flow is not implemented fully as spec'ed.
The dialog only shows the sub-dropdowns as soon as something is selected, and the UX copy and order of dropdown is not as spec'ed. This is MUCH higher priority imo than changing a sentence into a label for consistency sake.

EXPECTED and spec'ed:

1. Add-trigger dialog inc. copy is implemented as spec'ed in[ here][([url](url))](https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=313%3A2806
)
2. All dropdowns show whenever user enters the dialog 

3. All options to select from, show up. (eg : in some cases, such as in 'greeting' dialog, intent recognized is not available. Only Dialog and unrecognized intents are available.

4. order of the dropdowns is : 
- what initiates the trigger
- type of trigger
- name of trigger

4.  Name of trigger dropdown is prepopulated based on selections in dropdown 1 and 2

5. For intent selection, TRIGGER PHRASES are in a SUBSEQUENT dialog

6. The buttons should adhere to the detailed design spec. Submit is not appropriate or expected in this context. OK/Cancel or Next/back/cancel are button labels currently and consistently used in UI. Please stick to these standards unless deviation is absolutely necessary).

**Comment by tomlm** [comment]
Marieke, I don' understand this statement:

> We agreed with PVA to use the word 'trigger' vs 'event'. To respect this agreement, we have updated our copy, across the documentation and UX copy, this dialog included.

We agreed that to use the term Trigger for the rule which has a flow in it.  But:

**Triggers and events are not the same thing.** 

A **trigger** is a rule which reacts in response to something happening and the reaction is defined in terms of actions in a flow.

The dialog system fires **events** at multiple places as a turn is processed and triggers are evaluated to see if there is something defined to do in response to the event firing. 

Events are open ended, any components can define and emit new events and authors can author the emiting of a custom event and the trigger which handles that event.  They absolutely core to the dialog system, both at the code, execution model and mental model that developers need to think in.

ALL triggers could be modeled as single trigger type of **OnDialogEvent**() but that would mean we would have to educate people on the appropriate name and constraints for the various types of events to trigger off of

To make things more discoverable and easier to author we created a number of predefined Trigger Types.

OnBeginDialog, OnIntent, OnDialogEvent, etc. are all intents which make it easy to write a trigger which responds to built in system events in the system.

Activities are also represented as dialog events, but they are "ActivityReceived" events.  To make it easy to define triggers with external activities we have the OnMessageActivity, OnMessageReactionActivity, OnTypingActivity, including one the activities which you can receive is OnEventActivity.  (which is for modeling an external event such as a garage door opening from a smart home IOT device).

Any component library can define new event types, (as can authors)  and can emit new event types which needs to have triggers authored to reacts to them (either by using a generic OnDialogEvent() or a custom trigger class definition (again to make it easier to author).  _This means that our design needs to work correctly over time, and in response to components being added it doesn't know about._

All of these things are part of the possible **Trigger Types.**  which **New Trigger** needs to present to the user.

If your bullet 4 is saying that you want to classify trigger types to make it easier to pick the right one, then great.  But your comp and text says that the first thing to pick is "Input" or what initiates the trigger which I don't think is the right way to think about it.

If I interpret your intent I think you saying :
1. **XXXXXX** shows groupings of trigger types. (Intents|System events|Activities|Custom Events)
2. **Types** or **Trigger Types** are appropriate names for the shown list of trigger types. I don't know that we need to call it "trigger types" as it's already the "Add Trigger" dialog.
3. **Name**  to give the trigger a friendly name for navigation/recall, nothing controversial here, other then we should say "This name is for your own organization and means nothing to the system.

My problem is XXXXXX doesn't have a natural name in the system 
* Trigger Groups? 
* Trigger Kinds? 
* Type and SubType? It's artificial. 

It's important to note that someone adding a new Trigger type has no mechanism to communicate to the UI where in the groupings it should be. If this is an important thing we need to be able to do that.

We did this sort of clustering to make it easier to navigate with the Add Action hierarchy menu picker (add action), but we didn't have to name the root group names and so avoided the problem.

**Comment by mareekuh** [comment]
Hey Tom
Yes, I understand the difference between trigger, event and activity. The below is indeed the issue I’m dealing with:


“ALL triggers could be modeled as single trigger type of OnDialogEvent() but that would mean we would have to educate people on the appropriate name and constraints for the various types of events to trigger off of”

In the previous implementation, the user had to select ‘type’ first (intent, dialog, activity, custom), and then a sub-type on a following page. This made it difficult for people to ‘explore’ the types of events available and select the one that best matched their objective.Especially for devs that are still getting familiar with Composer/sdk this was not ideal. For many, at least initially, the difference between dialog event and activity is too nuanced and having both dialog events and activities in the same list makes for a long and overwhelming list of options.  
The other feedback received was that using the three different but seemingly similar concepts ‘event’, ‘trigger’ and ‘activity’ in the  ui copy and labels of this modal caused confusion, resulting in GitHub issues. 
We had extensive discussions with our techwriters @zxyanliu, Jonathan and Vishwac to try and address the issues and confusion with this modal. Allowing the user to select a highlevel trigger type first, and then narrow it down using a cascading menu seemed a reasonable approach. This would allow the user to more easily browse the various options and we would need to go deep on the nuances difference between the three concepts. When turning this into a mock-up it became clear that 3 levels of cascading menus from a dropdown were needed to communicate options, preventing overly long lists of options. As this is not easy-to-use, nor a scaleable solution, we move to a two-dropdown solution to let people select type and subtype separately, on the same modal. We can’t use  the labels ‘type’ and ‘subtype’, which is why we ended up where we are now.

**Comment by Stevenic** [comment]
Just filed a related issue: https://github.com/microsoft/BotFramework-Composer/issues/3173

The other issue I noticed is that we're sometime using titles to re-name properties. This is just going to lead to confusion when developers drop down to code or try to read the reference documentation.

**Comment by Stevenic** [comment]
My 2 cents...

I would agree with @tomlm that asking "What is the name of the trigger?" versus "What is the name of the intent?" is a bit confusing because we are in fact defining a trigger for an Intent. It's called an "Intent Trigger".  As he stated we don't have named triggers.

Furthermore, I think the current wording has potential IA issues as we really need the ability to define multiple triggers for the same Intent which is pretty much impossible using the current UX. https://github.com/microsoft/BotFramework-Composer/issues/3086

I care a little less about the labels vs questions part of this discussion but I do think its important that any questions/labels in the UX have a clear linkage to the underlying concepts they represent in the SDK.

**Comment by Stevenic** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/3174

**Comment by zxyanliu** [comment]
Thanks for your valuable feedback. Please see https://github.com/microsoft/BotFramework-Composer/issues/3175.
