### ISSUE TITLE
master branch can't build in windows now

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#3164]
## Describe the bug
![image](https://user-images.githubusercontent.com/39758135/82650789-c8976000-9c4d-11ea-9b97-f98209802881.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cxbuilders** [comment]
had same issue, reverted back to a commit from a day ago to keep working

**Comment by lei9444** [comment]
in Windows we use CRLF
![image](https://user-images.githubusercontent.com/39758135/82651016-29269d00-9c4e-11ea-909d-049be84dc5dd.png)

if we use lint:fix will commit a lot of files.

I not sure use 
`"endOfLine": "auto"`
in .prettierrc is a good Solution #3162

**Comment by zxyanliu** [comment]
Same here. I was unable to build Composer using the master branch in Windows.

**Comment by a-b-r-o-w-n** [comment]
@lei9444 I think we should enforce the files in git to be LF (can be done using a git attribute). This is the most cross platform friendly solution, but it may require windows users to reclone (according to https://prettier.io/docs/en/options.html#end-of-line).

Can you experiment by adding the following to a `.gitattributes` file in the repo?

```
* text=auto eol=lf
``` 

Since I'm on mac, this is already happening, but I am curious what Windows users will need to do if this setting is present. 

What about using the "auto" option? Did that not work? I see your PR #3162 is closed but without comment.

**Comment by lei9444** [comment]
> @lei9444 I think we should enforce the files in git to be LF (can be done using a git attribute). This is the most cross platform friendly solution, but it may require windows users to reclone (according to https://prettier.io/docs/en/options.html#end-of-line).
> 
> Can you experiment by adding the following to a `.gitattributes` file in the repo?
> 
> ```
> * text=auto eol=lf
> ```
> 
> Since I'm on mac, this is already happening, but I am curious what Windows users will need to do if this setting is present.
> 
> What about using the "auto" option? Did that not work? I see your PR #3162 is closed but without comment.

Sorry, I have tested the "auto" option. It works, but this will make windows and mac users commit different line-endinds. I'm not sure it is good way to fix this issue, so I closed it.

**Comment by timoconnellaus** [comment]
In lieu of this being addressed I was able to build the project on windows by running "npm run lint -- --fix" this command before running "yarn build"

**Comment by hibrenda** [comment]
addressed in #3162
