### ISSUE TITLE
Issue with passing activity to skill bot.

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#3205]
I am passing activity from consumer bot to skill bot. whatever i am passing from consumer bot i am getting everything in text turn.activity,text only. Ex. If i pass attachments from consumer bot to skill bot instead of getting it in turn.activity.attachments, i am getting it in turn.activity.text.

here are some screenshots regarding this issue.

![image](https://user-images.githubusercontent.com/51915291/83121216-a4290100-a0ef-11ea-994e-2efc51675850.png)

In Below Image i am passing turn.activity.attachments.
![image](https://user-images.githubusercontent.com/51915291/83121393-dfc3cb00-a0ef-11ea-8d5a-b360caf30a57.png)

**Comment by tdurnford** [comment]
@KoradaRajesh If you set the 'Activity Processed' property at the bottom of the Property Editor to `false`, it should begin the skill "using the activity in the current turn context instead of the activity in the Activity property." Setting the 'Activity Processed' to `false` should forward the entire activty including the attachments to the skill.

![image](https://user-images.githubusercontent.com/17039790/83173440-41773b80-a0d6-11ea-8097-74606dd3db8a.png)

**Comment by KoradaRajesh** [comment]
thanks @tdurnford. its working.
