### ISSUE TITLE
Bad error message when trying to start a bot

### ISSUE THREAD

**Issue by ajjosh-msft** [microsoft/BotFramework-Composer#3228]
## Describe the bug
I have cloned the https://github.com/microsoft/meeting_assistant repo. I opened up the Timer project in composer. I enter in my LUIS Key, AppID, App Password. It states.
![bug_composer](https://user-images.githubusercontent.com/64500801/83293651-d5add500-a1a0-11ea-83d2-5499623e0239.JPG)

## Version
v1.0.0

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ x] Edge

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to https://github.com/microsoft/meeting_assistant clone the repo.
2. Open in composer the MSMeeting-Timer bot which is under skils
3. Change setting to add in AppId, AppPassword, Luis Key
4. Start Bot.

**Comment by cwhitten** [comment]
@zhixzhan or @lei9444 can either of you look at this?

**Comment by hibrenda** [comment]
This should be fixed in https://github.com/microsoft/BotFramework-Composer/pull/3197. 
To mitigate this issue, you can try latest composer master.

By the way, this will also hit following error. 
![image](https://user-images.githubusercontent.com/43408889/83383949-c46efd80-a418-11ea-8153-d7a288f4ec32.png)

mitigation would be : rename the bot without "-". 
It is wired error as no error pop up if I create bot with "-" .

**Comment by VanyLaw** [comment]
@hibrenda **Only absolute URLs are supported** issue is cause by lubuild. @lei9444  will help to solve this issue.

**Comment by hibrenda** [comment]
Now figured out as above renaming does not change lu file name in the dialog file. so this step work around the luis publish. That's why no errors pop up.

**Comment by hibrenda** [comment]
endpoint issue is tracked by https://github.com/microsoft/BotFramework-Composer/issues/2986 .
