### ISSUE TITLE
Custom Deployment -> Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3275]
I have setup a Custom Deployment using the ARM template in Azure Devops and all is running fine, except for when a Luis call is made in the Emulator. It then responds with :
Response status code does not indicate success: 403 (Forbidden).

What is causing this? I have nicely both the normal and authoring Luis endpoints and both keys are in the appSettings.json and are correct. Is there any other setup that I am missing for Luis during development that I should include in the deployment?

**Comment by luhan2017** [comment]
Could you check your settings in appsettings.deployment.json? We are using this configuration for a deployed bot to avoid the mixing up between local and deployed environment.

**Comment by cxbuilders** [comment]
@luhan2017 I don't have an appsettings.deployment.json. I do see one in another skill that has a custom runtime, but this one does not. 

It would be really helpful if one could explain how Luis is deployed, published and used in the local vs azure setup.

**Comment by luhan2017** [comment]
For local, the step is 
1. Fill in the luis settings in the publish luis page. (those settings will be saved in botfolder/settings/appsettings.json) 
2. Call lubuild, output is the generated folder. 
3. Start botruntime.

For azure, the step is
1. Run the provision steps, which will provisioned two luis services for you(luis authoring and luis prediction), those settings are outputted as a publish profile.
2. Add this publish profile in the publish page, composer will take the keys from the profile and put it in appsettings.deployment.json
3. Deploy the bot, the deployment script, will call lubuild and use the authoring key to generate luis sevices, and then call another API to bind the service with the prediction key. (So in a deployment scenario, you will use the endpointKey which is come from the luis prediction service).

So for your question, if you want to update the luis settings for deployment, you could just update it in your publish profile. Because the appsettings.deployment.json will be deleted after the deployment is done.

**Comment by cxbuilders** [comment]
@luhan2017 Thanks for the information. I have the same issue on a normally deployed bot, so I guess that it is not related to the pipeline itself vs the normal deployment. Thanks for the info that is really helpful though.
