### ISSUE TITLE
CI/CD Approach

### ISSUE THREAD

**Issue by Todd442** [microsoft/BotFramework-Composer#3339]
We've gone through the effort to enable team development using the Bot Composer. Our solution now uses a Git repo to store the Bot artifacts and things are working pretty well. (There are a couple things we've had to address with multi-user but that's a different post).

The question is now. How best to automate the build and deployment of these artifacts in CI/CD pipelines. 

Do we have a script or official approach to do this or do we need to hand craft the WebApp deployment and LUIS deployments?

**Comment by cxbuilders** [comment]
@Todd442 #3170
We have a pipeline developed that builds and releases the composer bot all within Azure DevOps with currently the only exception the publishing of Luis. If you're interested let me know and maybe we can work together on this.

**Comment by jkergosi** [comment]
I'm also interested in this solution.

**Comment by Todd442** [comment]
I am interested!



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by cwhitten** [comment]
See https://github.com/microsoft/BotFramework-Composer/issues/3170#issuecomment-634153197 for suggested workaround to address this.

The team will look for document this method of creating plugins in an upcoming release.

**Comment by nathanvv** [comment]
I am at the same point where I have a bot+LUIS application and was hoping if I could use the azure DevOps pipeline to set up continuous deployment. Currently, I am using the publish feature from my local composer to deploy to the Azure resources that I created using the provisionComposer.js

![image](https://user-images.githubusercontent.com/11080029/87865075-1ec70d80-c936-11ea-958d-8159d6de8297.png)

Should I just end up using the build steps (https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-continuous-deployment?view=azure-bot-service-4.0) to deploy the bot services and create another cd for LUIS related resources?

The publish feature in the composer seems to be calling the API/publish/29624.65201173752/publish/testpublishprofile , would I be able to use something similar?

Was checking to see if anyone was able to already successfully set this up or there is a document that I can refer to

**Comment by cwhitten** [comment]
Hello! In an upcoming release we will provide documentation and examples on how to configure Composer to publish into a CI/CD infrastructure

**Comment by martinlarosa** [comment]
@cwhitten was that release 1.1.1 or some other coming later?

**Comment by cwhitten** [comment]
Hi @martinlarosa - not this November release but we anticipate the release after that.

**Comment by knightmeister** [comment]
Do we have an ETA on this, because I need to be able to commit to a CI/CD strategy.

**Comment by stevengum** [comment]
Per @cwhitten, the ETA is the next release, [post November's](https://github.com/microsoft/BotFramework-Composer/issues/3339#issuecomment-703810943).

**Comment by knightmeister** [comment]
> Per @cwhitten, the ETA is the next release, [post November's](https://github.com/microsoft/BotFramework-Composer/issues/3339#issuecomment-703810943).

Thanks @stevengum I read that - I am wondering when the estimated release date post November. I'm unsure of the cadence and how Christmas will affect it.

**Comment by parasdesaicims** [comment]
Hello @cwhitten  and @stevengum, do you have any update on when this will be released. If already released please share the link.

Thanks in advance.

**Comment by cwhitten** [comment]
No updates as of today, but it is a priority. We're currently working through the various resources one would use the implement CI/CD. Here is the latest that explains how to recreate the LUIS language modeling in a CI environment:

https://github.com/microsoft/BotFramework-Composer/blob/main/docs/archived%20docs/how-to-process-language-models-with-CI-CD.md#using-botframework-cli-tool-to-process-language-models-for-composer-bots

**Comment by rahul-8437008949** [comment]
Any updates on ci/cd approach?

**Comment by rahul-8437008949** [comment]
Are there any updates on CI/CD approach?

**Comment by rahul-8437008949** [comment]
Hello @cwhitten @stevengum ,Are there any updates on CI/CD approach?

**Comment by rahul-8437008949** [comment]
@cwhitten @stevengum ,I am facing the same problem ,Are there any updates?

**Comment by martinlarosa** [comment]
The solution is to deploy the bot app as a normal app in the normal deployment way for the platform you pick, and then the luis apps can be deployed using https://github.com/microsoft/botframework-cli/blob/main/packages/luis/README.md#bf-luisbuild
make sure that the output of that command is pointing to the path ./generated, since the json it generates needs to be inside that folder for composer to know the luis apps ids

**Comment by filipelteixeira** [comment]
Hey, it's unofficial, but I wrote an article about Bot Composer CI/CD built on GitHub and Azure DevOps, you can check it here https://filipelteixeira.com/blog/how-to-devops-pipeline-for-bot-composer.
The code is available at my GitHub: https://github.com/filipelteixeira/msft-mbf-composer-pokebot-pipeline
And the pipeline execution can be checked here: https://dev.azure.com/filipelteixeira/msft-mbf-composer-pipeline-pokebot
Hope it helps @jkergosi @Todd442 @rahul-8437008949 @parasdesaicims @knightmeister @nathanvv  :)

**Comment by cxbuilders** [comment]
@martinlarosa Currently Composer relies on the luis apps to be defined in the appsettings.json and having the generated folder or not has no effect. Additionally version 1.4 has removed the version property from the luis apps in the appsettings.json, which was present in 1.3. Having the version even breaks 1.4 with a 404 on luis prediction calls.

What you're stating is that indicative for relying solely on the luis generated folder for settings in upcoming releases and not have the luis apps defined in the appsettings.json anymore?

**Comment by martinlarosa** [comment]
I have never used luis app ids on appsettings with composer. So I can't comment on your first paragraph, sorry.

I was not talking about future releases, I was talking about how I currently use it, with 1.4 and before that with 1.3.something. Although I should clarify I didn't update the runtime of the bot since I ejected the runtime in the previous version to customize some things. Maybe that's why it keeps working for me. Generally I don't run the bot from composer, I only use it to do authoring of the dialogs, then I just run `bf luis:build` and then run the azurewebapp project with `dotnet run`

Even if it works/used to work with ids in appsetings, the thing is that since you are building the apps with bf cli using bf luis:build, you don't know beforehand the ids of the luis apps it will create. You get to know them when that command outputs that generated folder. Putting that folder in the bot makes it work querying those luis apps just fine. If you don't want to do that and if what you said about appsettings work, then you'd need to copy all the ids from the generated json file to the settings.

**Comment by cxbuilders** [comment]
@martinlarosa I am talking about the final state of composer published in the webapp. We have pipelines doing all the building and publishing into dev / acc / prod environments. Since this was changed between V1.3 & V1.4 I thought (mistakenly) you were saying here that the id's in the appsettings might not be required anymore in upcoming releases.

If you check the appsettings.json of a published bot in Azure you can see the luis id's there. These are in the end what makes Luis tick in a published Composer Bot, not the generated folder. So to me the role of the Generated folder ending up in the actual published webapp is not clear. I just have it as part of my pipeline, so at least the content of a webapp published by composer vs published by our pipelines is a 100% match.

**Comment by martinlarosa** [comment]
Are you using WebApp of Azure Function? 
I'm using WebApp and I'm using the generated json file because I saw the code in Microsoft.BotFramework.Composer.Core.ComposerSettingsExtensions
Maybe the deployment code in Composer moves the generated values to env variables? I'm not sure, I never deployed the bot using composer. Anyway, the important thing is that the bot needs in the settings at runtime a way to access settings like: luis.{appname}.appId. Wether the app reads that from rthe generated json file, the settings file, env variables or cli parameters, it doesn't really matter as long as they are loaded into memory.

Again since I found that code when trying to solve AppId '' is not a valid Luis Id, I went ahead and solved it that way since it was the most straight forward.

1. Run `bf luis:build'
2. Copy the generated folder into the web app artifact

Done.

Locally it's the same things since in order to run it locally I also run the `bf luis:build` and set the output directory to the bot's directory so that the generated folder ends up right where the app needs it. Then just run the bot using `dotnet run`. I believe this is what Composer does internally when you press the run button, probably some other extra stuff as well that we don't need yet.

**Comment by cxbuilders** [comment]
strange, for me it only works when the pipeline adds the actual app id's to the appsettings.json luis property. Maybe someone from the composer dev team can shed some light on the generated folders function vs appsettings.json app id's?

**Comment by martinlarosa** [comment]
in the settings do you have correctly set the luis environment and luis region so that it can find the output json correctly?
"luis.settings.{environment.ToLower()}.{luisRegion}.json"

**Comment by cxbuilders** [comment]
@martinlarosa Just looked into it, as it was annoying me :) The environment and the region are correct. I believe it actually does pick it up correctly in the webapp from the generated folder. The generated json file just gets added to the IConfiguration, as if it was part of the appsettings.json. However the issue I had to fix in V1.4 was that having the version in the appsettings.json as well broke Luis, so I just removed the version and only added the appId to appsettings.json and it worked ok. See luis appsettings below:
![image](https://user-images.githubusercontent.com/49873947/113501958-5eb43c00-9529-11eb-9ace-11c3d589487a.png)

The json file in the generated folder does have the version:
![image](https://user-images.githubusercontent.com/49873947/113502008-9e7b2380-9529-11eb-9f8b-ef758dd72a07.png)

And this then breaks luis again in the published webapp. Funny thing is that this only happens once published. The publishing mechanism in Composer also adds the appId in the exact same way to the appsettings.json like I am doing.

Anyone from the Dev team can shed some light on why this has been changed and what the underlying issue is with having the luis app version in the IConfiguration?

**Comment by Clooney24** [comment]
How will different LUIS contents for development/testing and production be differentiated when there is no version anymore? Dialog changes in development/test system should not affect productive LUIS content at all but should became productive within the deployment process.

**Comment by martinlarosa** [comment]
I'm very confused now, I'm using bf luis cli to do the publishing an it still adds the version in the json

**Comment by martinlarosa** [comment]
> How will different LUIS contents for development/testing and production be differentiated when there is no version anymore? Dialog changes in development/test system should not affect productive LUIS content at all but should became productive within the deployment process.

What is removing the version? New composer version or bf cli?
