### ISSUE TITLE
error on menu

### ISSUE THREAD

**Issue by madbeher** [microsoft/BotFramework-Composer#3447]
Hi,
I want to create menus yes/no but when i select the menus i am getting below error.
Can anybody give me a solution for this issue.

error: Object reference not set to an instance of an object.

thanks...

**Comment by hibrenda** [comment]
could you share the dialog file for more evaluation ?

**Comment by madbeher** [comment]
[luis1.zip](https://github.com/microsoft/BotFramework-Composer/files/4811995/luis1.zip)

I worked successfully with menus in Composer preview version but in New composer version i am getting error.

**Comment by hibrenda** [comment]
- Don't add choiceinput in Greeting as it will change the turn value. so you will get "object xxx" error due to turn.activity.membersAdded got changed.
![image](https://user-images.githubusercontent.com/43408889/85270408-d722a280-b4ab-11ea-9c79-7d897e39562b.png)
- try to avoid using '-' in variable. as "-" will be recognized as minus in expression which might got different meaning in condition filed 
option1 : using $answermenu instead of $anser-menu
option2:  change switch condition into following 
![image](https://user-images.githubusercontent.com/43408889/85270833-7e073e80-b4ac-11ea-9535-69e35015aaa8.png)

**Comment by madbeher** [comment]
thanks @hibrenda

**Comment by hibrenda** [comment]
close this as it has been solved
