### ISSUE TITLE
Improve error messages for common errors

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#3458]
Let's compile a list of common errors that could use some TLC.

**Comment by beyackle** [comment]
I'll take this one. I think it's a sensible approach to find all the user-facing strings and double-check they've got formatMessage on them, and then extract all of the formatMessage strings in order to go through and improve the ones that need it. This will also generate an initial `locales/en.json` file (or whatever other format we agree on) for use with i18n efforts later on.
