### ISSUE TITLE
Response Type "standard response" switches back to expression

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3580]
- Create a HTTP Request
-  Select "standard response" in the Response Type Value type dropdown
- Select Json
- Click away to another component and back again
- Dropdown is changed to expression
![image](https://user-images.githubusercontent.com/49873947/86788948-09650000-c067-11ea-9ead-61489f5e1959.png)

**Comment by tdurnford** [comment]
@cxbuilders 

It looks like the `getSelectedOption` function in the Expression ui-plugin,  which is responsible for setting the dropdown, does not check if the `value` is included in the `enumOptions`. As a result, it sets the dropdown to 'expression' instead of 'standard response.'


https://github.com/microsoft/BotFramework-Composer/blob/182f4220e3e200791d07ef6243cfbc904632cf7b/Composer/packages/ui-plugins/expressions/src/utils.ts#L113

**Comment by cxbuilders** [comment]
@tdurnford Thanks for the update. Bit amazed to see the value type is not stored and attempts are made to extract the value type from the actual value. This also explains all the strange behavior I have seen with this functionality. Eg, adding a string like '=Some Text' would be perfectly valid, but then Composer decides it is an expression.

Not sure why this approach is used for Value Types, but to me that seems like a setup that keeps on giving...

**Comment by tdurnford** [comment]
@cxbuilders Unfortunately, there isn't a place to store the selected types in the dialog files since the Adaptive Dialogs package infers how to handle the value from the Dialog Schema and the actual value provided by the developer - not from the type selected in the dropdown. If the schema type for the property is an expression that evaluates to a string and you begin the string with an equal sign, the Adaptive Dialogs package will interpret that value as an expression - not as a string - because the equal sign denotes the value is an expression.  We want to convey how the runtime will utilize the value by setting the dropdown to how the Adaptive Dialogs package will interpret the value. I understand the experience can be a bit strange as it is currently, but we have some work scheduled to revisit this editing experience in the near future.
