### ISSUE TITLE
Support `fieldsets` in ui schema

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#3588]
## Is your feature request related to a problem? Please describe.

As a developer of a custom sdk component, I would like to be able to have better control over the organization of the form UI by being able to group fields together in fieldsets.

## Describe the solution you'd like

```json
{
  "fieldsets": [
    {
      "title": "Advanced Settings",
      "fields": ["autoEndDialog", "disabled", "..."],
      "defaultCollapsed": true
    }
  ]
}
```

## Additional context

This could also support the tabbed view that we do with the prompts today.

**Comment by a-b-r-o-w-n** [comment]
@sangwoohaan @mareekuh Getting this on your radar to start a discussion. @tomlm has requested this feature in the ui schema that we currently don't support. 

Since we have talked about hiding some fields behind an "Advanced" section, I think this would be a good way to achieve that. Let's use this thread to discuss.

**Comment by mareekuh** [comment]
Could you share some examples of the scenario - what is the dev trying to accomplish? And what would be common examples for which fieldsets are needed/used?

**Comment by tomlm** [comment]
Any time you build a form UX which edits a number of fields you almost always end up wanting to organize them to make it easier to understand.  For example

Color Properties
* BackgroundColor
* ForegroundColor
* TextColor
* Border Color

Another example is cluster things so that less used fields are below the fold or only accessible for advanced users.

Field1
Field2
Field3

Advanced Options<--collapsed -->
* Advanced Field1
* Advanced Field2
* Advanced Field3

This has been part of GUIs toolkits and design since they were invented and every GUI system since then has supported this as a design pattern.

**FieldSet** is the name of the way that w3 HTML defined it all the way back to HTML 1 as the way to group input fields in a form 
[www.w3.org](https://www.w3.org/WAI/tutorials/forms/grouping/)

It a key way of reducing the cognitive load of someone who is presented with a number of fields, and so shows up in many design style best practices:
* [form design](https://www.nngroup.com/articles/form-design-white-space/)
* [Form design best practices](https://www.ventureharbour.com/form-design-best-practices/)

> If your form has more than six fields, it’s considered good practice to group questions into logical sections or steps.
