### ISSUE TITLE
[MCS-DE] Local Publishing Plug-In LUIS Issues

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#3639]
When running the Start Bot from the ElectronAPp v 1.0.2 the following issues arise:

1. First publish does not attach the Prediction Ressource to the newly created LUIS apps.
2. Each Publish does also update the LUIS Apps from the first "Azure WebApp Publishing" profile although these are separate from the ones created and used for the local testing.

@benbrown

**Comment by hibrenda** [comment]
@goergenj This is by design so far (known issue). we can improve it later.

**Comment by luhan2017** [comment]
@mareekuh @sangwoohaan, we need a design to input the prediction resource key in the local publish page.

![image](https://user-images.githubusercontent.com/32191031/95734534-289ea980-0cb6-11eb-85c8-c23ba30f8afe.png)

**Comment by luhan2017** [comment]
I did some investigation and found that to we need the azure access token to bind the prediction resource with the luis app, which means if we want to enable this, we need to ask user for their azure access token.

**Comment by cwhitten** [comment]
@luhan2017 with the endpoint key in the LUIS form is this still an issue?

**Comment by luhan2017** [comment]
@cwhitten, Yes, though we expose the endpoint key in the form, if user want to use the endpoint key, they still need to manually bind the luis app with the prediction resource. We can't achieve this right now because, we need the azure access token to do the binding. But we did have a plan in R12 to support azure login and some UX experience similar as provision for local luis settings configurations.

**Comment by mareekuh** [comment]
@emivers8 is this still 'live' UI, in other words, should I add this to the Copy List?

**Comment by goergenj** [comment]
Should this be solved in v2.0?
