### ISSUE TITLE
UX design for QnA in Multi-Lang

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#3685]
The inline QnA editing will be landed in composer. As LU/LG multi-lang have been supported in Composer now, we may leverage the similar design. 

For lu/lg multi-lang support, we only need to translate the utterance or response. so we can use "intent name" or "lg template name" as the placeholder across the different languages and this will help us to do the language comparison in the list view . But QnA has more fine-grained in-place editing in list view .  Both question and answer need to be translated.  so it is hard to list out items comparison as what we delivered in lu/lg all up view.  

At this moment, we did not introduce the trigger to hoist with specific QnA question, so we only need to take care about the whole QnA file translation experience .

**Comment by luhan2017** [comment]
@vivekkshankar @mareekuh @cwhitten , good news, the multi language support within one qna service has been released recently. So the QnA Multi-lang is unblocked and maybe we can start the work on the design?

**Comment by mareekuh** [comment]
Exciting! @cwhitten - This is a great oppty to see how we can better integrate QnA into the main Composer experience vs adding a 4th place for users to go to deal with translation/language management (Settings, LU, LG and potentially QnA).
Is Prashant still your contact on QnA or has this since switched to Somi Reddy?

@vivekkshankar let's talk before getting started.

**Comment by mareekuh** [comment]
I think this is done, no? @vivekkshankar
