### ISSUE TITLE
Multi-Lang support for luis supported language

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#3699]
Problem : LUIS service only support for limited language  but QnA and LG do not have such constraint . So if user add not supported language for LUIS editing and start bot . Composer will not complain any error. Once user specify that language in emulator to test the bot, user will not get expected LUIS recognition.

Proposed Solution : User will get warning/errors during the bot start for LUIS only bot or LUIS+QnA bot . No language constraint for QnA only bot. 

Scenario 1: Assume "abc" language is not supported by LUIS service, user add the "abc" language and removed the "en-us" language. so both "default-language" and "bot language" are set into "abc". User click "start bot", composer will report error and bot could not be started as there is no correct fall-back language to set for LUIS recognizer.

Scenario 2: Assume "abc" language is not supported by LUIS service, user keep the default language as "en-us" and add the "abc" language to the bot for luis editing. User click "start bot", composer will warn user "abc" language is not supported but "en-us" can be successfully published to LUIS and QnA. Bot can be started. Later if user specify the language "abc" in Emulator, as there is no "abc" recognizer, so bot will be fallback to "en-us" to recognize the user input.

Scenario 3: Assume "abc" language is not supported by LUIS service, user add the "abc" language (not removing "en-us" language") and set it as a default language . User click "start bot", composer will warn user "abc" language is not supported and warn user "default-language" will be set to "en-us" (if "en-us" is not available, composer will choose the first supported LUIS language listed under "languages".) Bot will be started. Later if user specify the language "abc" in Emulator, as there is no "abc" recognizer, so bot will be fallback to the default language.

**Comment by zhixzhan** [comment]
I can add more check on composer side base on Luis & Qna supported language list and fallback policy, produce warnings, and let user start bot as much as possible.

**Comment by vivekkshankar** [comment]
@hibrenda 

Here are few thoughts on this,

We should  try to avoid a) A bad creator experience where the author creates bunch of LU intents only to realize that the language is unsupported. Thats going to be frustrating.  b) A bad end user experience - where the bot doesn't respond because the language is not supported in run time. 

To solve for A for now lets,

- As discussed we need to show a warning in line in the settings page - to indicate that a particular language is unsupported by LUIS. Repeat these warnings in the LU editing page. We need to convey this warning in a way that is not confusing to the user (they might not even be aware or LU/QnA concepts at this point)
- We should revisit the adding and removing of languages concept... maybe do not allow removing some basic languages supported by LU so we don't run into cases where no supported language is left in the default list. 


@mareekuh @sangwoohaan FYI

**Comment by mareekuh** [comment]
@vivekkshankar - do you want to take this? 
I will also forward you a thread on the documentation for MultiLang - the capability of our MultiLang is very limited and it's becoming clear that the design does not appropriately set expectations. Let's discuss so you're up to speed on the why and how of the current design and then take it forward?
