### ISSUE TITLE
Composer does not groups comments with LG definition that immediately follow then

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#3808]
## Describe the bug

In the Bot Responses view, if the user types comments before a definition in edit mode and then switched out of edit mode, the view shows comments at the end of the previous definition instead of grouped with the immediately following definition.

## Version

main branch - fd2a6d4f06d8322855f4edd03ad7edc884872912

## Browser

- [ ] Electron distribution
- [ X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X ] Windows 10
- [ ] Ubuntu

## To Reproduce

1. Create a bot project
2. Go to the Bot Responses screen
3. Enter edit mode
4. Add LG like the following:

> ---------------------------------------- Comment 1  ----------------------------------------
> A detailed comment
# First_definition
- A reponse

> ---------------------------------------- Comment 2 ----------------------------------------
> Another detailed comment
# Second_definition
- Another response

5. Switch out of edit mode

## Expected behavior

The comments should appear associated with the definition immediately following them, not with the previous definition

## Screenshots

<img width="581" alt="Screenshot 2020-08-07 141001" src="https://user-images.githubusercontent.com/28762486/89688766-baa1c480-d8b7-11ea-8ec9-319263f82b0b.png">

**Comment by cosmicshuai** [comment]
Hi @GeoffCoxMSFT, I completely agree with you, the comments should be better aligned with the templates. 
Here is some of our thoughts and common usage of comments in LG.
For an empty LG file. There will be two lines of comments at the head. 
```
> To learn more about the LG file format, read the documentation at
> https://aka.ms/lg-file-format
``` 

Moreover, due to the comments line are very flexible, user can type anywhere in the LG file. So it will be a little tricky for the parser to decide which template should contain a certain line of comment.

I recommend the comments of a template can be placed under the template name line which can provide more clarity in the non-editor mode. 
![image](https://user-images.githubusercontent.com/17074777/92361144-8886bb00-f120-11ea-88c8-61aec82dc124.png)

![image](https://user-images.githubusercontent.com/17074777/92361088-773dae80-f120-11ea-8f36-4371eae26d44.png)

**Comment by cwhitten** [comment]
It would make sense to instead render the comment under the name column, or a in a new column (I believe form dialogs will be utilizing comments in a separate column)

It's odd to have it render in the responses column. @GeoffCoxMSFT is a change required here to render the form dialogs UX? If so, we can fund this through that effort, perhaps and reassign to a different dev.

**Comment by mewa1024** [comment]
Can we hide the comments in the UI view (the not-code view) of LG? So in other words, remove from here:
![image](https://user-images.githubusercontent.com/39317542/105437976-f8e93100-5c16-11eb-9cae-d763073e1349.png)

and here:
![image](https://user-images.githubusercontent.com/39317542/105438126-3ea5f980-5c17-11eb-8149-3cb1321bdba3.png)
