### ISSUE TITLE
Is there are possiblity of switching LUIS resources from authoring resources to prediction resources? as I have Authoring resource available only in F0 tier and I get the following error

### ISSUE THREAD

**Issue by likith3611** [microsoft/BotFramework-Composer#3818]
<img width="454" alt="luiserror" src="https://user-images.githubusercontent.com/49705166/89762516-36954a00-db0e-11ea-9520-48e7766fbc6e.PNG">

Can you please help me solve this issue

**Comment by luhan2017** [comment]
@likith3611 , if you are using the composer locally, you could do this:

1. go to luis website, find the application, and bind it to a prediction resource. 
2. Then copy the prediction service key, and place it to luis.endpointKey. 
3. restart your bot and try again.

![image](https://user-images.githubusercontent.com/32191031/89876216-ec38c980-dbf0-11ea-8179-e74a1e863635.png)

**Comment by likith3611** [comment]
Yes actually I am doing the same but we have an option for authoring key right what must we mention there? if i mention authoring resource key it shows the same error because I have exceeded the free usage for the month

**Comment by luhan2017** [comment]
I am not sure if I understand correctly, In Luis, the authoring service is designed for creating you luis applictions, though it can be used as prediction, but it is not recommended. In a production scenario, you definitely need a prediction service and use that to do the luis intent understanding instead of using the authoring service.

**Comment by likith3611** [comment]
ohh ok understood thanks a lot
