### ISSUE TITLE
Reloading via ctrl-r on the Settings page of a bot with an ejected runtime throws an error

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#3845]
<img width="1679" alt="Screen Shot 2020-08-13 at 6 47 41 PM" src="https://user-images.githubusercontent.com/1156704/90203494-c39e0480-dd95-11ea-94a5-b9bd69f44ad9.png">

**Comment by zhixzhan** [comment]
Repro step 
1. open setting page
2. runtime config
3. use custom runtime
4. add c# runtime, done
5, refresh, ctrl-r
<img width="329" alt="image" src="https://user-images.githubusercontent.com/49866537/90207238-51bacf00-de18-11ea-9780-3bae06deec7b.png">

The page turned out to be `no bot is opened` status, seems opened project not persistence at client.
