### ISSUE TITLE
Ejecting runtime to get a new copy of the runtime code can lose file attributes

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#3850]
## Describe the bug

The localPublish plug-in copyDir function does a content copy of files by reading the file content into memory and then writing it to the destination.  I'm not sure why it doesn't use the copyFile function imported on the IFileStorage interface.

This is the problem code:
https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/plugins/localPublish/src/copyDir.ts

    // copy files
    const content = await srcStorage.readFile(srcPath);
    await dstStorage.writeFile(dstPath, content);

## Version

Main branch - fd5d15a36d7e8407f47b301b05d3af548d9da776

## Browser

- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Run dev environment (yarn start:dev)
2. Ensure that plugins/localPublish/hostedBots is empty
3. Publish a bot using the default runtime
4. Eject the runtime and choose to copy a new C# runtime
5. Inspect the file attributes on the ejected runtime.

## Expected behavior

File attributes should included with ejected runtime files

**Comment by VanyLaw** [comment]
@GeoffCoxMSFT That's because the source Storage and destination Storage may not be the same storage. Such like copying the files from remote Storage into local Storage. We did this due to the storage extensibility.

**Comment by benbrown** [comment]
We can't actually have 2 different storage drivers active at the same time, so this should not block us from changing the mechanism for copying files.

@geoffcoxmsft can you give a bit more information about what problems this causes for you?

**Comment by zidaneymar** [comment]
@GeoffCoxMSFT Currently the file system is using local storage, I'm not sure if this IStorage interface will be implemented by other ways. I guess the main reason here is to insure the dstStorage could write 'content' successfully, maybe in the future the dstStorage could be located in another disk.

Maybe we can't just srcStorage.copyFile to the 'dstPath' since the dstPath only makes sense to the dstStorage.

```
const content = await srcStorage.readFile(srcPath);
await dstStorage.writeFile(dstPath, content); 
```

**Comment by boydc2014** [comment]
@GeoffCoxMSFT is there a specific scenario that are requiring this? the reason asking is in current design the copyDir function is for copying folder inside one storage. But the code here 
```
// copy files
const content = await srcStorage.readFile(srcPath);
await dstStorage.writeFile(dstPath, content);
```
is copying from a source storage folder to a destination storage, which can't simply replaced by copyDir.

If this is blocking for you, i would proposed we added an attribute filePath in LocalFileStroage and implement an comparator in IFileStorage, so that we can do copyDir when src == dst, otherwise do read\write.

If this is non-blocking, how about let's move this to R12? 

cc @luhan2017 @zidaneymar

**Comment by zidaneymar** [comment]
Close this issue, could reopen if needed
