### ISSUE TITLE
Ejecting runtime in dev environment with updated runtime bits causes stale runtime bits to be used in emulator

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#3851]
## Describe the bug

In developer mode (yarn start:dev) the localPublish plug-in will copy files from the Composer runtime folder into a hostedBots folder.  If a developer is working on a project and publishes it to emulator and then later updates the Composer runtime bits with a new version, the localPublish code keeps using the stale runtime bits in the hostedBots folder.

I believe this is the problem code:
https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/plugins/localPublish/src/index.ts

eject: async (project, localDisk: IFileStorage) => {
      const sourcePath = path.resolve(__dirname, '../../../../runtime/dotnet');
      const destPath = path.join(project.dir, 'runtime');
      if (!(await project.fileStorage.exists(destPath))) {

This code either needs a better check against the checksum/version/date of the bits or to avoid caching the runtime and copy the files every time.  This was particularly problematic for the Composer Core and WebApp DLLs as their versions are always 1.0.0 and only the date stamp distinguishes revs.

## Version

Main branch: fd5d15a36d7e8407f47b301b05d3af548d9da776

## Browser

- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Start composer in dev mode
2. Eject the runtime and copy a new C# runtime for a project
3. Update the composer runtime components to a different version
4. Delete the runtime folder and go back to using the default runtime
5. Eject the runtime again and copy a new C# runtime again
6. Inspect the versions/date of the runtime bits 

## Expected behavior

Always have the latest runtime in copied runtimes and hosted default runtimes.

**Comment by zidaneymar** [comment]
Hi @GeoffCoxMSFT , I'm not sure if I understand your problem. If you eject your runtime, you would have a copy instance of your C# **runtime template**, then if you make any changes to that **runtime instance**, composer **will not** update the template based on your changes. So If you delete your runtime instance and re-eject the runtime, composer will not record the changes you make to the instance, but get a brand new copy based on the template (the stale runtime you mentioned). I think this is by design.

**Comment by luhan2017** [comment]
ejected runtime deprecated.
