### ISSUE TITLE
Move LU and LG LSP's into service workers

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#3896]
This accrues value towards Composer's goal of being easily host-able

**Comment by boydc2014** [comment]
@tonyanziano can you share what your discovery was?

**Comment by tonyanziano** [comment]
Assuming that this means porting the actual parsing work done by the language servers to service workers, here were my findings:

- Initially, I thought that this would prove difficult due to service workers not being able to understand Web Sockets -- which is the model that the current language servers use when connecting with the Monaco editor.
- However, service workers have access to an API ([`postMessage()` / `onMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage)) that is very similar to the API that Web Sockets use.
- I believe that to port the parsing logic over to the service workers, you would need to do the following:
  - Move the parsing logic into the worker file
  - Have the language servers forward any Web Socket messages from the client to the parsers via the `postMessage()` API
  - Receive results back from the parsers via the `onMessage` API and forward them back to the client via Web Sockets

There might even be a way to skip this middleman role played by the language servers here, and bind the `postMessage() / onMessage` API directly to the connection with the Monaco editor. This way the entire language server could be moved to the service worker.
