### ISSUE TITLE
What is purpose of debugging options in bot composer.

### ISSUE THREAD

**Issue by Shivang007-del** [microsoft/BotFramework-Composer#3905]
What is purpose of debugging options in bot composer.Can I use them in the bot framework to get trace and can it also be in power virtual agents to get error details and to trace?

**Comment by benbrown** [comment]
The "emit a trace event" will cause your bot runtime to emit a special event that can be viewed inside the Emulator debug panel.

The "Log to console" will cause your bot runtime to log out your message to the terminal/console where your bot application is running.  These log events are not directly viewable when running Composer as an electron app, however if you run the bot application yourself from the command line you will see them.

**Comment by Shivang007-del** [comment]
can you please share any sample code for "Log to console" .

**Comment by benbrown** [comment]
There is no code involved... you would configure a log to console action like this:

![Screen Shot 2020-08-26 at 3 28 23 PM](https://user-images.githubusercontent.com/729873/91353384-d4487480-e7b0-11ea-8ed1-89ad228060f3.png)

This would result in the message "DEBUG: The ticket body is <some value>" being printed to the console during the course of the bot execution.

Since I also set "send trace activity" to true, it would emit a trace visible in the emulator.
