### ISSUE TITLE
multilingual feature in bot composer not working for hero and adaptive cards etc...

### ISSUE THREAD

**Issue by madbeher** [microsoft/BotFramework-Composer#4019]
I have a sample echo bot in bot composer and applied translation middleware logic as mentioned in the below url documentation.
https://github.com/microsoft/BotFramework-Composer/issues/3514
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/17.multilingual-bot

The multi lingual feature is working fine for normal text messages but if i add hero or adaptive card in the bot it is
giving error and translation is not working. what things need to be changed so that multilingual feature will work for
messages of type hero and adaptive card.

For hero card message it is giving bad request error as shown in below screenshot.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/36945600/92106795-8102a180-ee02-11ea-86db-3d61e293b0fc.png)

**Comment by v-kydela** [comment]
Thank you for the report, @madbeher 

I'm afraid the translation middleware is only [designed](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/17.multilingual-bot/Translation/TranslationMiddleware.cs#L106-L112) to translate the `text` property and nothing else. Translating cards is complicated because the translator needs to know which properties to translate and which properties not to translate.

I've built an Adaptive Cards translator that hasn't been released yet, but you can find a sample here: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/feature/cards/samples/Cards%20Library%20Sample

If you're interested in that code, you can voice your support on this issue: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/issues/137

I hope that helps.
