### ISSUE TITLE
[UX] Recognizer type's naming rule needs to be consistent 

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/BotFramework-Composer#4060]
## Describe the bug

![image](https://user-images.githubusercontent.com/16643193/92429771-904c6b00-f1c5-11ea-9bf6-94c97f4c3046.png)

**Comment by cwhitten** [comment]
@DingmaomaoBJTU please submit a pr to fix this.

**Comment by zxyanliu** [comment]
We can follow the sentence case and make the language and style consistent. 

Proposing the following:

* Default recognizer
* Regular expression recognizer
* Custom recognizer

**Comment by stevkan** [comment]
@zxyanliu,

I think, because "Regular Expressions" is a technology and is referred to by the same name in the various readme files, it should read "Regular Expression recognizer". Or, possibly "Regular Expressions recognizer", if we want to keep the actual name the same, as well.

Thoughts?

**Comment by zxyanliu** [comment]
@stevkan I liked your comment on this because I was having the same confusion before proposing the names. 
I thought Regular Expressions is a proper name, meaning we should capitalize both "R" and "E", however, it might not be the case.

For the books I referred to (since I was unable to find the term in either [Merriam-webster dictionary](https://www.merriam-webster.com/) or [Cambridge English dictionary](https://dictionary.cambridge.org/us/) ), all of them have lower case when address "regular expressions".  FYI. 

* [Mastering Regular Expressions (3rd edition)](https://www.amazon.com/dp/B007I8S1X0/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1) Jeffrey E. F. Friedl.
* [Regular Expressions](https://www.amazon.com/dp/1683922271?tag=uuid10-20) by Oswald Campesato
* [Introducing Regular Expressions](https://www.amazon.com/dp/1449392687?tag=uuid10-20) by Michael Fitzgerald.

**Comment by stevkan** [comment]
@zxyanliu, I agree with your assessment. Looking more broadly, I can see other examples that demonstrate the same. I will move forward with your recommendation.

**Comment by zxyanliu** [comment]
@stevkan Thanks! Hope it helps. : )
