### ISSUE TITLE
Composer Skills: Skill bot returning adaptive/hero cards end conversation (preventing multi-turn skill flow). If by design, add documentation.

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#4152]
## Scenario: develop parent/skill bots for multi-turn interaction where skill bot returns an adaptive or hero card in turn.
* Parent bot (using Composer) - call skill
* Skill bot (using Composer) - sends an adaptive or hero card waiting for response for multi-turn interaction.
--> skill conversation terminates. 
Fix: add end-turn after the card and multi-turn can continue
Note: other responses such as prompt or text response apparently do not terminate the skill. 

Issue: This interaction isn't obvious. If by design, needs corresponding documentation. If a bug, fix it such that cards in skills permit multi-turn (i.e. do not terminate multi-turn skill conversation).

(@luhan2017 may be able to elaborate).

**Comment by benbrown** [comment]
@luhan2017 can you shed some more light on this for us? 

I don't understand what would cause the skill to end simply because a card is sent...

**Comment by luhan2017** [comment]
@benbrown 
For a bot served as a skill, we set the autoEndDialog flag to true, which means what if there is no actions in the dialog stack, the main dialog will end, and send EOC to parent bot. This is always the expected behavior, because if we don't do this, the dialog in skill will never end. 

In Eyal‘s skill bot, the dialog ends when it send the adaptive card, if it is bot mode, the bot will still wait for user's input, if it is skill mode, the bot will send EOC to parent bot. 

I think Eyal‘s request is we should clearly document this to users, if you want your bot served as a skill, and if you expecting another turn when there is no actions in stack, please add an EndTurn action to do that. 

@scheyal could you please help double confirm on your request?
