### ISSUE TITLE
Microsoft Teams file handling

### ISSUE THREAD

**Issue by eluchsinger** [microsoft/BotFramework-Composer#4213]
## Describe the bug

If I send a file using MS Teams, the bot will not receive the file like it does on the WebChat or Bot Framework Emulator.

The Teams Bot's `supportsFile` flag is set to true.

## Version

v1.1.1

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Import the bot to Microsoft Teams
2. Send a File to the bot
3. The bot will not handle the file like it does with the Webchat or Bot Framework Emulator.

## Expected behavior

The Bot handles the file exactly the same, regardless of the channel it is using.

**Comment by v-kydela** [comment]
Thank you for the report, @eluchsinger 

I think your expected behavior may not be correct. A lot of things can be considered channel-specific, like attachments. The ability to upload a file to a conversation is dependent on the client application allowing you to do so, and that makes it channel-specific behavior. Is the bot really not receiving the attachment at all, or is it just not handling the attachment the way you expect?

**Comment by v-kydela** [comment]
@eluchsinger - Are you still working on this?

**Comment by eluchsinger** [comment]
Hi @v-kydela yes, I'm still working on this, but we had to switch the focus to other features right now. I may have to come back to further investigate before go-live.

**Comment by v-kydela** [comment]
@eluchsinger - Would you like to close this issue then?

**Comment by eluchsinger** [comment]
I'll close the issue until I have more time to research. Feel free to reopen it, in case someone hits a similar issue.
