### ISSUE TITLE
Launching Composer on W10 launches 4 apps at the same time  

### ISSUE THREAD

**Issue by michielpr** [microsoft/BotFramework-Composer#4334]
## Describe the bug

Launching Composer takes a long time. At the start, it creates 4 different instances of itself. Only when the 4th one launches, Composer opens. Prior to creating any bot OR launching the emulator, Composer has also created 12 different services for itself which seems inefficient. 

Launching an empty composer takes about 0.5Gb of memory.  

## Version

1.1.1

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

W10

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch Composer via the desktop icon. 

## Screenshots
![Screen Shot 2020-10-05 at 8 34 44 AM](https://user-images.githubusercontent.com/47259560/95250652-414b2300-07cf-11eb-99ed-a427c7c651ea.png)

**Comment by cwhitten** [comment]
@michielpr we're not sure if this is a bug yet, in fact it may be expected behavior. It isn't 4 APPS, but it could rather be 1 app + 3 child processes. Anecdotally, Microsoft Teams opens 10 processes.

We could take a bug to _name_ these child processes to better explain the fact that Composer launches more than one process.

Incidentally, were you experiencing odd behavior that led you to open the Task Manager in the first place?

**Comment by michielpr** [comment]
Oh interesting. Thanks for the clarification @cwhitten. 

A bit more context: 
I opened the task manager as the start-up was taking quite some time (blame it on curiosity).  
On the screenshot you can see that there Composer has 4 applications and 12 child/background processes. Is that something as expected?

_As a side-note: only when the 4th application is loaded, the application UI becomes visible._
