### ISSUE TITLE
The commands in both edit menus are out of sync

### ISSUE THREAD

**Issue by michielpr** [microsoft/BotFramework-Composer#4335]
## Describe the bug

When I open the both edit menus, at times they will have different states. This cannot be the case. 

## Version

1.1.1

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

Open both edit dropdowns on the home screen 

## Expected behavior

Both menus need to be in sync so that a user doesn't get conflicting information when he/she can copy/paste etc. 

## Screenshots

<img width="563" alt="Screen Shot 2020-10-07 at 6 06 41 AM" src="https://user-images.githubusercontent.com/47259560/95361013-086b8680-0881-11eb-811b-971011e60fe3.png">

**Comment by yeze322** [comment]
It's a little tricky here but it's actually as-desgined. The Electron's app menu has 2 modes, one for Flow Canvas, another for system's default behavior.

1. When you are focusing on the flow canvas part (there will appear a border), the Electron's menu will be synced with Toolbar's menu. Cut / Copy / Delete will operate on action nodes.
2. When you are focusing on other parts of the Electron App, default system shortcuts will take over the Electron's menu, it means that if you selected some plain text, Cut / Copy / Delete will operate on the plain text.

The reason we can't simply let the Electron's menu be synced with Flow Canvase state is because of system's default shortcuts (cut/copy/paste) are only available when the Electron's app menu items are enabled, if two menus are in sync, when no Action node is selected, you can't even cut/copy/del a plain text in a text input via Ctrl+C/V.

**Comment by yeze322** [comment]
FYI https://github.com/microsoft/BotFramework-Composer/pull/3846

**Comment by cwhitten** [comment]
@mareekuh let's follow-up on this to make sure we stay consistent with other desktop applications

**Comment by mareekuh** [comment]
@JaskeeratBedi-cmk and @vivekkshankar  where are we with this and does this need to get a new work item to get addressed?

**Comment by mewa1024** [comment]
This has been addressed in Jas's menubar designs. Here is a snippet from the Figma mockup:
![image](https://user-images.githubusercontent.com/39317542/124333534-59c35080-db49-11eb-8c9e-f25a10013d4c.png)

https://www.figma.com/file/J3oIdXDmeBQbAe4a4PYbQc/Jaskeerat-s-files?node-id=3737%3A48

**Comment by mewa1024** [comment]
Closing is this is addressed in #6959
