### ISSUE TITLE
Configurable Delay Node

### ISSUE THREAD

**Issue by kdubious** [microsoft/BotFramework-Composer#4406]
## Describe the solution you'd like

Would be nice to include a node that implements a configurable delay. Even nicer to show an animated "..." in the WebChat UI.

## Describe alternatives you've considered

I suppose one could "Send an HTTP Request" to a backend that accepts the delay length as a query param and returns based on that delay. But this is hacky.

**Comment by EricDahlvang** [comment]
Hi @kdubious 

The sdk does provide a 'delay' activity type, which can be used from composer:

```
[Activity
    Value = ${3000}
    Type = ${"delay"}
]
```

![image](https://user-images.githubusercontent.com/11055362/96386824-a2211680-1152-11eb-8012-fcec78a75f4c.png)

Note: this does not work as expected from the emulator, i think because it is holding the calling thread and waiting for completion.  It does work from channels however.

We should maybe consider adding a property to SendActivity, enabling a pause afterwards.  Or some such feature.

**Comment by kdubious** [comment]
@EricDahlvang OK, I'll try this out, thanks. Yes, would certainly be best if the Emulator provided the right experience with it.

**Comment by EricDahlvang** [comment]
Closing in favor of re-opening https://github.com/microsoft/botbuilder-dotnet/issues/4509#issuecomment-708188371

Thanks for raising this issue @kdubious This helps confirm we should support this in a more simplified way.
