### ISSUE TITLE
Custom Runtime Error

### ISSUE THREAD

**Issue by kdubious** [microsoft/BotFramework-Composer#4416]
## Describe the bug

I followed the steps outlined in:
https://docs.microsoft.com/en-us/composer/how-to-add-custom-action

There are many warnings after this step:
`Parsing component .schema files`

Warning C:\Users\kdubi\.nuget\packages\Microsoft.Bot.Builder.AI.Luis\4.10.2\content\Schemas\Microsoft.LuisRecognizer.schema: Component schema https://schemas.botframework.com/schemas/component/v1.0/component.schema does not match https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/component/component.schema

When I re-open Composer, I get this error:
"Definition not found for Microsoft.Ask/properties/activity/oneOf/1/properties/membersAdded/items"

## Version
v 1.1.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Screenshots

![image](https://user-images.githubusercontent.com/9756166/96400594-27321d00-119f-11eb-8c68-f6502ecd824a.png)

**Comment by kdubious** [comment]
The custom action does work, though.

**Comment by stevengum** [comment]
@dmvtech can you investigate and report back? Thanks!

**Comment by luhan2017** [comment]
@kdubious , could you check the your bf cli version, is it pointing to the latest?

**Comment by rmthurman** [comment]
I am getting the same issue, and 2 of my customers writing bots in Composer found this as well.  The custom action does work once you click through the error.

**Comment by dmvtech** [comment]
I can confirm this experience. I tried with both versions:
`@microsoft/botframework-cli/4.10.1 win32-x64 node-v12.18.3` and
`@microsoft/botframework-cli/4.10.0-dev.20200730.3786d10 win32-x64 node-v12.18.3`

Just a lot of warnings, it does work. I think this is a BF cli issue as it's definitely coming from `bf dialog:merge` and not the .ps1 script.

**Comment by dmvtech** [comment]
Sorry maybe not a BF cli issue, but it is the one reporting it. There definitely is a schema mis-match, due to the ID:

https://schemas.botframework.com/schemas/component/v1.0/component.schema:
    `"$id": "https://schemas.botframework.com/schemas/component/v1.0/component.schema"`

https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/component/component.schema
  `"$id": "https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/component/component.schema"`

**Comment by chrimc62** [comment]
@Kaiqb the issue is in the documentation at: [custom action](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action).  The $schema should be https://schemas.botframework.com/schemas/component/v1.0/component.schema.

@kdubious you can fix this by changing the $schema in your custom action .schema file.

**Comment by zxyanliu** [comment]
FYI. The [doc](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#about-the-example-custom-action) actually references the schema from [here](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action). 
@luhan2017 Can you take a look and see if I need to update the doc?

**Comment by dmvtech** [comment]
@zxyanliu 

> Then run ./update-schema.ps1 -runtime azurewebapp in powershell again.

But when running this (after remedying your execution policy), did you no longer get any Warnings output in the shell/cmdline? They should have looked like:
`Warning C:\Users\kdubi.nuget\packages\Microsoft.Bot.Builder.AI.Luis\4.10.2\content\Schemas\Microsoft.LuisRecognizer.schema: Component schema https://schemas.botframework.com/schemas/component/v1.0/component.schema does not match https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/component/component.schema`

The issue is not that it _fails_, it's that it is outputting a bunch of warnings (even though in the end it runs).

**Comment by zxyanliu** [comment]
@dmvtech 
Yes, I did get a lot of warnings about mismatched schema:

![image](https://user-images.githubusercontent.com/32497439/97050109-a160f980-1531-11eb-9bfb-c621967977f7.png)

The warnings went away after I updated the $schema in the sample to be https://schemas.botframework.com/schemas/component/v1.0/component.schema

See: 
![image](https://user-images.githubusercontent.com/32497439/97050191-c7869980-1531-11eb-80cb-51244e2e1b2b.png)

**Comment by zxyanliu** [comment]
We should update the following in the [sample schema](https://github.com/microsoft/BotFramework-Composer/blob/main/runtime/dotnet/customaction/Schemas/MultiplyDialog.schema):

The $schema should be https://schemas.botframework.com/schemas/component/v1.0/component.schema
