### ISSUE TITLE
Get Chat History in a Custom Action

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#4418]
How can one get the chat history in Composer using a Custom Action?

**Comment by v-kydela** [comment]
Thank you for the question, @cxbuilders 

We do prefer to have how-to questions asked on [Stack Overflow](https://stackoverflow.com/questions/ask) instead of GitHub. This reaches a larger audience, allowing more people to possibly answer the question and more people to be helped by the answer. If you use the [`botframework`](https://stackoverflow.com/questions/tagged/botframework) tag then my team will be sure to see the question. Make sure you follow [this guide](https://stackoverflow.com/help/how-to-ask) so that you can get a good answer as quickly as possible.

I will go ahead and close this on GitHub.
