### ISSUE TITLE
prebuilt Entity extraction: Can not convert Object to String.

### ISSUE THREAD

**Issue by anemit** [microsoft/BotFramework-Composer#4488]
I am trying to save as property `user.region` a continent or a country found in LUIS prebuilt entity geographyV2. However when the value is about to set to the property message Can not convert Object to String. appears.
![Screenshot_15](https://user-images.githubusercontent.com/48094685/96941424-0dfcd980-14db-11eb-9924-438158cc1783.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/48094685/96941426-0f2e0680-14db-11eb-9a86-39dc535340f0.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/48094685/96941429-0fc69d00-14db-11eb-84d6-2ff1acb7b84b.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/48094685/96941430-105f3380-14db-11eb-8c6f-24fbc9d89f0d.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/48094685/96941431-10f7ca00-14db-11eb-8231-509fb74db04b.jpg)

**Comment by dmvtech** [comment]
Reproduced. Investigating.

**Comment by dmvtech** [comment]
So, `location` is the property that you're after (from the whole result object). Alter your value (where you are using the coalesce statement, so that it looks like this:
`=coalesce(@geographyV2,@RegionExtractor.location)`

Reviewing in Emulator can help you determine this as you can see the whole response and know which properties to use:
![image](https://user-images.githubusercontent.com/43397658/97065071-bd7b8f80-155f-11eb-8a49-0c498821ebb1.png)

**Comment by anemit** [comment]
Thank you!
