### ISSUE TITLE
Name conflict Error when publishing to an existing publish profile

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#4627]
## Describe the bug

When I try to deploy my bot to an existing publish profile, if I had already deployed the same lu file before, I will get the following name conflict error.
![image](https://user-images.githubusercontent.com/32191031/97949607-202a2200-1dcf-11eb-9d95-2504139f31fc.png)

The name field is used to identify the abs and luis resource,  so I can't fix this by just update the name, I need to go to luis portal to find and delete the existing app. 

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by tonyanziano** [comment]
@zidaneymar can you please take a look at this?

**Comment by feich-ms** [comment]
There is a ticket here https://github.com/microsoft/botframework-cli/issues/1044 tracking the name conflict issue in bf luis build, but it's in R12 plan. After the issue fixed in bf-lu side and composer consume the new bf-lu package, this error will go away since luis application names with only case differences will be recognized as same app so it will update the existing app instead creating a new one that already exists. Will keep posted.

**Comment by feich-ms** [comment]
Closed this issue since luis build has been fixed https://github.com/microsoft/botframework-cli/pull/1045.
