### ISSUE TITLE
Unable to rename any publishing profiles other than the first one

### ISSUE THREAD

**Issue by dmvtech** [microsoft/BotFramework-Composer#4657]
## Describe the bug

After creating more than one publishing profile for a bot, only the first one can be renamed.

## Version
1.1.1.

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a simple bot in composer
2. Create a publishing profile
3. Create a second (or more) publishing profiles
4. Attempt to rename second or subsequent profiles; unable to rename
5. Attempting to rename first publishing profile works still.

## Expected behavior

Any publishing profile should be able to be renamed.

## Screenshots

![image](https://user-images.githubusercontent.com/43397658/98054087-ef59e500-1dee-11eb-81b4-8eab7fbb807e.png)

**Comment by VanyLaw** [comment]
Hi @dmvtech,  I can not reproduct that the first profile can be edit. In my site, all profiles's name can not be edit. and that situation was by design, because we use name as key to save all the publish history and status in server. If user rename during publishing, the history and status will be mess up.

**Comment by boydc2014** [comment]
I also can't repro this, so taking down the rc and p0 label for now, until we hear from customer.
