### ISSUE TITLE
How to add Content Middleware to a Composer bot?

### ISSUE THREAD

**Issue by neetgupta7** [microsoft/BotFramework-Composer#4727]

**Comment by dmvtech** [comment]
Hello @neetgupta7 

The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/blob/master/README.md) repos are the preferred platform for submitting **bug fixes** and **feature requests**.

The only middleware supported in Composer OOB is the _typing_ and _inspection_ middleware. You can enable these by setting these values to true in the settings:

```
    "UseShowTypingMiddleware": true,
    "UseInspectionMiddleware": true,
```


Otherwise, you will want to [use a custom runtime](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#export-runtime) and modify the code to use middleware.
