### ISSUE TITLE
QnA Maker follow-up prompts do not work in test WebChat CDN bot using the Composer

### ISSUE THREAD

**Issue by ismendes** [microsoft/BotFramework-Composer#4773]
## Describe the bug
I have a bot using the Bot Framework Composer, and we have 800+ FAQs. You can check an example here:
https://partner.microsoft.com/en-us/Search#/?search=action%20pack
Follow up prompts appear in the Test pane within QnA Maker​
 
![image](https://user-images.githubusercontent.com/56369624/98871157-50a23980-2429-11eb-8480-29cbc1f28a3f.png)

However, it doesn't show in the bot:
![image](https://user-images.githubusercontent.com/56369624/98871216-69125400-2429-11eb-83d4-c6c4c82b8e54.png)

## Browser

- [ ] Electron distribution
- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

## OS

- [x] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to https://partner.microsoft.com/en-us/Search#/?search=action%20pack
2. Type in the bot "convert trial to paid"
3. See answer. It doesn't show the follow up prompts

## Expected behavior
The expected behavior is to see the follow-up prompts as we see in QnA maker.

**Comment by luhan2017** [comment]
@ismendes , did you check the Enable Multi-turn extraction when you extracted the qna pairs in composer?
And what composer version are you using? We had a bug on the multi-turn extraction feature, and it should be fixed in the latest main branch.

**Comment by BeheraMadan** [comment]
Hi,
Yes, we have enabled multiturn extraction in the QNA knowledge base setting. Currently we are using composer version 1.0.2.
Today we updated to latest version 1.2.0. Even after updating the composer to latest version, followon prompt is not getting displayed to QNA answers. We are using QnaMaker generate answer api to fetch qna answers and we are using following settings in the body section of the qna maker api. 

{
  "question": "QNA question",
  "top": 1
}

Is there any modification required so that api response will display followon prompt qna answer? 

Thanks,
Madan

**Comment by ismendes** [comment]
@luhan2017, please, check Madan's answer, he's a software engineer from my team. Thanks!

**Comment by luhan2017** [comment]
Did you use the QnARecognizer to query qna or a normal qnadialog? 

We only support multi-turn for the QnARecognizer, could you share some screenshot on how do you extrac qna pairs in composer, are the multi turn informations extracted successfully? Then I can identify if it is an extraction issue or a runtime issue. 

![image](https://user-images.githubusercontent.com/32191031/99348001-7325ce00-28d3-11eb-9baa-3bdbd043d519.png)

**Comment by BeheraMadan** [comment]
Hi,

We are using neither QnARecognizer nor a normal qnadialog to query qna. We are using "qna maker generate answer API" call for qna questions(to fulfill one of the requirement). 

We have created qnamaker knowledgebase separately on qnamaker.ai portal and not using the composer.

Thanks..

**Comment by ismendes** [comment]
@BeheraMadan, can you also please give background of the requirement we had that led us to decide for the route of using the API call feature and not the QnA trigger?

**Comment by BeheraMadan** [comment]
Hi,

we wanted to store telemetry parameters such as user asked questions, question found or not in knowledge base, corresponding matched question in knowledge base, confidence score etc which was not possible with qnamaker dialog because qnamaker trace for qnamaker dialog is not available as shown in below screenshot.  Also these telementry parameters we wanted to store in the qnamaker answer message itself with the help of image url parameters.

![image](https://user-images.githubusercontent.com/70739031/99762755-377f4400-2b1f-11eb-99b9-dbf150d73b3b.png)

So we use api call.

**Comment by ismendes** [comment]
Makes sense. We need to verify if the trace from QnA maker is now available if using the QnA trigger, and refactor if so.

**Comment by BeheraMadan** [comment]
Hi,
The scenario is like below.

When ever there is a qna question asked by the user , we want to store corresponding telemetry data such as QnA_ArticleFound or not in the knowledge base, QnA_UserOriginalQuestion, QnA_MatchedQuestion, QnA_Score, ConversationId etc so that this data can be used by data team for analysis purpose.

If we use qnamaker dialog in composer, there is no qnamaker trace available to capture above mentioned data . Please find below screenshot for reference

![image](https://user-images.githubusercontent.com/70739031/99789720-087dc800-2b49-11eb-83a6-43593ace0fcd.png)

![image](https://user-images.githubusercontent.com/70739031/99792387-0ae22100-2b4d-11eb-91a8-64183e1687de.png)

Now if we use generate answer api to query qnamaker  we can trace the api response and capture all the data mentioned above. Please find below screenshot for the reference.

![image](https://user-images.githubusercontent.com/70739031/99790528-462f2080-2b4a-11eb-9241-a8f5136f1c98.png)

![image](https://user-images.githubusercontent.com/70739031/99791196-4c71cc80-2b4b-11eb-9327-eb5c5fd3b81f.png)

this is the reason we decided to use api call so that we can trace qna maker response and capture and store  the above mentioned telemetry data.

But if we use api call, qna answer is not displaying followup prompt which is getting displayed if we use qnamaker dialog.
Based  on this there can be these scenarios as mentioned below.
1. If qnamaker trace is available it will resolve our problem.
2. If we use api call how can we modify api call request so that qna answer will display followup prompt as well in the chat window.

**Comment by BeheraMadan** [comment]
Hi,

Please find below some more screenshots for the reference 

Below are the screenshots when we use qnamaker dialog 

![image](https://user-images.githubusercontent.com/70739031/99793823-382fce80-2b4f-11eb-9452-12c946a4a25f.png)


![image](https://user-images.githubusercontent.com/70739031/99793918-5dbcd800-2b4f-11eb-81e2-4ca702e6bfbf.png)


Below are the screenshots when we use api call to query qnamaker.

![image](https://user-images.githubusercontent.com/70739031/99794109-b42a1680-2b4f-11eb-8603-6b6b4e097705.png)



![image](https://user-images.githubusercontent.com/70739031/99794674-8d201480-2b50-11eb-8bcd-ebade36947db.png)


![image](https://user-images.githubusercontent.com/70739031/99794818-c062a380-2b50-11eb-939a-1f4a788a7b59.png)

**Comment by luhan2017** [comment]
@BeheraMadan ， if you just want to see the qna trace, you can configure you qna service in the emulator.
1. Create a new bot configuration, enter the Endpoint Url, and connect to the bot.
![image](https://user-images.githubusercontent.com/32191031/99926568-22075580-2d7d-11eb-8d4c-a25b83d0e28a.png)

2. Add a QnAMaker service under Services tab
![image](https://user-images.githubusercontent.com/32191031/99926595-3b100680-2d7d-11eb-9c94-f43c736cc5fb.png)

3. Choose connect to a knowledge base manually and fill in your qna maker configurations
![image](https://user-images.githubusercontent.com/32191031/99926658-64c92d80-2d7d-11eb-8ebb-2ca2a441ba76.png)
![image](https://user-images.githubusercontent.com/32191031/99926667-6b57a500-2d7d-11eb-957d-eaae59192826.png)

4. Then you can see the QnAMaker Trace，you can even edit, train and publish it. 
![image](https://user-images.githubusercontent.com/32191031/99926698-7ca0b180-2d7d-11eb-827a-9d47ef692e6d.png)

If you want to continue to use the API, you should follow this to show the multi-turn prompts:

You should check if you qnaResponse.context.prompts has value, if yes, add it to the response. Please just follow the detailed actions in QnA Intent Recognized trigger. I didn't see that part in your screenshot. 

![image](https://user-images.githubusercontent.com/32191031/99926764-bc679900-2d7d-11eb-9016-10ff903596a9.png)

**Comment by luhan2017** [comment]
@BeheraMadan did this answer your question? any update on this?

**Comment by BeheraMadan** [comment]
We are using qnamaker dialog action instead of qnamaker api call.

![image](https://user-images.githubusercontent.com/70739031/101349076-bfe93d00-38b2-11eb-9b35-10aa6d537a43.png)


![image](https://user-images.githubusercontent.com/70739031/101349016-a21bd800-38b2-11eb-9b59-8b58d7cd6e79.png)

Followup prompt is working  for this qnamaker dialog action.

**Comment by luhan2017** [comment]
Close this issue, please let me know if you still need help here. @BeheraMadan
