### ISSUE TITLE
Sending File type attachment to user through Composer

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#4815]
I'm unable to send File type (.pdf, .csv,.txt,etc..) attachments to user From Composer

**Comment by cwhitten** [comment]
@KoradaRajesh I assume you are using the File/Attachment prompt. 

@luhan2017 can you verify this is an issue with the component before we transfer to the SDK as a bug?

**Comment by KoradaRajesh** [comment]
@cwhitten File/Attachment prompt we are using for to handle the user send attachment with validation of attachment only but I haven't seen any option to sent file attachments(.pdf,.txt etc) to user

**Comment by johnataylor** [comment]
@luhan2017 any update on this?

**Comment by luhan2017** [comment]
@boydc2014 , do we support send attatchment to user through LG/AdaptiveCard?

**Comment by boydc2014** [comment]
@luhan2017  LG supports all the SDK types, so i think attachmentInput should be also supported. @Danieladu can you try the coding approach first, and then Composer.

**Comment by Danieladu** [comment]
@KoradaRajesh I'm sorry to say that Declarative Bot can not send the binary attachment to the user currently.
Here are some workarounds that you could take a look.
- Upload the binary file to somewhere that could be fetched from the internet. For example, the url of the resource is: `xxx.png`
Then in LG file, you could use the below template to render the activity:
```
# attachmentTemplate
[Attachment
    name = myImage
    contenttype = image/png
    contentUrl = xxx.png
]
```
Then in the `SendActivity` action, just apply:
```
{
        "$kind": "Microsoft.SendActivity",
       "activity": "${attachmentTemplate()}"
}
```

- The second solution is more complex.
You could get the base64 format of the binary file and then send it to user with LG template.
For example, you can use such C# code to get the base64 format content of the file:
```
var imageBase64 = Convert.ToBase64String(File.ReadAllBytes(imagePath));
```

Then in the LG file,  change the template content with
```
# attachmentTemplate
[Attachment
    name = myImage
    contentType = image/png
    content = data:image/png;base64,${imageBase64}
]
```

In addition, we may consider supporting the reading of binary files in LG. For example, add a function that called `fromFileWithBinary`, so that the template could be optimized as below without additional code involved.
```
# attachmentTemplate
[Attachment
    name = myImage
    contentType = image/png
    content = data:image/png;base64,${base64(fromFileWithBinary(1.png))}
]
```

**Comment by KoradaRajesh** [comment]
How can I send it in composer

![image](https://user-images.githubusercontent.com/51915291/99495942-771c2380-2999-11eb-8b96-7676e8fe487e.png)

**Comment by Danieladu** [comment]
> How can I send it in composer

This is action data, you just need to add a "SendActivity" Action and fill in "${attachmentTemplate()}" in the activity property.
At the same time, in LG file, add such template:
```
# attachmentTemplate
[Attachment
    name = myImage
    contenttype = image/png
    contentUrl =https://xxx.png
]
```
Make sure that you have uploaded the image to the URL.

**Comment by KoradaRajesh** [comment]
I'm using this

# attachmentTemplate
[Attachment
    name = pdf
    contenttype = application/pdf
    contentUrl = https://storageaccountbcv4ib7d4.blob.core.windows.net/qna-images/DesktopTroub.pdf?sp=r&st=2020-11-11T12:34:10Z&se=2023-11-11T20:34:10Z&spr=https&sv=2019-12-12&sr=b&sig=5jLjG%2ByYAkFFwars693Y1Slp8%2BbKjnvdb1qbv0JGE7I%3D
]


it's displaying like

![image](https://user-images.githubusercontent.com/51915291/99498683-dda34080-299d-11eb-9ca4-ea119222cfde.png)

Once I click on the download it's opening in browser not download directly

**Comment by Danieladu** [comment]
@KoradaRajesh Maybe the Emulator/webchat does not support download the file directly.

**Comment by boydc2014** [comment]
> @KoradaRajesh Maybe the Emulator/webchat does not support download the file directly.

Do we know any other channels support this?

**Comment by taicchoumsft** [comment]
@dmvtech, do you think you could help the customer with this issue?

**Comment by dmvtech** [comment]
Hi @KoradaRajesh; @Danieladu is correct. Emulator does/will not handle _file_ downloads. Since this is a "file" type attachment and not something that gets rendered into chat (like say an _image_), it is just sent across as http(s) link. Due to that, Emulator is going to hand-off the handling of that to the (operating) system to let it proceed with that however it needs. Since it's an https link, the _browser_ is of course the appropriate client and the browser then just renders that pdf in the browser as that is how it is configured to handle those content types.

You can change that setting in your browser if you wish. For the new Edge browser it is:
![image](https://user-images.githubusercontent.com/43397658/102269192-254fb600-3ed1-11eb-8fc9-5a401e4eeb4c.png)

Additionally; if you are in a client like WebChat, you can click on the attachment name and select "Save link as..." as another workaround.

Bottom line is that this is not a composer issue, and not really a Emulator or WebChat issue. All channels are going to handle these types of attachments slightly different.  I guess I could see where this _might_ be a feature request for Emulator. So that it would be able give you a way to save your attachments to a specified location. But that seems like a very edge case/need. Emulator is just a way to test and develop your bot. Not for customer/user use. Again; you're back to the fact that every channel will handle these types of attachments differently. But of course feel free to [create a feature request](https://github.com/microsoft/BotFramework-Emulator/issues/new?assignees=&labels=Enhancement&template=feature-request.md&title=) for Emulator if you desire.
