### ISSUE TITLE
The given key 'ja' was not present in the dictionary.

### ISSUE THREAD

**Issue by okajun35** [microsoft/BotFramework-Composer#4817]
## Describe the bug
I want to run it on a browser that is written in Japanese.
I'm getting an error with Chrome and firefox.
The error message is "The given key 'ja' was not present in the dictionary."

## Version
1.2.0

## Browser
- [〇 ] Chrome
- [〇] Firefox

Bot Framework Emurator causes an error when I change Locale "ja".
No error in  safari. 

## To Reproduce

1. add "ask a question"
2. Click on 'restart bot'
3. Use Bot Framework Emurator 
4. locale setting "ja" 

## Expected behavior

The question appears.
Choices are displayed in Japanese.

## Screenshots

![image](https://user-images.githubusercontent.com/14844237/99179108-ae05f580-275d-11eb-8f6f-3c5640fea34a.png)

locale setting "ja-jp" 
![image](https://user-images.githubusercontent.com/14844237/99179144-f0c7cd80-275d-11eb-923b-30be5790d603.png)

locale setting "ja" 
![image](https://user-images.githubusercontent.com/14844237/99179127-cd9d1e00-275d-11eb-8fde-4dc3f18d9727.png)

Thank you

**Comment by v-kydela** [comment]
Thank you for the report, @okajun35 

I'm a little confused because you say you're getting an error with Chrome and Firefox which might imply that you're using a browser-based chat client like Web Chat, but then you say you're using Emulator. Your mention of Chrome and Firefox could imply that you're using Composer in a browser, but your screenshot looks like you're using the desktop app.

1. Are you using Composer in a browser or are you using the Electron distribution?
1. What do Chrome and Firefox have to do with the error you're seeing in Emulator?

**Comment by okajun35** [comment]
Thank you @v-kydela 

I have tried with a browser and an emulator.
I didn't explain it well enough. sorry.

I'll post a screenshot of the web chat results in mac and windows 
browsers

Browser screenshot results：

Edge (os:windows)
![winddows_edge](https://user-images.githubusercontent.com/14844237/99323636-f801ef00-28b5-11eb-81a9-e1cfb8ae0a33.jpg)

Chrome(os:windows)
![winddows_chrome](https://user-images.githubusercontent.com/14844237/99323647-fafcdf80-28b5-11eb-9472-1e868e11f09f.jpg)

Firefox(os:windows)
![windows_firefox](https://user-images.githubusercontent.com/14844237/99323651-fdf7d000-28b5-11eb-8ab5-d718a544b317.jpg)


Chrome(os:mac)
![mac_chrome](https://user-images.githubusercontent.com/14844237/99323580-ddc81100-28b5-11eb-8949-d4bf8f3f1b23.jpg)

Firefox(os:mac)
![mac_firefox](https://user-images.githubusercontent.com/14844237/99323594-e587b580-28b5-11eb-87a9-3ecca96e909b.jpg)

Safari(os:mac)
![mac_safari](https://user-images.githubusercontent.com/14844237/99323626-f1737780-28b5-11eb-99ea-11c5622074e7.jpg)

**Comment by v-kydela** [comment]
Thank you for the screenshots, @okajun. I have reproduced the issue. The problem is that MapToNearestLanguage is only used for prompt dialogs and not input dialogs, and Composer uses adaptive dialogs and therefore it uses input dialogs. The .NET SDK needs to be updated so that input dialogs match the behavior of prompt dialogs.

A similar issue was reported here: https://github.com/microsoft/BotFramework-Composer/issues/4094

This is related to an old issue in the JS SDK: https://github.com/microsoft/botbuilder-js/issues/2475

It was fixed here: https://github.com/microsoft/botbuilder-js/pull/2534

The fix needs to be ported to the other languages, since Composer uses C#. I've made a new issue for that here: https://github.com/microsoft/botbuilder-dotnet/issues/4981

I will close this here so it can be addressed in the .NET repo.
