### ISSUE TITLE
Bot is not working properly after updating to latest composer version

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#4850]
Hi,

Earlier we are using bot composer version 1.0.2 and bot was working  fine in local emulator &  on Azure portal as well(after deployment). Yesterday we migrated to new composer version 1.2.1. After migrating we tested the bot in emulator and it is working fine locally but after deploying to Azure it is not working properly and giving below error,

"Exception has been thrown by the target of an invocation."

Could you please guide us on above issue.

Thanks,
Madan

**Comment by dmvtech** [comment]
Hi @BeheraMadan 

Is that exception being thrown in the chat itself? What channel? Did you deploy from within Composer or another method? When you did the new deployment, what all did you deploy? Just declarative resources or did you deploy the runtime as well?

**Comment by BeheraMadan** [comment]
Hi,

Yes exception is being thrown in the chat window itself. Its web browser channel. Bot is deployed using CI/CD pipelines and not from within composer. We deployed the whole bot solution along with runtime. Earlier too we were deploying whole bot solution and runtime as well.

Thanks,
Madan

**Comment by luhan2017** [comment]
@BeheraMadan, we had some bot structure change during this release, could you share more details about your CI/CD pipeline , does it cover the crosstrain+lubuild+qnabuild processes?

**Comment by BeheraMadan** [comment]
Hi,
We have updated app service  configuration settings on Azure portal  as per new bot structure appsetting.json file.
So now bot is working fine on azure portal as well after the deployment.

Thanks

**Comment by BeheraMadan** [comment]
Hi,

But while implementing the new logic in our updated bot solution(latest composer version) we found another issue. We are
trying to a new multiple input choice action with some choices for selection. But when we run the bot and click on any of the choice bot is giving error "Sequence contains no elements"

![image](https://user-images.githubusercontent.com/70739031/99515375-e2262400-29b2-11eb-8f3b-5700ce7d0e99.png)


![image](https://user-images.githubusercontent.com/70739031/99515614-30d3be00-29b3-11eb-9446-6bf3b5d3e6a0.png)

Thanks..

**Comment by dmvtech** [comment]
Hi @BeheraMadan 

> We have updated app service configuration settings on Azure portal as per new bot structure appsetting.json file.
So now bot is working fine on azure portal as well after the deployment.

Thank you for following up and sharing the resolution. 

> But while implementing the new logic in our updated bot solution(latest composer version) we found another issue. We are
trying to a new multiple input choice action with some choices for selection. But when we run the bot and click on any of the choice bot is giving error "Sequence contains no elements"

You should avoid using $ in your variable names as that is used for evaluation, etc. Additionally, you should be setting these in a [memory scope](https://docs.microsoft.com/en-us/composer/concept-memory). Typically either in dialog or user.

So, to resolve the above, you should change `$optionselected` to `user.optionselected` (or something similar) in both the user input choice and the switch actions. Please try that and test. If it does not work, please open another issue. Since the issue specified here is resolved, I will close this one.
