### ISSUE TITLE
knowledgebaseid must be supplied manually

### ISSUE THREAD

**Issue by peterbozso** [microsoft/BotFramework-Composer#4873]
## Describe the bug

After starting a QnA Maker-integrated bot in the Composer for the first time, the user needs to manually go to the QnA Maker portal, acquire the created knowledge base's ID, then put it as the value of `knowledgebaseid` property on the Bot Settings page of the Composer.

## Version

1.2.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Using the QnA Sample template, create a QnA Maker-integrated bot. Add an Unknown intent trigger with a QnAMaker dialog action inside it according to [this article](https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot#add-qna-maker-integration).
2. Click Start Bot.
3. Click Test in Emulator.
4. Send a message to the bot. Observe that regardless what message you send, the bot replies with this text instead of an answer from the knowledge base:
   `KnowledgeBaseId`
   It will also send a QnAMaker Trace with this value:
   ```text
   Unable to find a QnA Maker service with Knowledge Base ID c85519cf-adc2-4c9c-9bf6-325e4a97bad6. Please add a QnA Maker service to your bot.
   ```

## Expected behavior

The Composer should fill the `knowledgebaseid` setting after publishing the knowledge base, so the user doesn't have to do it manually. Either that, or the documentation should clearly state that this is mandatory.

**Comment by tdurnford** [comment]
@peterbozso Thank you for the suggestion. We'll add this to our backlog and triage for future releases.

**Comment by luhan2017** [comment]
@peterbozso，I didn't quite understand the scenarios here. We have two QnA sample bots for two different kinds of QnA usage:
- QnAMakerDialog
- QnARecognizer

In QnAMakerDialog, there is no authoring and publishing step in Composer, you create the qna from the portal, and copy the knowledgebaseid, endpoint and key into the settings to make it work. In this case, you need to fill in all the settings by your own.
In QnARecognizer, you author your qna pair in composer and input subscriptionkey and publish qna within composer. In this case, you just need to input a key.

Which one do you refer to?

**Comment by managedcoder** [comment]
@luhan2017,  I have also hit this issue so I think what @peterbozso is getting at is that no matter how you try to create a QnA Maker KB in Composer it gets you deceptively close to working but still needs the developer to visit the QnA Maker portal to fetch the last few configuration items that Composer did not set for the QnA logic in the bot to work.  

So, for example, if you choose the "QnA Maker Sample" template or the "QnA and LUIS" template and then go to QnA blade in Composer and "add a new knowledgebase (does not matter if you create from a URL or if you "create from scratch") and add at least 1 Q&A pair and provide your QnA Maker subscription key, you will be able to Restart the bot and the KB will be created and you will think every is fine but the Composer QnA configuration won't be complete since Composer does not set the full set of required config which you can only see if you switch to Advanced view. If you try to run the bot at this point it will run but won't be able to access the QnA Maker so and the bot won't return any answers.

So the solution that would fix this issue is simple... when composer creates the QnA Maker KB, have it grab the requisite config settings for "qna" section and set the following Composer configuration so the developer does not have to do this manually:    

"qna": {
    "knowledgebaseid": "",
    "hostname": "",
    "qnaRegion": "",
    "endpointKey": "",
    "subscriptionKey": ""
  },

Oddly enough, the qnaRegion and endpointKey settings do get set by Composer but not knowledgebaseid and hostname and without knowledgebaseid you can't access a QnA Maker KB.

-Russ

**Comment by hibrenda** [comment]
@managedcoder thanks for the feedback. I'd like to understand more for your scenarios. 

Scenario A :You create bot from scratch or URL and author the QnA pairs in composer. And then you input the QnA subscriptionkey which created in Azure portal. And then  you can add "QnA intent recognized" trigger to get the answer and no need to call QnA action to retrieve the answer . please reference https://docs.microsoft.com/en-us/composer/how-to-define-triggers#qna-intent-recognized for more detail.

So for QnA samples, if you have already add following trigger, it should work. 
![image](https://user-images.githubusercontent.com/43408889/104429017-1cc9c880-55c0-11eb-9eb8-8b219d8b5354.png)

you don't need to define the "knowledgebaseid" which only used in following action.
![image](https://user-images.githubusercontent.com/43408889/104429237-5bf81980-55c0-11eb-82a7-b88cc9d92196.png)

Scenario B: If you are using luis+qna sample, the whole process will be different. you need to go to QnA portal to publish your QnA content and then follow https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot step to retrieve the answer.

So which scenario you are looking for ?

**Comment by cwhitten** [comment]
It seems like managed QnA authoring and the QnA Action are being conflated with each other. When using the QnA Action the knowledgebase id is required.

**Comment by peterbozso** [comment]
Thanks @luhan2017 and @cwhitten for the explanation! Now (after also carefully re-reading the docs) I see the situation clearly.
