### ISSUE TITLE
Allow Project tree to be expanded

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#4952]
## Describe the bug

<img width="435" alt="Screen Shot 2020-11-23 at 4 23 58 PM" src="https://user-images.githubusercontent.com/13004779/100030436-5c3a1c80-2da8-11eb-8ba7-bb35fa68bc50.png">

The Project tree pane cannot be expanded or contracted. The sizing has disappeared on the pane

**Comment by zhixzhan** [comment]
After some dig, there seems a mask from VisualEditor.ZoomZone has covered splitter's drag, will sync with @alanlong9278 .

**Comment by zhixzhan** [comment]
if do not use `MarqueeSelection` component, won't meet this bug. ( but not sure it's the root cause )
https://github.com/microsoft/BotFramework-Composer/blob/ac57d72d437dd781e4c6a0d32b0b3cae950c6227/Composer/packages/adaptive-flow/src/adaptive-flow-editor/AdaptiveFlowEditor.tsx#L156

the splitter between visual editor / form editor was broken after #4743

the splitter between project tree / visual editor was broken after https://github.com/microsoft/BotFramework-Composer/commit/800a4dfc06ecdca86526fe07ab4bdb017119850c

**Comment by boydc2014** [comment]
> if do not use `MarqueeSelection` component, won't meet this bug. ( but not sure it's the root cause )
> https://github.com/microsoft/BotFramework-Composer/blob/ac57d72d437dd781e4c6a0d32b0b3cae950c6227/Composer/packages/adaptive-flow/src/adaptive-flow-editor/AdaptiveFlowEditor.tsx#L156
> 
> the splitter between visual editor / form editor was broken after #4743
> 
> the splitter between project tree / visual editor was broken after [800a4df](https://github.com/microsoft/BotFramework-Composer/commit/800a4dfc06ecdca86526fe07ab4bdb017119850c)

@alanlong9278 @yeze322 can you comment on this?
