### ISSUE TITLE
Ability to use LG in Properties

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#4958]
We use the common.lg file as a dictionary for all the language of the bot. These responses are typically used as bot messages to the user. 

However for some features like the bot sending out a reminder mail for you, or sending a message on behalf of a user via an external Api we need to have the ability to use the entries from this dictionary into properties, so we can use them to set mail subject, body, etc, etc.

Now they need to be hardcoded into the flow, or set in the appsettings.json, whilst we just want to sent out one file to the business to translate.

![image](https://user-images.githubusercontent.com/49873947/100085096-ea1b1380-2e4b-11eb-88f7-4ac81614ce23.png)

![image](https://user-images.githubusercontent.com/49873947/100085142-f8692f80-2e4b-11eb-89e9-1dea569f9fd5.png)

**Comment by cwhitten** [comment]
@cxbuilders if you set the value to an Expression, does it work?

**Comment by boydc2014** [comment]
> @cxbuilders if you set the value to an Expression, does it work?

This won't work, because it will need namespace + exports. 

So, @cxbuilders the current way to enable LG outside of SendActivity is using namespace + exports. Please refer to https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lg-file-format?view=azure-bot-service-4.0#exports-option and exports the template you want and try that in the properties or in any other actions. 

We are planning to make it easier in the next SDK release by binding LG natively in more actions, which potentially you don't need this extra steps to exporting your template.

**Comment by hibrenda** [comment]
@cxbuilders 
Just like @boydc2014 mentioned here. you can try out as below : 

Use template outside of SendActivity
![image](https://user-images.githubusercontent.com/43408889/100175235-f618db00-2f08-11eb-878f-2d10b6874eb4.png)

Define the template in .LG file
![image](https://user-images.githubusercontent.com/43408889/100175299-0df05f00-2f09-11eb-9a9d-305b8ea1e231.png)

Does this meet your requirement ?

**Comment by cxbuilders** [comment]
@boydc2014 @hibrenda , that worked perfect. I was also able to use this for #4960
