### ISSUE TITLE
How can we use ActivityTypes.Typing

### ISSUE THREAD

**Issue by tannguyen3** [microsoft/BotFramework-Composer#4966]
Hi guys,
I have a MS Team bot, and I'd like to greet user when they start using the bot again. 
The "Greeting - ConversationUpdate" activity, only triggered the first time user added to the bot. 
So I plan to use the typing activity, but it doesn't work on Bot Emulator and Teams

Do we have any document for how-to use ActivityTypes.Typing or if someone has experience with it?

Thanks

**Comment by dmvtech** [comment]
Hi @tannguyen3 

> The "Greeting - ConversationUpdate" activity, only triggered the first time user added to the bot.
> So I plan to use the typing activity, but it doesn't work on Bot Emulator and Teams
> 
> Do we have any document for how-to use ActivityTypes.Typing or if someone has experience with it?

The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/blob/master/README.md) repos are the preferred platform for submitting **bug fixes** and **feature requests**.


---------------------------------------------------------------------------------

You can send a typing activity by using the following LG:
```
[Activity
    Type = typing
]
```

But typically, you enable typing middleware, so that it is done in a more dynamic/automatic way. You enable in the settings:
```
  "feature": {
    "UseShowTypingMiddleware": true,
    "UseInspectionMiddleware": false,
    "RemoveRecipientMention": false
  }
```

When using middleware, the runtime is what is configured to determine the length of time to wait before sending the first typing activity (delay, default 500ms) and how often to send typing activities (frequency, default 2000ms). Additionally, each channel+client has it's own implementation on how to render that typing indicator. The typical scenario is that typing only gets sent if a request is taking too long (that assessment uniquely determined by designers/developers), and then disappears once the overwritten by new activity.

If you need to tweak these values you can use your own runtime. You can also simulate your own long-running tasks (in custom runtime, or by using a custom action or a 'Access external Resource->Send an http request' action (to something that takes a long while).


More info:
[Dotnet typing middleware](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/ShowTypingMiddleware.cs)
[Typing activity spec
](https://github.com/Microsoft/botframework-sdk/blob/main/specs/botframework-activity/botframework-activity.md#typing-activity)
