### ISSUE TITLE
How to configure Composer to publish LUIS recognizer in Spanish

### ISSUE THREAD

**Issue by lopejum** [microsoft/BotFramework-Composer#5038]
## Describe the bug
Composer always publishes the LUIS recognizer into LUIS web app with "en-us" culture. So, I can not change the language.

I would like to create a new dialog and use my LUIS recognizer in Spanish, from my Composer framework

## Version

Bot Framework Composer - Desktop

                Version:  1.2.1
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by stevkan** [comment]
@lopejum, can you list the steps you took so I can accurately attempt to reproduce? In the mean time, I’ll look closer at this.

**Comment by lopejum** [comment]
Hi, @stevkan 

1. Launch Composer (both, Desktop version or web composer )
2. Create a simple dialog
3. Use LUIS as recognizer
4. Fill-in with my LUIS auth-token when it prompts (my LUIS auth is located in Westeurope). I will use the "es-es" culture
5. Everytime I exec "Start Bot", when it updates the intents in LUIS web app, it appears with "en-us" always.

So, can I execute my Spanish bot from Composer and get the LUIS intents (and entities) in "es-es" culture?

Thanks

**Comment by lopejum** [comment]
Dear support team,

After several days, I don't have any response about my issue...

So, is there any way to use Bot Composer with other languages (Spanish, German, French...) rather than default English and publish to LUIS app with these "culture languages"?

Thanks!

**Comment by dmvtech** [comment]
Hi @lopejum I'm looking into this and should have some sort of update for you today.

**Comment by dmvtech** [comment]
Hi @lopejum 

To clarify; are you configuring Composer to use other languages than just English, or are you wanting to use Composer with English language, but use the Spanish local/resource for LUIS?

I was able to reproduce your issue somewhat by doing the following:

1. Launch Composer (both, Desktop version or web composer ) [Only using en-us local/language]
2. Create a simple dialog
3. Use LUIS as recognizer
4. Fill-in with my LUIS auth-token when it prompts (my LUIS auth is located in Westeurope). I will use the "de-de" culture
5. Starting the bot publishes the en-us culture as same as you. No de-de.

Then I changed the settings to explicitly be:
```
  "luis": {
    "name": "GermanLUIS",
    "authoringKey": "<redacted>",
    "authoringEndpoint": "",
    "endpointKey": "",
    "endpoint": "",
    "authoringRegion": "westeurope",
    "defaultLanguage": "de-de",
    "environment": "composer"
  },
```

And at the point it would still only publish to `en-us`, same as you see.

Then I added the German language to Composer and set as default. 
```
  "defaultLanguage": "de-de",
  "languages": [
    "en-us",
    "de-de"
  ],
```

At that point I hit some other errors, due to (I think) how I made these changes. 

I started with a new bot and did the following:

1. Created new bot
2. Added German language, set as default. also selected "When done, switch to the newly created language and start the (manual) translation process"
3. Set LUIS settings for my key and region (westeurope)
4. Created my trigger and dialogs, added German utterances (under German language)
5. Then tested, and I can finally see (both) locales:

![image](https://user-images.githubusercontent.com/43397658/101539757-e3b08f80-3953-11eb-8982-02848039895d.png)


So, to clarify; is **your bot** _only_ going to be in Spanish or English? Or is it going to be [multilingual](https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language), and you only want to utilize the Spanish LUIS functionality and have it publish to the correct locale.

**Comment by lopejum** [comment]
Hello,
 
Maybe the issue comes when I select this option (just "Spanish"):
![image](https://user-images.githubusercontent.com/28530984/101545452-9231f000-39a7-11eb-88dd-89ffa2e7b3d4.png)

So, the culture is not well created (only "es"; not "es-es"):
![image](https://user-images.githubusercontent.com/28530984/101547137-1c7b5380-39aa-11eb-9754-6c00c81fb4d1.png)


That way, when a creates some utterances and then I try to publish them to LUIS, I get:
![image](https://user-images.githubusercontent.com/28530984/101547379-6e23de00-39aa-11eb-91ab-d38b284b3a8e.png)



When I select the other option for "Spanish, International": 
![image](https://user-images.githubusercontent.com/28530984/101546171-b17d4d00-39a8-11eb-9d72-c6ca036e0d1d.png)

I can publish with no error to LUIS and, finally, I get:
![image](https://user-images.githubusercontent.com/28530984/101546459-19cc2e80-39a9-11eb-86f2-74a0b0da2f51.png)

So, the confusion (and error) is done by the just "Spanish" selection, which does not produce the correct "culture" es-es. 

Selecting the international Spanish locale and default language, I still got an error:
![image](https://user-images.githubusercontent.com/28530984/101547714-f5715180-39aa-11eb-8d97-0f6531fd5e67.png)

Finally, I need to delete manually the wrong "Spanish", selected previously to avoid this error, and keep International Spanish:


![image](https://user-images.githubusercontent.com/28530984/101547912-513bda80-39ab-11eb-9ff3-83f21c00b7fd.png)

So, please, delete this option that causes error and confusion.

And, yes, I will create a multi-language (from Spanish, to French and English as well). But I needed to have as default Spanish language; then translate it to the other languages.

Thanks a lot for the support.
