### ISSUE TITLE
Orchestrator Recognizer - LU FILE IS EMPTY

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#5126]
On a fresh bot, I switch to the Orchestrator Recognizer and see:

![Screen Shot 2020-12-04 at 12 48 43 PM](https://user-images.githubusercontent.com/1156704/101213336-147c8600-362f-11eb-9b6f-62dd7726e4b8.png)

**Comment by taicchoumsft** [comment]
The workaround is to create a new "Intent Recognized" trigger before switching the dropdown to 'Orchestrator'.

Given how many people brought this up at bugbash, we should consider perhaps leveraging the diagnostics work now to show a warning instead of using a popup to prevent user from submitting an empty LU file.

**Comment by cwhitten** [comment]
Why would an empty LU file be a warning? I'd expect that you can have a recognizer selected with either no .lu or empty .lu's and it shouldn't break.

**Comment by boydc2014** [comment]
> Why would an empty LU file be a warning? I'd expect that you can have a recognizer selected with either no .lu or empty .lu's and it shouldn't break, or warn.

yes, that should not a warning, i was talking to Leilei on Friday this, haven't get time with Tai to confirm why the limitation is there at the beginning. Will do soon.
