### ISSUE TITLE
Windows Installer seems broken

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#5198]
## Describe the bug

The Windows installer fails to complete; the scrollbar terminates early with an unhelpful error message.

## Version

Nightly 191674.827857c

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Download the new nightly BF Composer framework (`BotFramework-Composer-1.2.1-nightly.191674.827857c-windows-setup.exe`)
2. Run the installer
3. See error

## Expected behavior

The installer should complete successfully.

## Screenshots

![image](https://user-images.githubusercontent.com/61990921/101400226-6fa7b600-3885-11eb-9273-57ff73152162.png)

**Comment by taicchoumsft** [comment]
So after discussing with @beyackle, we think this is a bad state on the user machine, unrelated to the vcredist installer change.  What probably happened was that the app folder was deleted manually from an earlier install of Composer instead of using the uninstaller, and this left a very old uninstall key on @beyackle's machine.

When Composer is installed via the installer, it leaves a key in the uninstaller section as a pointer to the uninstaller. On my machine, this uninstall key is here: `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\af30ccea-0e1e-54cd-b22a-e7e279121975`

Per reports [here](https://github.com/electron-userland/electron-builder/issues/4057), when the app program folder is deleted manually (in the default case `%APPDATA%\..\Local\Programs\Bot Framework Composer`) instead of using the uninstaller, the installer will look up this key first to uninstall earlier versions, and because there are no contents, the installer fails.

@beyackle deleted this uninstall key, and he was able to install Composer without issue.

**Comment by cwhitten** [comment]
closed in https://github.com/microsoft/BotFramework-Composer/pull/5240
