### ISSUE TITLE
need property information from teams turn.activity.from

### ISSUE THREAD

**Issue by mganeshphani** [microsoft/BotFramework-Composer#5261]
as per the following issue: https://github.com/microsoft/BotFramework-Composer/issues/4587

i can get username from "turn.activity.from.name" property... i am also looking for email address of the user as well.
i am looking for documentation on what all properties does "turn.activity.from" object hold

**Comment by anusharavindrar** [comment]
@mganeshphani, we do not have any specific documentation for the turn.activity.from object properties, but you can refer to https://github.com/Microsoft/botframework-sdk/blob/main/specs/botframework-activity/botframework-activity.md#from and https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0#activities to get started. Also, you can use the emulator to look at the properties and understand what properties might be available by default.

**Comment by mganeshphani** [comment]
@anusharavindrar  what is the best way to get email address of user interacting from teams?

**Comment by anusharavindrar** [comment]
@mganeshphani, you will not be able to directly get the email address of the user from "turn.activity.from". You will need to export runtime which will generate a copy of your bot's runtime so that you can modify the code and add your custom action. Refer to https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#export-runtime
