### ISSUE TITLE
Published Bot to Azure but not sure where to get the manifest URL https link to publish to PVA

### ISSUE THREAD

**Issue by DS2019** [microsoft/BotFramework-Composer#5350]
## Describe the bug

I followed the directions, here: https://docs.microsoft.com/en-us/composer/how-to-publish-bot#create-azure-resources to publish a bot composer bot to Azure Web App, with success. However, how do I get the manifest URL?

## Version

1.3
## Browser

- [ ] Chrome

## OS

- [ ] Windows

## To Reproduce

Publish a bot to Azure Web App, as in the directions in the article (created azure resources, published bot) Bot is published to Azure with success - verified by testing in web chat in azure. However, I'd like to try for the first time to import this skill bot to PVA, from within PVA. To do this, you need to go to PVA > choose a bot > manage > Skills > add a skill and enter the skill manifest URL (requires a https:// link). When I look at the azure web app I published in app registrations, the home page URL is blank. I can see the uploaded manifest though. If I look at it in resource groups, I do see a messaging endpoint. 
## Expected behavior

Not sure where to get the manifest URL so I can import the skill into PVA. I saw this article: https://www.arafattehsin.com/empower-your-existing-power-virtual-agents-with-bot-framework-skills-%f0%9f%a4%96/ where it is noted that there is a bug and to change the Home Page URL manually by going to the app registration, but I'm not sure what the URL there should be or how to construct it. 

## Additional context

Through this article (https://docs.microsoft.com/en-us/power-virtual-agents/advanced-use-skills),  says you can create and deploy the skill using pro-code tools, but the link sends you to the homepage of bot framework solutions documentation and I didn't find anything there about deploying a skill (new to bot framework).

**Comment by hibrenda** [comment]
@DS2019 The manifest URL : "https://_skillbot-dev_.azurewebsites.net/manifests/_skillbot-manifests.json_" 
![image](https://user-images.githubusercontent.com/43408889/102294659-c3508880-3f84-11eb-9c2e-46c4dd703413.png)

**Comment by Samirun** [comment]
@zxyanliu  we also have same issue  how to get manifest url? or atleast how to construct it?

**Comment by DS2019** [comment]
Yes, agree with Samirun on the manifest - to get a bot published to Azure Web App and try to publish to PVA via the manifest URL, I've needed to go to several documents online (new to Azure and Bot Composer) - and I've not seen yet how to construct the manifest step by step from what you get with the Azure Web App publish.

**Comment by zxyanliu** [comment]
FYI. I am working on the content you guys requested on the docs patch releases.

**Comment by DS2019** [comment]
That is wonderful news, thank you!

**Comment by zxyanliu** [comment]
Apologies for the delay because of the holiday season and we writers have many details to check with our developers before publishing the docs. Will keep you informed on this. Thanks for your patience!  : -)

**Comment by zxyanliu** [comment]
Hi, I tested today and while waiting for the docs to be published, I'd like to answer your question so that you do not get blocked., 

How to get the manifest URL after you publish your skill to Azure?

1. Select the **App Service** resource you just published. 
   ![image](https://user-images.githubusercontent.com/32497439/102567814-26cadb00-4097-11eb-9c37-6f8ce8fd22e1.png)

2. Select **App Service Editor (Preview)** from the menu (under the **Development Tools** section)
   ![image](https://user-images.githubusercontent.com/32497439/102568009-80cba080-4097-11eb-840b-f9addd8b47a5.png)

3. Select **Go->**
   ![image](https://user-images.githubusercontent.com/32497439/102568046-9c36ab80-4097-11eb-90a8-68838d648d62.png)

4. Access your skill manifest in the following directory:
   ![image](https://user-images.githubusercontent.com/32497439/102568156-d011d100-4097-11eb-91d1-e01b1e6afc52.png)

5. Now you will see in the browser, the following URL: 
   `https://composer-skill.scm.azurewebsites.net/dev/wwwroot/wwwroot/manifests/echo-remote-Skill-2-1-preview-1- 
    manifest.json`
   This is not your remote skill URL. Your remote skill manifest URL should be: 
    `https://composer-skill.azurewebsites.net/manifests/echo-remote-Skill-2-1-preview-1-manifest.json`

**Other important details:**
1. Before publishing your skill, it is strongly recommended that you set your skill's `allowedCallers` property to associate it with the caller. Set `allowedCallers` to be "*" to allow all caller. 

2. You must update the `endpoint URL` and `msAppId` of your remote skill manifest after publishing it to Azure. 
   ![image](https://user-images.githubusercontent.com/32497439/102568651-c177e980-4098-11eb-85f5-0a6ea041a52f.png)

**Comment by zxyanliu** [comment]
@DS2019 FYI. I created a FAQ thread for this particular issue you brought up. The docs have just published to docs.microsoft.com 
Please let me know if you are still blocked for anything...
https://docs.microsoft.com/en-us/composer/faq/composer-faq

**Comment by zxyanliu** [comment]
@DS2019 are you still blocked?

**Comment by zxyanliu** [comment]
@DS2019 I am wondering if you are still blocked and if I should close this issue as the doc has been updated. :-)
Please let us know if you still have any questions.

**Comment by Samirun** [comment]
sorry for the late response. we can close this issue

**Comment by zxyanliu** [comment]
Per @Samirun's request in the email: "sorry for the late response. we can close this issue".
I am closing this issue because it has been addressed.
