### ISSUE TITLE
Trigger labels in bot tree, breadcrumbs, and property don't match

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#5383]
## Describe the bug

1.3.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

I noticed this when I generated a form dialog:

![image](https://user-images.githubusercontent.com/39317542/102546303-47ca0680-406c-11eb-930f-cf43a339fee3.png)

![image](https://user-images.githubusercontent.com/39317542/102546497-94154680-406c-11eb-9bb4-415d1e7c4e1e.png)

But also in the LUIS To Do sample:

![image](https://user-images.githubusercontent.com/39317542/102547048-70063500-406d-11eb-90ce-b9c1670bc4bf.png)

## Expected behavior

In general, the name should be the same in the tree, breadcrumbs, and property pane.
For a form dialog, the form dialog should not have "main dialog" in the breadcrumbs because it is not a main dialog.

**Comment by tonyanziano** [comment]
@chrimc62 this looks to be an inconsistency between what the form generation library produces and what composer does natively

**Comment by mewa1024** [comment]
I'm seeing the issue on non-form dialogs as well. Here's a screenshot from the ToDo example (not the H in help):
![image](https://user-images.githubusercontent.com/39317542/103795508-eeb21a80-4ffa-11eb-807c-632ca067a945.png)

**Comment by alanlong9278** [comment]
There are two reasons for the name mismatch
- For dialog name mismatch in left menu & breadcrumbs and form dialog, the reason is that `LeftMenu` use dialog file as name, but the other two use `dialog.designer.name` in dialog file content. So I think we should use `designer.name` in all three models.
![Uploading image.png…]()

- For trigger name mismatch in visual editor & form dialog, the reason is visual editor use 
```
    data.intent ||
    get(data, '$designer.name', conceptLabels()[data.$kind] ? conceptLabels()[data.$kind].title : data.$kind)
```
we can editor `desinger.name` in form editor. But the name will not change in visual editor if the trigger has intent. So I think we should prefer to use `designer.name` in visual editor. 
![Uploading image.png…]()
