### ISSUE TITLE
V1.3.0 Not Compatible with Previous Versions when using a Pipeline

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#5412]
V1.3.0 fails to launch when executed using our Pipeline. Apparently this new version has some changes in the way it is build and deployed. I would like to get some insights in this if possible to make a decision on what to do with this;

- What are the changes in the build / deploy process from V1.2.2?
- Will this be possible for each version upgrade?
- When will Composer come shipped with a native Pipeline?

Before I start diving into the code and see what has changed and updating our Pipelines I would like to have some insight on these points mentioned above. For now we have to skip the upgrade to V1.3.0 because of this. We are simply not allowed (and actually do not want) to create any resources in Azure without a Pipeline, so the Publish method is not an option for us.

**Comment by luhan2017** [comment]
@cxbuilders we updated the luis and qna build process, now the recognizers will be generated at the early stage and will be placed in the recognizer folder, could you check if your pipeline deployed the recognizer folder?

**Comment by boydc2014** [comment]
@cxbuilders As Lu mentioned above the changes in 1.3.0 about build/deploy, is we take the "recognizers" out of generated folder and put those recognizer files into a dedicated "recognizers" folder. 

The intention of this change is to make Composer's process more transparent and more be more friendly to CI/CD pipeline. Without this change, you have to build the bot in Composer. This change will enable user to build the bot out of Composer using CLI tools in there CI/CD environment and be able to achieve the same result. 

I don't foresee changes like this in the next few Composer releases, but to make CI/CD more friendly is definitely the direction we are heading, and if there is more changes necessary to make, we will make sure we communicate that better. 

Can you share more about what your pipeline does and how that's been built? The changes here should be able to make pipeline related easier, not to be disrupting, and open the possibility for a native pipeline.

**Comment by cxbuilders** [comment]
@boydc2014 Thanks for the info I will take a look today  and see if I can update the pipeline to fix it.
The Pipeline we have basically does everything the provisioning and publishing does in Composer. So from within the bot folder you push to the repo and all resources, building and deploying ia executed in the pipeline.

If you're interested I can show you how it's setup and works, let me know.

**Comment by cxbuilders** [comment]
I have fixed the pipeline to be compatible again with 1.3.0. There were quite some differences in the build that I needed to implement.

- Recognizer folder as mentioned (This enabled be to remove quite a big chunck of my PS script dealing with Luis, so that was good).
- Luis properties in appsettings.json was changed to contain an object property per app instead of just a string property per app
- Luresources property was added to the appsettings.json
- The generated folder contained a new json file with Luis settings
- Publish was updated to winx-64

All in all this took quite some time to reverse engineer this from a bot that was published using Composer itself. It is all again nicely working now, but I surely hope I do not have to do this every update. Can this be properly described? As in per version what has changed in the build and publish process?

**Comment by cxbuilders** [comment]
Additionally I saw that the publish process updates the runtime project. Should this be part of the build as well?
![image](https://user-images.githubusercontent.com/49873947/103453320-18a4cd80-4cd9-11eb-8673-4558a867b3b7.png)

**Comment by cwhitten** [comment]
hi @cxbuilders. sorry about the trouble upgrading your pipeline to work with 1.3.0. we're investing on improved capabilities and integrations with CI environments and building out documentation on which stable interfaces or shape can be relied upon in a CI environment as well as providing a lot more functionality made available through the bot framework cli. 

@boydc2014 will follow up with more details--but I'd like to offer early engagement with you as a partner as we test new releases to verify your scenarios, or at least work to provide a set of instructions needed to work with the new model so you aren't reverse engineering anything.  are you interested in this?

**Comment by boydc2014** [comment]
@cxbuilders Sorry for the delay. I can help clarify more context of making composer bot compatible with CI/pipeline. 

In our view, before 1.2.1, a bot is authored by composer is not considered as CI friendly, the criteria was whether user can create a bot in composer, and can **build and run** the bot outside composer. (we didn't list be publish as a goal yet). And we received lots of feedback from users to make sure composer bot is CI friendly. 

Note: build in composer, represent generating the "generated" folder, which is like the bin folder for a c# project. And the changes in generated folder, is not guaranteed to be stable (the other folders and structures are considered to be stable, and if there is a break change in the further, we will explicitly call it out), the additional files you saw there, is we are putting more intermediate results there to help debug easier. 

Under that criteria, the goal is 1.3 is to make sure composer bot friendly, and we identified two blockers
* recognizer folder is previously in the generated folder and generated with some internal logic, so we move it out
* we previously did two intermediate pre-processing of user's raw lu file, called cross-train and down-sampling, the fix for that, is we are also outputing a cross-train json config in the settings folder, and update our cli to make sure the cli can generate the exact same result as composer. 

Here are a document in 1.3 to describe how you'd repeat all internal steps in composer to build a bot, https://github.com/microsoft/BotFramework-Composer/blob/main/docs/archived%20docs/how-to-process-language-models-with-CI-CD.md. User should be able to follow this to build and test a bot in a CI pipeline. 

Moving forward, in the direction of CI friendly, we probably will enable user to publishing a composer bot in CI, and i think we got a few document pieces there, just haven't yet get them together. And for sure, we will be better informing user for any breaking changes. Sorry for the inconvenience, and thanks for your support of composer.

**Comment by cxbuilders** [comment]
@cwhitten Yes that would be great. I see eg some issues raised for adding setting for channels to be added, which are already part of our pipeline, so things like that would all be good to be aligned on, so I can update the pipeline if required.

@boydc2014 Thanks for the info. I think having an overview of the final directory structure within the WebApp would also help with explanation of what is what etc. In the end this is what I used to reverse engineer the Pipeline, by looking at the output of the WebApp created by the Publisher instead of searching through code of the publisher itself.

**Comment by congysu** [comment]
@cwhitten could you please update our customer during an incoming release?  Thanks.

**Comment by cwhitten** [comment]
@cxbuilders We'll close this as we've communicated over email and will include you in any upcoming release to verify your scenarios.
