### ISSUE TITLE
.gitignore not correct

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#5425]
Although there is no native CI/CD for Composer we do have this setup and the .gitignore file seems to be not ok. Currently it has;
![image](https://user-images.githubusercontent.com/49873947/103405059-1108eb80-4b56-11eb-914f-3ebcd0c3aecf.png)

appsettings.json should be part of the repo and for example the generated folder and publish log files could be ignored.

Now I all the time have to update that file, so hopefully this can be fixed

**Comment by cwhitten** [comment]
@cxbuilders this is currently by design so users don't inadvertently check in sensitive information that may be serialized into the file.

I could see this being configurable to an extent, but to simply remove this from .gitignore I worry that users less familiar with the diligence needed to avoid exposing sensitive information will be set up for failure, which is something we avoid, especially when it comes to security concerns.

**Comment by cxbuilders** [comment]
@cwhitten I see just as much potential of having sensitive data in dialogs, like Api keys in Http calls etc. By just ignoring the appsetings.json inexperienced users could push to the repo and remove their local bot, ending up with a repo that contains sensitive data in their dialogs ánd a crippled bot.

It is pretty tricky to spot that the default Composer bot does exclude an integral part of itself to be pushed to a repo. I would argue that it would be much better to warn users somewhere in the settings, or just in the docs. If it really needs to be excluded then exlude everything , since then at least it's clear something needs to happen. I forget this all the time, the only trigger I have is that the Pipeline is failing..
