### ISSUE TITLE
Publishing 1.3.0 to Web App hangs after logging in

### ISSUE THREAD

**Issue by bdezeeuw** [microsoft/BotFramework-Composer#5436]
## Describe the bug

I'm trying to publish as an Azure web app.  I created just a basic echo bot template.  I then started the process to add a new publish profile and select the web app option.  It asked me to login to Azure which I did successfully.  It then hung on the "Configure resources" page.  It says "Loading" with the spinning wheel but nothing ever actually loads.

## Version

1.3.0

## Browser
Not really meaningful for this point since I'm just trying to publish.

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Create a new publish profile 
Give it a name and select the publish to Azure Web App option
Login
It hangs on the next screen trying to load resources

I belong to a lot of different directories so is it possible it's related to that?

## Expected behavior

I expect it to show the create resources UI as documented in the publish documentation:
https://docs.microsoft.com/en-us/composer/how-to-publish-bot

## Screenshots
It's stuck on the below screen:

![image](https://user-images.githubusercontent.com/2798309/103552935-af5cc000-4e7a-11eb-994b-594e991f4dd3.png)

## Additional context

I have previously been using 1.2.1 and was able to use the provision script there to publish bots. I was also able to publish bots to the provisioned resources from Composer for older versions.  I tried opening one of those bots with 1.3.0 and publishing and I receive an error message saying, "Error - Required field `accessToken` is missing from publishing profile.".  The accessToken field is definitely in there, though, in the same place it was in 1.2.1.  I ran an "az account get-access-token" and pasted the new token in to make sure it had a valid one.

That may be a separate issue with 1.2.1 publish profiles not working with 1.3.0, though.  Which isn't as big of a deal right now since I could ideally create a new profile if needed.  The interesting thing, though, is that 1.2.1 bots can be published but it runs into an issue with 1.3.0.  So, my Azure account is setup with everything it needs to publish bots and it just seems to be an issue with the UI retrieving Azure information for some reason.

**Comment by tonyanziano** [comment]
@luhan2017 @benbrown can one of you investigate?

**Comment by luhan2017** [comment]
@bdezeeuw , could you please help provide more information here? Click View->Toggle Developer Tools. and share the Console logs.
![image](https://user-images.githubusercontent.com/32191031/103726271-7572f180-5013-11eb-9d80-0db6ed884efd.png)

**Comment by bdezeeuw** [comment]
Sure!  Here it is:

[ConsoleLog.txt](https://github.com/microsoft/BotFramework-Composer/files/5775899/ConsoleLog.txt)

**Comment by luhan2017** [comment]
@bdezeeuw , thanks for your response, I think we got an error when decoding your token. We still need your help to get more information here.
```
azurePublish:1339 decode token error in  s {message: "Invalid token specified: Cannot read property 'replace' of undefined"}message: "Invalid token specified: Cannot read property 'replace' of undefined"__proto__: InvalidTokenError
```

Could you follow the steps to get your token to debug?

1. Open commnd line tool and Go to the composer exe folder, usually located here: C:\Users\{YourUserName}\AppData\Local\Programs\Bot Framework Composer 
2. run set debug=composer*
3. start Bot Framework Composer from the command line
4. Try to Add a new publish profile and do azure login in Composer Election app.
5. Check the command line tool log, if you can see the token like the following, go to jwt.ms and decode the token, otherwise, please help paste the logs here.
![image](https://user-images.githubusercontent.com/32191031/103847846-07dec800-50dc-11eb-8a4e-ffbba70e2942.png)

Please let me know if the process above is too complicated, we can set up a sync up meeting to go though the steps. 

Thanks, Lu

**Comment by bdezeeuw** [comment]
I grabbed the logs starting from the auth section and attached them in the file below:

[DebugLog.txt](https://github.com/microsoft/BotFramework-Composer/files/5781745/DebugLog.txt)

**Comment by luhan2017** [comment]
@bdezeeuw Thanks for sharing more logs here. This seems relates to an external package which we are depending on, we are contacting them on this issue which may take some time. Is this blocking you currently? Maybe you could downgrade your composer to 1.2 as a work around?

**Comment by bdezeeuw** [comment]
Yes, I'm able to work on v1.2.1 currently.  I'm looking forward to using some of the new features once they figure out the issue.

Thanks for the help, @luhan2017!

**Comment by luhan2017** [comment]
@VanyLaw Let's update the code to make sure we show the correct error message.

**Comment by tonyanziano** [comment]
Hi @bdezeeuw ,

We forwarded your logs over to the authentication team, and were able to help us debug your issue.

In short, the domain that you are trying to log into is not a "federated domain," and so we have to add code on our side to handle that special case and sign you in interactively to acquire a token instead of silently acquiring a token.

**Comment by tonyanziano** [comment]
Note to fixer:

1. Check `accountType` property on received account object after sign-in
2. If `accountType` is non-federated, use `acquireTokenInteractively` instead of `acquireTokenSilently`
  a. I think we might already do this, but we need to look for it in the `catch` block instead of checking the result for `result.error`

**Comment by VanyLaw** [comment]
show the correct error message in https://github.com/microsoft/BotFramework-Composer/pull/6112

**Comment by luhan2017** [comment]
@VanyLaw , The issue is not fixed yet, we should support non-federated account login.

**Comment by cdavilarios** [comment]
Hi everyone! I am having the same issue on Bot Framework Composer. I've tried signing in from a different and work-education account as well and keeps getting me the same issue!
![image](https://user-images.githubusercontent.com/20851408/116647490-4e348d00-a940-11eb-9424-5ba44640d180.png)
