### ISSUE TITLE
Suggestion: Change "Composer Settings" to "Global Settings"

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/BotFramework-Composer#5438]
Hi Team

I am not sure if anyone else has reported this but I think that the name of Composer Settings sounds confusing when we're creating a bot (esp. those who're new to this client). 

I suggest changing this name to **Global Settings**.

![image](https://user-images.githubusercontent.com/16351038/103600791-5feec080-4f5c-11eb-823b-05f1e9450c57.png)

**Comment by tonyanziano** [comment]
@sangwoohaan any thoughts on this?

**Comment by sangwoohaan** [comment]
Global settings would also be confusing since it can read as global configurations that affect all the bots in the bot project. An alternative would be Application settings which sounds more confusing (at least to me). Since this is the first time this naming issue has been brought up, we will collect more data on this.
