### ISSUE TITLE
Home page, MRU list: Remove from list, Reveal in finder

### ISSUE THREAD

**Issue by irwinwilliams** [microsoft/BotFramework-Composer#5526]
It would be good to be able within the composer to remove projects from the list of recent projects.

**Comment by a-b-r-o-w-n** [comment]
@sangwoohaan will you look into this feature request? It should be rather trivial to implement but will need some UX design.

**Comment by sangwoohaan** [comment]
Ok will take a look into this.

**Comment by daveta** [comment]
@sangwoohaan : Any updates?

**Comment by sangwoohaan** [comment]
Sorry @daveta for the delay, @emivers8 @xiyangdesign should be able to support this! Could you guys take a look at this feature request?

**Comment by xiyangdesign** [comment]
will do! @sangwoohaan self-assigned.

**Comment by xiyangdesign** [comment]
proposed solution here: https://www.figma.com/file/pghEVhZEtMsXae9IHybdYo/Composer-Xi-s-workspace?node-id=595%3A1987

@a-b-r-o-w-n  to your comment: 

For clarity, there are two possible approaches for this.
- Remove the project from the recent list
Added in design
- Delete the project from the user's disk
The user can first "reveal the bot in folder", then delete from there.  

Let me know if you have any questions.

**Comment by mewa1024** [comment]
Design solution is to have a contextual menu (vertical dots). The icon (vertical dots) appear when you hover or click on the row. The context menu includes:
- Save as a new project
- Remove from list
- Reveal in explorer

![image](https://user-images.githubusercontent.com/39317542/124211213-98053500-daa1-11eb-8078-83b83302cc49.png)

(Removing "UX design" label since the design is ready.)
