### ISSUE TITLE
Node runtime unable to send trace and customEvent to application insights

### ISSUE THREAD

**Issue by Dan-Bai** [microsoft/BotFramework-Composer#5671]
I have already modified __TelemetryTrackEvent__ to __TelemetryTrackEventAction__ and added instrumentationKey.
There are no errors but also no logs showing up in AppInsights.

I can't find in generated runtime code where telemetry client is generated and available.

**Comment by Dan-Bai** [comment]
I may have resolved this by initializing telemetryClient this way
<img width="651" alt="image" src="https://user-images.githubusercontent.com/25358214/106513337-d8379b80-64a0-11eb-93e5-ec4e86276d84.png">

**Comment by stevkan** [comment]
Hi @Dan-Bai, are you still needing assistance on this issue or did you solution solve the problem?

**Comment by Dan-Bai** [comment]
Hello @stevkan, I still need assistance. The solution I provided is not adding the necessary conversation properties such as __coversationId__ and __activityId__ to any of logs sent to application insights. Any direction on this issue would be appreciated.

**Comment by v-kydela** [comment]
Sorry for the delay, @Dan-Bai

When you click the button to create a [new issue](https://github.com/microsoft/BotFramework-Composer/issues/new/choose) in this repo, you should be given a choice like this:

![image](https://user-images.githubusercontent.com/41968495/108127379-06e87100-7060-11eb-8f14-8089055b65df.png)

If you choose "bug," you'll be given an [issue template](https://github.com/microsoft/BotFramework-Composer/blob/main/.github/ISSUE_TEMPLATE/bot-framework-composer-bug.md) that you can use to give us the information we need in order to help you. The template includes things like repro steps and screenshots (note: please do not post screenshots of code). We need to know things like how you arrived at your problem so that we can reproduce it on our end, and what your expected behavior and actual behavior are. And it's always a good idea to provide links, especially if you followed any samples or documentation.

Can you provide that information for us?

**Comment by Dan-Bai** [comment]
Here is the issue I opened #5808

**Comment by v-kydela** [comment]
@Dan-Bai - I will close this issue in favor of the new one
