### ISSUE TITLE
Orchestrator: ChooseIntent (aka Duplicate Intent) Trigger doesn't work when using Orchestrator

### ISSUE THREAD

**Issue by taicchoumsft** [microsoft/BotFramework-Composer#5747]
## Describe the bug
When using Orchestrator with a `ChooseIntents` trigger in a dialog, Orchestrator will not pop up the disambiguation prompt, even if all conditions are met.

## Additional context
`OrchestratorRecognizer` supports this scenario, but we need to explicitly set the `detectAmbiguousIntents` flag in the recognizer for the dialog if it has a duplicate intent/`ChooseIntent` trigger. 

Fix is to add this flag to orchestrator recognizer settings for every dialog that has a `ChooseIntent` trigger.

**Comment by boydc2014** [comment]
Is this still on track on R13? @taicchoumsft 

Regarding the fix, should we add the flag only to every dialog that has an onChooseIntent trigger,  or we can just add it for all orchestrator recognizer? What will be the harm of adding it for all cases?

**Comment by taicchoumsft** [comment]
Yes one fix is to add flag only to dialog that has onChooseIntent trigger, and expose the recognizer thresholds in Composer somewhere.  

I experimented with adding it for all, but then dialog will not work as expected when Orchestrator returns ChooseIntent and there is no onChooseIntent trigger to handle.

**Comment by boydc2014** [comment]
> Yes one fix is to add flag only to dialog that has onChooseIntent trigger, and expose the recognizer thresholds in Composer somewhere.
> 
> I experimented with adding it for all, but then dialog will not work as expected when Orchestrator returns ChooseIntent and there is no onChooseIntent trigger to handle.

I feel like that is the expected behavior, if orchestrator returns ChooseIntent and there is no trigger, and thus nothing happens. 

I think it's down to the question, do we think ChooseIntent from Orchestrator is "trustworthy" or not.  If it is, i feel like it makes more sense that we add this flag for all cases, and educate user that, "you know, not always one single intent win, you need to design for ambiguous case".   If not, probably, adding this flag conditionally is better, it would be less breaking. 

what do you guys think? @scheyal @chrimc62
