### ISSUE TITLE
bot with qna overwrite knowledge base in qnamaker

### ISSUE THREAD

**Issue by KarlXOL** [microsoft/BotFramework-Composer#5767]
I'm not sure wether this is a bug, wrong application or a conceptual misunderstanding of how bot with qna and qnamaker work.

What I'm doing
1. Create a bot with bot composer
2. add a qna-knowledgebase with some q&a pairs
3. publish bot
4. then I updated this knowledge base  in the https://www.qnamaker.ai
5. publish bot again
==> then all knowledge base changes I did in the qnamaker are gone

Is this the way it should work? Actuall I'd expected the main tool for managing the knowledgebase is the qnamaker not the bot composer

Thanks in advance for any feedback

**Comment by iMicknl** [comment]
Related to https://github.com/microsoft/BotFramework-Composer/issues/5373. I just stumbled upon the same issue during a proof of concept. In simple bot scenario's it makes a lot of sense to have a business user manage QnAMaker where developers can handle more complex flows via Composer + LUIS.

**Comment by Virtual-Josh** [comment]
Hey @jwiley84 do you want to attempt a repo and see if this belongs more on the product side or the support side?

**Comment by cwhitten** [comment]
hello @KarlXOL. This is indeed by design. The data stored locally in the .qna files are the source of truth when using Composer. There is a feature request to provide service syncing with the QnAMaker portal, which is here: https://github.com/microsoft/BotFramework-Composer/issues/5373

Closing as a feature request/dupe
