### ISSUE TITLE
Variables not parsed in HTTP Request Url

### ISSUE THREAD

**Issue by mpcrossley** [microsoft/BotFramework-Composer#5855]
## Describe the bug

When filling out the "Url" field in the "send an HTTP Request" function, it does not expand variables.
## Version

1.3.1 - there is no build SHA.

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Add Set a property (Property: user.city, Value:'Victoria')
Add Send a HTTP request (Method: Get, Url: "http://api.openweathermap.org/data/2.5/weather?q=${user.city}")
Run the bot
${user.city} is not used, request fails as it is passed as a string.

## Expected behavior

variabe is passed as its value.

## Screenshots

![image](https://user-images.githubusercontent.com/9376945/108604006-2208f880-7360-11eb-8f95-98a3b92a279d.png)

**Comment by mpcrossley** [comment]
I forgot to mention that it's very similar to this issue: https://github.com/microsoft/BotFramework-Composer/issues/2695

But I tried their suggestions to no avail, I got a similar error as the other person that had a parsing error when I added a "=".

**Comment by stevkan** [comment]
@mpcrossley, I was able to repro the behavior. I am presently looking into possible workarounds, if any.

**Comment by stevkan** [comment]
@mpcrossley, first off I made a mistake on my end and I'm actually not able to repro the behavior. Apologies for any confusion.

Comparing the trace activity between your screenshot and my attempt, they both look identical when the JSON properties are collapsed to the first level. When I expand the `value` property (see below) I can see the interpreted URL as well as the response. The `label` property only shows the literal request that was made.

Are you receiving an error message? If so, can you post that error?
If you expand the `value` property, is it similarly populated?

Also, regarding using "=" or not, you will want to include it. It's possible to pass in a plain string in the URL field, but with a string literal included you need to treat the field as an expression by prepending the string (wrapped in ticks) with the "=" sign. Otherwise, the field will read the entry as-is.
> =`http://localhost:3500/data/json?p=${user.city}`

![image](https://user-images.githubusercontent.com/18403946/108927579-6234d900-75f5-11eb-8318-7a8b0b38850d.png)

![image](https://user-images.githubusercontent.com/18403946/108927209-b55a5c00-75f4-11eb-9604-5aa5414c0689.png)

**Comment by stevkan** [comment]
Closing due to lack of response.

**Comment by rahul-8437008949** [comment]
@stevkan I am still facing the issue .
My http request:  =https://xyz.com(key=${dialog.id})
error : mismatched input ‘:’ expecting <EOF>
