### ISSUE TITLE
Cannot opt-in into the Early Adopters channel

### ISSUE THREAD

**Issue by peterswimm** [microsoft/BotFramework-Composer#5932]
## Version
1.3.1
Electron: 8.2.4
80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
              

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

When I enable the early adopter toggle, it fails to update when I check for update (doesn't matter if I select restart now or restart later)

The initial error is:
Couldn't complete the update: Error: ditto: Bot Framework Composer.app/Contents/Resources/app.asar: No such file or directory ditto: Couldn't read pkzip signature.

And sometimes 

Update failed
Couldn't complete the update: Error: ENOENT: no such file or directory, rename '/Users/pswimm/Library/Application Support/Caches/@bfc/electron-server/pending/temp-BotFramework-Composer-1.3.1-nightly.217012.67a05de-mac.zip' -> '/Users/pswimm/Library/Application Support/Caches/@bfc/electron-server/pending/BotFramework-Composer-1.3.1-nightly.217012.67a05de-mac.zip'

There is no such zip in that folder.

## Expected behavior

I expect to be updated to the latest nightly.

## Screenshots

![Screen Shot 2021-02-24 at 8 52 35 AM](https://user-images.githubusercontent.com/1554372/109028184-2ba79e80-7687-11eb-8a26-50aaf197f1b1.png)
![Screen Shot 2021-02-24 at 9 01 25 AM](https://user-images.githubusercontent.com/1554372/109028203-2f3b2580-7687-11eb-968f-259b410c7ab6.png)

**Comment by srinaath** [comment]
We will try reproing this error @peterswimm . We thought we resolved it.

**Comment by tonyanziano** [comment]
@peterswimm can you try reproducing this after starting Composer from the terminal with the following environment variable set:

`DEBUG=composer*`

You should see a lot of output in your terminal when you run Composer. It would be helpful if you could repro this issue and post the log output here. It should show us the behavior of the app updater.

**Comment by peterswimm** [comment]
@tonyanziano I'm sorry I'm not seeing where/how to set that debug variable. Could you point me to more information? A quick search here wasn't illuminating.

**Comment by tonyanziano** [comment]
@peterswimm No worries, I could have been more clear:

The goal here is going to be to start Composer from a terminal / command line so that we get the verbose log output.

1. Open a command line or terminal application
2. Navigate that instance of terminal to wherever Composer is installed on your machine
3. In that terminal, set the `DEBUG` environment variable to `composer*`
  **On Windows**, you do this by running the command `set DEBUG=composer*` in that terminal (not sure how to do this on Mac -- `export DEBUG=composer*` ??)
4. In that same terminal, now execute the Composer binary to start Composer
5. You should now see a ton of output in the terminal while Composer starts up

Let me know if you need help and I can hop on a quick call.

**Comment by daveta** [comment]
Closing issue..
