### ISSUE TITLE
Unexpected list size for Teams triggers UI

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/BotFramework-Composer#6014]
## Describe the bug

When adding a trigger for teams, the displayed popup appears larger than expected (extra white space).

## Version

latest from main branch, local build, commit d9ee12c

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. select "Add a Trigger"
2. Choose "Microsoft Teams" for the type
3. Click the "Which Teams Event"

## Expected behavior

A popup no larger than the list (like the others).

## Screenshots

![composer-teams-events](https://user-images.githubusercontent.com/1024902/109316575-63425200-7811-11eb-9bf9-462efb2a25b4.PNG)

**Comment by yeze322** [comment]
There are two problems in this screenshot:
1. A too long Trigger dropdown menu - We've planned a new Trigger Wizard in the next Sprint, in R12, Teams will still be a preview feature so the menu was not crafted.
2. Menu label is missing - This is because Teams actions' uischema are not fully added, there is a PR for fixing that https://github.com/microsoft/BotFramework-Composer/pull/5710

**Comment by yeze322** [comment]
'extra white space' was fixed by 5710.
Needs more work to fix the grouping problem.

**Comment by yeze322** [comment]
@luhan2017 please triage and reassign, thanks!
