### ISSUE TITLE
LG export is not useful

### ISSUE THREAD

**Issue by chrimc62** [microsoft/BotFramework-Composer#6096]
## Describe the bug

You can export LG templates using the Exports/namespace syntax like this:
```
> !# Namespace=blah
> !# Exports=foo
# foo()
- something
```
The reason you do this is to prevent template name collision, but the current implementation does not prevent that collision. I can call this template as either `foo()` or `blah.foo()`, but I cannot define a different template `foo` in another file. 

## Version
![image](https://user-images.githubusercontent.com/17637681/109722530-ad08a080-7b61-11eb-8ec8-aa62dd2798a1.png)

## To Reproduce

1. Create an empty bot 'main'
2. Change you main bot and common files:
main.lg:
```
[import](common.lg)
# SendActivity_Welcome()
- foo(): '${foo()}' blah.foo(): '${blah.foo()}'

# foo()
- Something
```

common.lg: 
```
> !# @Namespace=blah
> !# @Exports=foo
# foo()
- exported foo
```
3. You will see an error like this:
![image](https://user-images.githubusercontent.com/17637681/109723035-69626680-7b62-11eb-9bbd-3a0204d1b2cd.png)

If you change the main template to: 
```
[import](common.lg)
# SendActivity_Welcome()
- foo2(): '${foo2()}' exported foo(): '${foo()}' exported blah.foo(): '${blah.foo()}'

# foo2()
- Something
```
You will get no errors and you can call the imported template with or without the namespace.

## Expected behavior

I should be able to define a local template and not have it conflict with an imported one--otherwise there is no point to a namespace from the LG template standpoint.  (Still useful to extend adaptive expressions though.)  I would propose that when you export a template name it can only be referred to with its namespace outside of that file.  (Either the default namespace based on file or an explicit one.)  That way we can keep the current behavior of identifying duplicates in the "global" namespace while still being able to carve out a namespace by explicitly exporting templates.

**Comment by boydc2014** [comment]
Agreed from the perspective of preventing naming conflicts.  Exports + namespaces was introduced to bridge LG sub system to actions beyond SendActivity, by extending adaptive expression functions with LG templates.  

Now, given the LG-Dialogs store is going to be we want to make sure LG templates generally available in any actions without having to do any exports, namespaces, making everyone's life easier.  What that means to the naming conflicting issue is we don't have to reuse namespace + exports just because they are there (because they probably don't have to be there, or won't be there soon). 

So, i'd like to think about the name conflicts from a fresh start, including the ideas you proposed earlier about lg interheirts, a few thoughts in my head without thinking too much
1. as this proposal, reuse namespace + exports, and make sure exported templates can only be refered with namespace.
2. completely drop namespaces and exports, instead, extending the import syntax with a postfix like [import](an lg file)#name, using this name as namespace, and the mechanism will be, only when the name conflicts you have to use namespace to refer. This is a more aligned approached like a normal programming language. 
3. something in between 1 and 2, or some adjustment applied in 1 or 2

I need to dig a little in and explore more options and let's group together and discuss the options, how about that?

**Comment by chrimc62** [comment]
I kind of like the combination of 1 (if you do export you have to use namespace) and 2 (specifying a namespace when you import).  Happy to chat when you look into it more.
