### ISSUE TITLE
Web Chat (or more fundimental) error after changing an LG template

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#6149]
## Describe the bug

After changing the template and restarting the bot, the bot is responding with the previous version of the template.

## Version

                Version:  1.3.1-nightly.219396.61c944a
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an echo bot.
2. Change the **Send a response** activity template in the **Unknown intent** trigger to:
	~~~lg
		-  ```
		You said:
		> ${turn.activity.text}
		> 1. **Type**: ${turn.activity.type}
		> 1. **Value**: ${turn.activity.value}
		```
	~~~
3. Restart the bot and test it in Web Chat. (This part works as expected.)
4. Change the template to:
	~~~lg
		-  ```
		You said:
		> ${turn.activity.text}
		- **Type**: ${turn.activity.type}
		- **Value**: ${turn.activity.value}
		```
	~~~
5. Restart the bot and text it in Web Chat.
6. **Error**: I got this output (which does not match the updated template.)
    ![image](https://user-images.githubusercontent.com/35047199/109873864-38963600-7c23-11eb-9f5e-f1ee21816931.png)

## Expected behavior

The Markdown should render correctly.
1. The numbered list should be a bullet list.
2. The list should be outside the blockquote.

for example:

You said:
> ${turn.activity.text}
- **Type**: ${turn.activity.type}
- **Value**: ${turn.activity.value}

## Additional context

- Secondary error: I should not need to restart Web Chat to see the changes in the template if the resource manager is working correctly. It should notice changes in the resource files and reload them on the fly. (A baked in feature of the SDK.)

**Comment by garypretty** [comment]
I believe this has to do with how the LG is structured.  I have seen the resource manager work for LG in the current runtime intermittently (where I can update some LG and immediately see a change in the emulator), even though it never works for dialogs.  Right now we are expecting the new runtime to be updated so that the resource manager correctly refreshes dialogs / language files on update as per a recommendation from @tomlm.  Given this is related to the current runtime, I don't anticipate we would fix the existing behavior ahead of replacing it in a few weeks in R13 and so I will close this issue.
