### ISSUE TITLE
Clicking on a link in the readme for a template opens the page in composer

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#6156]
## Describe the bug
Clicking on a link in the readme section of the Select a template dialog opens the page in full screen and couldn't find a way of getting back to composer.

## Version
1.3.1-nightly.219396.61c944a

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Enable the new bot creation experience flag.
2. Add a new bot and select Empty bot.
3. Click on the component model link in the readme section.
![image](https://user-images.githubusercontent.com/12264946/109878930-f0870b80-7c42-11eb-9e63-e81d77764a1a.png)
4. The page will open and there are no navigation buttons to go back.
![image](https://user-images.githubusercontent.com/12264946/109879010-0c8aad00-7c43-11eb-9999-b0281c99759a.png)

## Expected behavior

I would expect the links to be open in my default browser window.

**Comment by benbrown** [comment]
@pavolum  we may need to do a clever rewrite on links in the markdown to include a target... or somehow otherwise catch links in this area and redirect them.

**Comment by pavolum** [comment]
This is a redundant issue and has been fixed in a seperate PR
Link Target = "_blank" in the following line of code ensures that any markdown link within the readMe renders in a new window
https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/client/src/components/CreationFlow/v2/TemplateDetailView.tsx#L65
