### ISSUE TITLE
Exception thrown when trying to use the date function

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#6160]
## Describe the bug

The bot throws an exception when trying to render the current date using the date function.

## Version
![image](https://user-images.githubusercontent.com/12264946/109881316-15c94900-7c46-11eb-9bbf-900bc1d22478.png)
## Repro

1. On any bot, add a Send a response task
2. Set the text to `Today is ${date(timestamp)}`
![image](https://user-images.githubusercontent.com/12264946/109881450-53c66d00-7c46-11eb-991a-bfec5ac30ca7.png)
3. Run the bot and you'll get an error in webchat:
![image](https://user-images.githubusercontent.com/12264946/109881495-66d93d00-7c46-11eb-9f59-8fa963998dea.png)

## Expected behavior

I would have expected to see today's date.

**Comment by cosmicshuai** [comment]
Hi @gabog, the datatime related functions in Adaptive-Expressions can only take an ISO timestamp or a datetime object as input, except formatDateTime function. One workaround for your issue is, you can use ` date(formatDateTime(timestamp)) `. This will ensure the input value for `date` function is an ISO timestamp.

**Comment by gabog** [comment]
thanks for the help @cosmicshuai, the function I really needed was utcNow(). I'll close the issue.

Thanks again.
