### ISSUE TITLE
We need to support abs handoff for new creation flow. 

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#6190]
## Describe the bug

Turn on the Create New Flow flag and Open in composer from abs. 

It is v2 templates with v1 UX 
![image](https://user-images.githubusercontent.com/32191031/109945953-b7b66780-7d12-11eb-95b9-0342a8f0b8a4.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by benbrown** [comment]
There are three pieces of this:

1. this block needs to be ported into the code that currently handles the completion of the provisioning process -> https://github.com/microsoft/BotFramework-Composer/blob/702f34ac70943626a1afda57ffce9b408708bdd9/Composer/packages/client/src/recoilModel/dispatchers/project.ts#L315


2. New create flow needs to handle this alias field -> https://github.com/microsoft/BotFramework-Composer/search?q=getAliasFromPayload

3. Need to open the new create modal instead of the old one -- this could be handled by checking the feature flag in the electron server, or by doing it in the client.  server code is here: 
https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/electron-server/src/utility/url.ts#L33
