### ISSUE TITLE
PackageManager doesn't show nuget packages I install using CLI or Visual Studio

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6231]
## Describe the bug
When I installed a nuget package via CLI or Visual Studio packagemanager

## Version

1.3.1-nightly.219713

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Load .sln file
2. Add a component package using nuget manager
3. Load project in composer and go to package manager
4. The package that was added doesn't show up in the UI as being installed.

## Expected behavior

The package maanager should reflect the state of the packages added.

## Screenshots

Visual Studio

![image](https://user-images.githubusercontent.com/17789481/110056623-0adcea00-7d14-11eb-8141-fe164cb2de90.png)

dotnet CLI
![image](https://user-images.githubusercontent.com/17789481/110056844-6018fb80-7d14-11eb-8998-0966f87713d9.png)

composer
![image](https://user-images.githubusercontent.com/17789481/110056885-6dce8100-7d14-11eb-9810-c9e679d5846f.png)

**Comment by benbrown** [comment]
Package Manager currently only shows packages that include a schema file, or >=1 exported declarative file.   The intent is for package manager to be *for conversational components*, not for every type of package you might use.

Otherwise, it *shouldn't* matter where they are installed. 

Do those packages that didn't appear include schema files?

**Comment by benbrown** [comment]
This has been updated to show any package with the appropriate set of tags.

@tomlm let me know if you have issues in the latest builds.
