### ISSUE TITLE
Bot should not be blocked from running if there potential syntax error

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6280]
## Describe the bug

When there is a syntax error the bot is blocked from running.  There is no reason to do this, we already are communicating that there is a perceived error, and composer is NOT perfect in it's ability to detect errors.

## Version

1.3.1-nightly.220254

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to a send activity template
2. as soon as you type something COMPOSER doesn't understand, it disables the ability to start the bot.  

## Expected behavior
You should NOT disable the run bot menu on perceived errors.  BTW:if I type **dog**, which is a non-existent property you don't flag it as an error and you don't stop me from running the bot.  Why are you doing it when call **humanizer.pluralizer('dog')**?

## Screenshots
![image](https://user-images.githubusercontent.com/17789481/110179009-2ef40600-7dbc-11eb-9eb1-f0e0403922a6.png)

**Comment by boydc2014** [comment]
What kind of errors you see in your case, unknown functions? 

I think there are two things in this issue
* Should composer block starting bot when unknown functions detected(a semantic error). The behavior today is yes, it will block unless you inform compose the unknown functions. This is probably arguable. 
* Should composer block starting bot when there is syntax error. The behavior today is yes. And i think this is probably correct, since a syntax error is almost for sure to get you a runtime error, and bot will fail. 

Does that make sense?

**Comment by boydc2014** [comment]
per the discussion with @cwhitten, let's treat unknown functions as warning for now @lei9444
