### ISSUE TITLE
Dynamic/Custom Adaptive card implementation in Bot Composer.

### ISSUE THREAD

**Issue by LakshummaC** [microsoft/BotFramework-Composer#6311]
Hi Team,

Earlier using VA Template we have customized the adaptive card using for loops and adaptive card nugget packages.
Now our requirement is using BOT COMPOSER we have Add/Remove buttons, where on 'Add' button click new Input text has to be added and on 'Remove' button click one input text has to be removed from adaptive card prompting and finally display list of results as another adaptive card.

Inputs:
List of name and age
![image](https://user-images.githubusercontent.com/76558423/110319217-9320ff00-8034-11eb-9c65-1a7e43e65f57.png)

Output:
![image](https://user-images.githubusercontent.com/76558423/110319395-cfecf600-8034-11eb-9418-d377baacb3a4.png)

How to achieve this in Bot Composer?

**Comment by v-kydela** [comment]
@LakshummaC - You can see a solution discussed [here](https://stackoverflow.com/a/57418517/2122672) (though you may need to export the runtime in order to get that to work in Composer)

Are you targeting Web Chat or Teams?

**Comment by LakshummaC** [comment]
> @LakshummaC - You can see a solution discussed [here](https://stackoverflow.com/a/57418517/2122672) (though you may need to export the runtime in order to get that to work in Composer)
> 
> Are you targeting Web Chat or Teams?

Currently our target is WebChat.

**Comment by v-kydela** [comment]
@LakshummaC - As I said, you may need to export the runtime in order to get that to work in Composer. If you do export the runtime then you can write code like you would with a normal bot. However, it may still be possible to do what you're trying to do without exporting the runtime, depending on which route you go.

Since you're using Web Chat and not Teams, you won't be able to use a solution that involves updating the activity. However, there's an even more advanced possibility that involves updating the card on the client side. If you want to go that route, you will need to study up on Adaptive Card extensibility. You can use [this post](https://stackoverflow.com/a/61621137/2122672) and it's many linked questions as a starting point.

![image](https://user-images.githubusercontent.com/41968495/110513757-6e239f00-80bb-11eb-87a1-83f3132c8787.png)

If you need further help, we do prefer to have how-to questions asked on [Stack Overflow](https://stackoverflow.com/questions/ask) instead of GitHub. This reaches a larger audience, allowing more people to possibly answer the question and more people to be helped by the answer. If you use the [`botframework`](https://stackoverflow.com/questions/tagged/botframework) tag then my team will be sure to see the question.

I will close this issue as not a bug.
