### ISSUE TITLE
Pass an array to skill

### ISSUE THREAD

**Issue by rahul-8437008949** [microsoft/BotFramework-Composer#6390]

**Comment by jwiley84** [comment]
Closing as a duplicate of https://stackoverflow.com/questions/66594199/how-to-pass-multiple-values-to-a-skillarray-json-etc-from-a-bot-in-bot-compose

The bot framework team prefers that **how-to** questions be asked on stack overflow. As you've already asked this exact question there, I'm going to close this question so that we might address the answer there.
