### ISSUE TITLE
Can not start bot for using orchestrator recognizer

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#6407]
- Create bot using 1.3.1 nightly 
- install composer 1.4 rc0
- eject runtime to install orchestrator package
- set orchestrator recognizer 
- start bot will hit following error
![image](https://user-images.githubusercontent.com/43408889/111095820-387a2c80-8579-11eb-8672-e59c3d364340.png)

**Comment by boydc2014** [comment]
@taicchoumsft  can you help check this one, looks like component registration fails to work as expected

**Comment by taicchoumsft** [comment]
@hibrenda, is the bot a new "component model" bot, using the new creation experience? If it is an older root bot using the legacy runtime, you have to add the Orchestrator registration manually since we took Orchestrator out of the 1.3.1 runtime (follow Step 4 onwards here) : https://github.com/microsoft/BotFramework-Composer/blob/main/docs/preview%20features/orchestrator.md#adding-orchestrator-to-a-new-bot-in-composer

**Comment by hibrenda** [comment]
@taicchoumsft  thanks for the instruction. Yes. I am using legacy runtime. With the instruction. It worked now.
