### ISSUE TITLE
unable to load Bot Framework Composer 

### ISSUE THREAD

**Issue by ABHILASH4012** [microsoft/BotFramework-Composer#6408]
unable to load Bot Framework Composer after installing all Prerequisites

**Comment by boydc2014** [comment]
Hi, @ABHILASH4012 are you building the web version or use the electron version in the release page?

If it's the web version, can you share the messages when you run yarn start (after yarn install && yarn build)

**Comment by ABHILASH4012** [comment]
HI @boydc2014 

It is the local desktop app that i have installed

**Comment by carlosscastro** [comment]
Hello @ABHILASH4012 : I'm closing this bug because of insufficient information. Feel free to re-activate or create a new bug and provide which version you installed, where you got the installer from and what the result was through a screenshot. Also I'm not clear on what you mean by `installed all prerequisites`, please clarify. We need all this info to support you in the most efficient way possible, thanks in advance!
