### ISSUE TITLE
Create Copy for Share Resource Request Instructions

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6566]
## Is your feature request related to a problem? Please describe.

The Copy on the Share Resource Request Instructions needs to be determined and created

## Additional context

![image](https://user-images.githubusercontent.com/18688053/112543201-6df5f580-8d83-11eb-9304-a70e85204206.png)

**Comment by JaskeeratBedi-cmk** [comment]
Updated copy

@benbrown is the command going to be very long or does it constrain at 3 sentences? Asking because the position of 'Learn more' may need to move above if command becomes very long..

![share](https://user-images.githubusercontent.com/67944302/113224952-60d47d00-9241-11eb-94ee-4964ede7c611.png)
