### ISSUE TITLE
Random words trigger incorrect intents

### ISSUE THREAD

**Issue by blakehoughton** [microsoft/BotFramework-Composer#6699]
## Describe the bug

Random words when entered into the emulator triggers incorrect intents. For example I have an intent that sends a response if one of the following words are detected eg. "37", "currency", or "money" but when I enter the word "banana" in the emulator this intent is recognized and triggers a response? Why is this?

Here is the example of the intent below:

![image](https://user-images.githubusercontent.com/70548503/113635124-28f78a80-96c4-11eb-8c6c-32b19188ef66.png)

Here is the example of an unknown intent recognized which is expected in this instance when the word "banana" is said:

![image](https://user-images.githubusercontent.com/70548503/113635178-43316880-96c4-11eb-84e5-ddfca3159e88.png)

Any ideas? I need every single word that is not recognized to bring up the unknown intent response shown above.

## Version
v1.4.0

## Browser

- [ ] Electron distribution
- [X ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

**Comment by dmvtech** [comment]
Hi @blakehoughton 

I'm not sure how familiar you are with LUIS, but NLP technologies need a fair amount of training to be really decent. My assumption for your above situation is that this is just using Composer and an authoring endpoint; is that correct?

I'm not sure why 'banana' is being picked up as an intent. I tested in the LUIS portal, and it behaves the same. The one thing that does help in these situations is having your **none** intent trained as well. You can do this in the portal, but any re-run of the bot in Composer will republish and overwrite. In a _production_ application, you would want your None intent properly trained with garbage phrases like 'banana', 'i like pickles' and 'where is Nebraska?'. 

More/better utterances typically help as well, but even deleting the LUIS app and then using something like:
```
-I want to spend $37
-Please give me info on currency
-How much money will it cost?
```
Didn't really help me. 

I also created another intent:
```
- I need to give {person=Joe} his review
- Set up a review with the team
- Please schedule a meeting with {person=Dana}

@ ml person
```
And was still getting _that_ intent when using 'banana'.


Just a side note, you don't the quotes in your trigger phrases. I believe LUIS will interpret that correctly (remove to train), but you don't need them.

So, instead of:
```
-"37"
-"currency"
-"money"
```

You can have:
```
-37
-currency
-money
```

I'll still look into this and let you know what I find.

@luhan2017 Any ideas or insight here on what might be going on?

**Comment by blakehoughton** [comment]
Thanks @dmvtech ,

Yes this is simply just using the composer and the authoring endpoint. I will have a go at training the none intent and putting in random phrases but this will require a lot of time/training,

Thanks for your ongoing help.

**Comment by dmvtech** [comment]
Thanks @blakehoughton 

Yeah, this is essentially due to how LUIS works, specifically with regards to the none intent. The none intent/trigger will get hit for garbage terms such as `asdfasdf`. But without training the none intent with utterances, this is going to be the behavior. As I mentioned, the behavior is the same, even in the LUIS portal. And still has a high score (banana was at least over 0.90).

So, the suggestion for development and testing, is to use both more robust utterances as well as less-likely (garbage) utterances to ensure hitting none intent when intending to. Then, when moving to production/publishing, you would flush out and fortify your none intent.

Here is some more info on LU:
https://docs.microsoft.com/en-us/composer/concept-language-understanding
