### ISSUE TITLE
Error: Failed to bind LUIS prediction resource

### ISSUE THREAD

**Issue by damlaalkan** [microsoft/BotFramework-Composer#6763]
I am getting this error: 
Error - Failed to bind luis prediction resource to luis applications.
Please check if your luisResource is set to luis prediction service name in your publish profile.
<img width="796" alt="ComposerError" src="https://user-images.githubusercontent.com/37966893/113867604-5fb8c800-97cc-11eb-98c0-b9e234556b49.PNG">

Can someone help me or give some pointer here?

_Originally posted by @praful-dhone in https://github.com/microsoft/BotFramework-Composer/issues/5354#issuecomment-814880819_

**Comment by lauren-mills** [comment]
Hi @damlaalkan - can you verify what your publish profile contains in the LUIS section? You can find it in your appsetting under hte publishProfiles property. If you can send it and remove the keys, that would help us triage this.

**Comment by anusharavindrar** [comment]
@damlaalkan, can you respond to Lauren's above query or share your publish profile so that we can investigate further.

**Comment by damlaalkan** [comment]
> Hi @damlaalkan - can you verify what your publish profile contains in the LUIS section? You can find it in your appsetting under the publishProfiles property. If you can send it and remove the keys, that would help us triage this.

Hello @lauren-mills  and @anusharavindrar I have added "LuisResource" and it worked right now thank you!
Unfortunately when I publish the app to Azure Bot, the adaptive cards does not seem in the Test Web Chat or in Iframe altough it works in Bot Composer test and Emulator, do you have any suggestions for that?

**Comment by lauren-mills** [comment]
Would you mind opening a separate issue and including your adaptive card json (with any sensitive data removed)? There are sometimes discrepancies in support between the different channels so I can try to help figure it out.

**Comment by lampeTechnidoo** [comment]
I have the same problem since weeks with V1..4.0  with that in other version it could be another error. Overall version since V1.2.1 it regards this post https://github.com/microsoft/BotFramework-Composer/issues/6482

So i hope you can help me too, as you did it for user damlaalkan.

Here is my publishing profile
![image](https://user-images.githubusercontent.com/73934108/114791102-2c56da00-9d86-11eb-815c-b00106fbf402.png)

  "resourceGroup",  "botName", "subscriptionId", "region" was insitially set but in the  many tries it has no effect  and so in new settings I didn' fill them with values.

accessToken is not needed for V1.4.0 but was needed for V1.2.1.

MyEmmyBot3-LUIS-Authoring
Resource group:RG-TestDeploy-LogApps-110221
Location:westeurope
Primary Key: ***1
Secondary Key: ***
Endpoint URL: https://my***bot3-luis-authoring.cognitiveservices.azure.com/

MyEmmyBot3-LUIS-Prediction
Resource group:RG-TestDeploy-LogApps-110221
Location:westeurope
Primary Key: ***1
Secondary Key:***
Endpoint URL: https://m***bot3-luis-prediction.cognitiveservices.azure.com/

**Comment by anusharavindrar** [comment]
@lampeTechnidoo, can you please open a new issue and explain in detail about the error you get in both the versions?

Closing this issue as resolved.

**Comment by damlaalkan** [comment]
> Would you mind opening a separate issue and including your adaptive card json (with any sensitive data removed)? There are sometimes discrepancies in support between the different channels so I can try to help figure it out.

Hello, I have created a new issue about it.
https://github.com/microsoft/BotFramework-Composer/issues/7164

**Comment by hshahbaz** [comment]
> > Hi @damlaalkan - can you verify what your publish profile contains in the LUIS section? You can find it in your appsetting under the publishProfiles property. If you can send it and remove the keys, that would help us triage this.
> 
> Hello @lauren-mills and @anusharavindrar I have added "LuisResource" and it worked right now thank you!
> Unfortunately when I publish the app to Azure Bot, the adaptive cards does not seem in the Test Web Chat or in Iframe altough it works in Bot Composer test and Emulator, do you have any suggestions for that?

can you share the final version of your publishing profile? Where did you add "LuisResource" and what was the value for it?
