### ISSUE TITLE
Home Page "Save as" menu option is confusing

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#6808]
## Describe the bug
We seem to be mixing metaphors on the new home page.  I get creating new bots, or opening an existing bot from this page.  What I don't understand is what is the role of the "Save as" menu option?

What am I saving as?

## Version
Version:  1.4.0-nightly.232669.4daad5c
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open or create a new bot
2. Click on home icon in the left hand nav so you can return to the home page.
3. Click the "Save as" menu option
4. Notice you get a Create a bot project model

## Expected behavior
I understand the need for a Save As, or even a rename.  I just find it odd to be on the home page.

**Comment by emivers8** [comment]
FYI design incoming for this and other project settings updates @pavolum.

**Comment by mewa1024** [comment]
The "Save As" button appearing on the home page is part of larger inconsistency: for actions that one would normally perform on a file/project, we sometimes perform at the bot project level and sometimes at the bot-*within*-a-project level.

### Current behavior

- "**New**" (on home page): creates a new **bot project**. The user selects the location of the bot project folder.
- "**Open**" (on home page): opens a **bot within a project**. The user must select the location of the bot, not the bot project folder. (If the bot is the root bot of a project, it in effect opens the project. If it is a skill within a project, it opens only that bot.)
- "**Delete a bot**" (on the project settings page): deletes a **bot within a project.**
- "**Save As**" (on the home page): duplicates the **root bot** only. Does not duplicate the bot project. 
(_**Problems**: The location of the Save As button on project-wide part of the experience would imply that it saves the project, but it does not. There is no control within Composer to duplicate a bot project.)_

### New behavior
- "**New**" (on Home): _no change_
- "**Open**" (on Home): _no change_
- "**Delete**" (on Project Settings): Split Delete action:
   1.  On Project Settings, above the page content, cchange "**Delete**" to "**Delete project**" and change the behavior so it deletes the entire bot project, rather than a bot in the project.
   1.  On Project Settings, in the bot-specific sections, add "**Delete bot**". This button will deletes just the bot in this project. (Designs to come--see Em's note above)
- "**Save As**" (on Home): Split the duplicate action:
    1.  "**Save As**" (on Home) duplicates the **bot project**, including all bot/skills in the bot project folder. 
    1.  On Project Settings, above the page content, add  "**Save As**" which also duplicates the **bot project**
    1.  On Project Settings, within bot-specific content, add "**Duplicate bot**" which duplicates just the selected bot or skill
    
- on home page, to "Recent bots" list, add overflow menu with these actions:
  - "Duplicate bot"
  - "Remove from list"
  - "Reveal in folder"
  - "Delete bot"
  Since the "Recent bots" list specifies down to the bot level, all these action apply to a bot, not bot project.

**Comment by xiyangdesign** [comment]
This issue is related: https://github.com/microsoft/BotFramework-Composer/issues/5526

**Comment by mewa1024** [comment]
@srinaath, @cwhitten Em and Patrick are working on the changes for the Project Settings page.

**Comment by mewa1024** [comment]
(new screen after Save As - it doesn't allow you to change the name, but instead directs you to choose a folder where you will save it:

![image](https://user-images.githubusercontent.com/39317542/115474041-7231f900-a1f1-11eb-94fc-365458024b07.png)

**Comment by mewa1024** [comment]
The solution will take more investigation: at this time we don't have a reliable way to determine if a folder is a bot project folder. Recommending we remove the "Save As" button completely for until we are able to implement a "Save As" action on the project foler.

**Comment by sgellock** [comment]
Shiproom - expection for this one is that the Save As button is removed for R13, and we'll revisit this flow post R13

**Comment by cwhitten** [comment]
R13 scope has been met, re-labeling to be scoped in a future milestone.

**Comment by mewa1024** [comment]
@srinaath Can we take this for R15? The ability to Save As or Delete on the bot project level? Dewain filed similar bug - #7616

**Comment by srinaath** [comment]
@mewa1024 Definitely makes sense to push to R15. This feature is being tracked in the Creation workstream currently. @benbrown can we remove the R14 label out of this?
