### ISSUE TITLE
Form Dialog generating multiple utterances

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#6830]
## Describe the bug
Form Dialog of 7  attributes is generating utterances in scale of 1200 to 1400 in luis for the form intent

## Browser

- [ ] Chrome

## OS

- [ ] Windows

## To Reproduce

1. Go to Form Dialog in composer
2. Either import or create attributes 5 to 6
3. Generate Form Dialog, Run the Dialog, have luis connectivity
4. It generates 1000 +  of intents.
Any solution to restrict this to a manageable state

**Comment by chrimc62** [comment]
This is by design--the utterances are auto-generated so that your bot has all of the functionality required to support add/remove/cancel/help/show.  If you removed the utterances the functionality would no longer work.  @aparnaji  is there a reason that the number of utterances is causing you problems?  If so, please reply and reopen the issue.

**Comment by aparnaji** [comment]
I believe too many might lead into management issues.I will check the commenting option.  Also coming to entities , sometime my dialog fails (luis ) saying it crosses 330 entities. Are there any published best practices for usage of form dialogs
