### ISSUE TITLE
QnA maker dialog fails when adding strict filter

### ISSUE THREAD

**Issue by gary-x0pa** [microsoft/BotFramework-Composer#6895]
## Describe the bug

QnA maker returns `Response status code does not indicate success: 400 (Bad Request).` When strict filters are set. 
However when isTest is set to true this error does not occur. 

## Version

latest 1.4.1.

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create QnA maker dialog
2. Add strict filter
3. Trigger QnA dialog
4.  `Response status code does not indicate success: 400 (Bad Request).` 

## Expected behavior

Returns answer from QnA maker.

## Additional context

My resource group of the chat bot is different from the qna resource group. Im also running bot composer as a tenant in azure. Can anyone explain what isTest does and why it 'solves' the problem?

**Comment by anusharavindrar** [comment]
@gary-x0pa,  in case of large KBs, it is always advised to use automated testing with the generateAnswer API and the isTest body property, which queries the test knowledge base instead of the published knowledge base. So when you use  `"isTest": true` , then you can can target the test version of the knowledge base and by using `"isTest":false`,  you can search through the published kb.

Can you elaborate more on what you mean by "running the botframework composer as a tenant in azure"?

**Comment by gary-x0pa** [comment]
Ah i think i see what you mean. I forgot to publish the kb after making some changes.
