### ISSUE TITLE
Create new KB lists language but does not allow to change it?

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7084]
When creating a new KB, the 1st wizard page asks the user to create a name and type the URL for the KB source.
Why does it also lists the language, but there is no pption to change the language. If EN (US) is default, and cannot be changed in this page, the info is noise and should not be shown.

<img width="274" alt="KB Source and name EN-US" src="https://user-images.githubusercontent.com/48503434/115160931-a372c380-a04f-11eb-8c03-b104ec3bc25a.png">

**Comment by vivekkshankar** [comment]
@mareekuh The language name here is trying to reinforce that the URL/content will need to be in the same langauge for it to work.
The same UI also scales to showing more locales if the user is creating a multi-lang bot like so.

![image](https://user-images.githubusercontent.com/67671676/116598173-60301480-a8db-11eb-875e-7a4ecb2c4d35.png)

Reason for this experience:
Due to limitations in the way QnA content ingestion works - QnA maker needs to be told the language associated with a URL that it is creating the KB from. So multiple locales will need multiple urls uploaded. this is an big expeirence gap but the UI here is trying to help the user understand that content needs to be mapped to locale.
