### ISSUE TITLE
"Create a skill in your bot" should be renamed to "Add a new skill"

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#7115]
## Describe the bug
When you have an existing bot project open and you go through the flow to create a new skill, the title of the dialog we display is "Create a skill in your bot". We don't create anything in a bot.  We are actually adding a new skill to a bot projects.  

Using Visual Studio as a guild, that use very simple language which would equate to "Add a new skill" or if we love the verb create, calling it "Create a new skill" would work as well.

## Version
Version:  1.4.0-nightly.236490.3735dd3
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch Composer
2. Open an existing bot project
3. From the main authoring screen, click the "+ Add" menu item at the top of the project window
4. Click the "Create a new skill" menu item, this will launch the dialog of I referring to
5. Note the title of that modal.

## Expected behavior
A more simplified title that more accurately represents the action and purpose of the modal

## Screenshots
<img width="984" alt="Screen Shot 2021-04-19 at 1 43 30 PM" src="https://user-images.githubusercontent.com/733559/115300788-3d507400-a115-11eb-811a-4ca8cbf1f4f5.png">

**Comment by emivers8** [comment]
I think "Add a new skill" is good--consistent with the button that got them in the modal.

**Comment by mewa1024** [comment]
(Adding @vivekkshankar since he's working on the UX for the skills flows).

But can we just reuse the modal from the "+ New" (New project). It has the conveniently generic header of "Select a template":
![image](https://user-images.githubusercontent.com/39317542/115311553-ac819480-a124-11eb-8d31-860cc41d0311.png)

**Comment by mewa1024** [comment]
related question, after the template picker modal, Composer shows the "Create a bot project" modal:
![image](https://user-images.githubusercontent.com/39317542/115314606-67f8f780-a12a-11eb-907f-087702afb7ef.png)

which creates a new bot **_project_** rather than just a bot. Is that intentional?

I got an error, so I don't know if this is the intended behavior, but the folders appear in my MRU list (bot project within the bot project is highlighted):

![image](https://user-images.githubusercontent.com/39317542/115314793-c2925380-a12a-11eb-8212-94393fbf34ec.png)

I tried this on Version:  1.4.0-nightly.236875.b9e46c2

**Comment by mewa1024** [comment]
@clearab do you know if the intended behavior for creating a new skill/bot is to create a bot project?

**Comment by emivers8** [comment]
Hmm, also, should you really be able to add an Enterprise skill to an Enterprise project, for example? I understand not wanting to be overly restrictive if people want to do weird stuff, but this doesn't feel like it's _guiding_ me to selecting an appropriate template choice for a skill.

**Comment by mareekuh** [comment]
+1 on @mewa1024 's suggestion. 
Any dialog or modal should capture what the user is looking at or supposed to do.
The 2nd line can add further content or more detailed instructions.

**Comment by clearab** [comment]
Some thoughts and responses:

- The "Create a bot project" modal should be something like "Select your bot details" or something - what it is creating is dependent upon the template you select. You may be creating a bot and a new bot project, you may be creating multiple bots and adding them to a new bot project, or you may be creating a new bot and adding it to an existing bot project.
- The Add a skill flow needs to not be displaying the Enterprise Assistant template, as that creates multiple bots (unless we want to allow this, with skill nesting in a bot project, I'm fairly certain the current format of the .botproj file prevents this)
    - Ancillary to this, whatever decision is applied here needs to work for any template that comes with multiple bots, including potentially 3rd party templates.
- Currently, you aren't adding a skill, you're just creating a new bot in your bot project. Not sure if the new skill flows change this behavior, but saying "add a skill" is misleading currently (@darrenj may want to comment)

**Comment by mewa1024** [comment]
> * Currently, you aren't adding a skill, you're just creating a new bot in your bot project. Not sure if the new skill flows change this behavior, but saying "add a skill" is misleading currently (@darrenj may want to comment)

@clearab if I understand you correctly, the intended experience should be to allow users to just create a new bot in your existing bot project? In 1.4.0-nightly.236875.b9e46c2, it looks like we are doing the opposite--we create a new bot projec and don't provide any way to create just a bot in your existing project.

This is what I got when I created a blank bot (empty_0419) and added a new blank bot as a skill to it (emptyskill2). Composer created a emptyskill2 project within the empty_0419 project instead of providing an option to create just the skill:
![image](https://user-images.githubusercontent.com/39317542/115323270-a8fa0780-a13c-11eb-95d8-ad38fd38f2ed.png)

**Comment by cwhitten** [comment]
It seems that a sensible solution here would be for the Creation UX to offer including a skill manifest with the generated assets. It should feasibly layer into any existing template, beyond the complex template like Enterprise Assistant for reasons outside the scope of this discussion.

This is the right northstar aim as well. We want users to be authoring and leveraging skill manifests when authoring local skills as well as working with remote skills.

**Comment by cwhitten** [comment]
Posting @mewa1024's comment here:

Summary: in the current build of Composer, we have 3 options for adding skills: (1) "Add new skill, (2) "Connect to local skill", (3) Connect to remote skill". We are combining 1 and 2 into one menu, with the fork between new local skill/bot or existing local skill/bot moved into the flow:

Choose option to "Add bot"
Choose the bot, then

Select an existing bot: DONE WITH THIS FLOW, or
Choose to create a new bot: we select the blank bot (not shown in the UI), Composer shows a modal to provide name, description, runtime type and location of the new bot (same as the second modal in the Creation flow)

The UI is just iterations of the same steps--the only difference is the prominence of the ability to create a new bot while in the flow of adding a bot to your project.

**Comment by mewa1024** [comment]
Option C: [https://www.figma.com/file/4kfahZUjBdrxdDGZih7PVP/Composer-1.5-E2E-flows?node-id=802%3A53854](url)

![image](https://user-images.githubusercontent.com/39317542/116284138-96d22780-a741-11eb-9a28-c4e22a00ff2a.png)

**Comment by mewa1024** [comment]
Just want to clarify, are when user goes through the of "Add bot > Create a new bot" are we creating this for them?
![image](https://user-images.githubusercontent.com/39317542/116292754-e8cb7b00-a74a-11eb-9fce-e67af106f116.png)

or just the stuff selected here:
![image](https://user-images.githubusercontent.com/39317542/116292869-0ef11b00-a74b-11eb-9d0f-3b5e77afcb53.png)

**Comment by pavolum** [comment]
@mewa1024 the first one

**Comment by mewa1024** [comment]
Thanks! that's what I thought, but just wanted to check.
