### ISSUE TITLE
Already added a LUIS Key. What does "Get LUIS keys" do? Misleading. 

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7129]
## Describe the bug

I've already added the LUIS key to my app. The key shows up and all is "as-expected". 

There's still a "Get LUIS keys" button, that I can click. What does this do? 
![image](https://user-images.githubusercontent.com/1165321/115332936-a05dfd00-a14d-11eb-8fad-33b5abc02a60.png)

Clicking this, a new LUIS resource is created, but it's not tracked in the UI. 

I would expect a more deliberate management around LUIS resources. Probably preventing me from clicking this button unless I've cleared out / delete the existing resource.

## Version
Version:  1.4.0-nightly.236875.b9e46c2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

**Comment by mewa1024** [comment]
@emivers8, I think "Get LUIS key" might be correct, but what might be confusing is this line:
![image](https://user-images.githubusercontent.com/39317542/115338995-cdfc7380-a158-11eb-83fb-0481ff8aed69.png)

"How would you like to provision this resource?" implies that you only have the choice of creating a LUIS resource rather than selecting one you already have. Remove that line?

**Comment by emivers8** [comment]
Yeah, that copy is incorrect. These modals just got a flow update so they need a more thorough copy pass. I'll get that on the list.

Once the keys are in place we could update the buttons to say "Edit LUIS keys". (I think that's what the original designs had.) Not sure how much effort that is.

**Comment by mewa1024** [comment]
button now says "Set up Language Understanding".
