### ISSUE TITLE
Authoring key incorrectly used for endpoint calls

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7146]
## Describe the bug

When selecting a LUIS key in Composer this is purely retrieving the authoring key and not enabling me to select an endpoint key. This has been raised a few times and the (old) composer behaviour of using Authoring key for endpoint (prediction) calls is not correct. Whilst it works, it has a limited quota and will quickly run out of quota meaning the developers Bot stops working which is hard to diagnose and root of many a developer issues today. 1000 calls to the key are allowed per month, with LUIS being run on every turn these days it doesn't take long to hit it. 

## Version

1.4.0-nightly.237101

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create new empty bot
2. Add LUIS intent/trigger
3. From rocket ship menu select an existing LUIS resource
4. Observe that LUIS authoring key is set and endpoint key is not.

## Expected behavior

Selection of an endpoint key as well as authoring. Ensuring we give the developer a recommended, best practice configuration out of the box not something setting them up for failure.

**Comment by Dewain27** [comment]
This should add a prediction key to what we provision in LUIS from getting started with a F0 sku.

You will need to run this command to be able to give the permissions to allow the key to have the proper rights:
az account get-access-token --output json

bf luis:application:assignazureaccount `
    --accountName <luisAccountName> `
    --resourceGroup <resourceGroup> `
    --armToken <az access token> `
    --azureSubscriptionId <az account id> `
    --appId <luis app id>`
    --endpoint <luis endpoint> `
    --subscriptionKey <luis authoring key>

**Comment by benbrown** [comment]
This has been a known issue for a while, and I knew there was a reason it had not yet been addressed.  It took a little sleuthing, but I figured it out:

In order to do this key assignment process, we will need to require the user to login to Azure first during the "start bot" process. In addition, we will need to capture additional information about the LUIS endpoint key resource during provisioning. 
The actual resource name, in addition to the key, is required to do the assignment. We do not currently have a place in the settings for this value.

It is not trivial to add authentication to this flow. This is another strong indicator that we need to invest in an all up "login to composer" strategy.

**Comment by Dewain27** [comment]
Blocked by #7166

**Comment by cwhitten** [comment]
Eng. is recommending a warning in the settings page and a rocket menu update

**Comment by benbrown** [comment]
OK the r13 solution for this is in #7430 - a warning appearing on the settings page, and a recommendation to publish the bot to Azure if the limit is reached.
