### ISSUE TITLE
Error when migration an old bot with custom runtime and custom schema

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#7398]
## Describe the bug

Steps to reproduce:

1. Create a new EchoBot with composer 1.4.0.
2. Enable custom runtime with custom action. 
3. Open the EchoBot with composer 2.0.0
4. See this error
![image](https://user-images.githubusercontent.com/32191031/116191060-42897080-a75e-11eb-9464-e784351b1ce2.png)

![migration1](https://user-images.githubusercontent.com/32191031/116191669-4ff32a80-a75f-11eb-9dff-eebcd3968c81.gif)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by boydc2014** [comment]
This looks like not "customized action specific", seems like some file operations are not correct causing a bot
 that have a runtime folder will fail.

**Comment by benbrown** [comment]
This is due to the lack of support for the sdk.schema and sdk.uischema files in the botStructure.ts file.  This causes them to be improperly renamed, and the uischema causes the error because it is attempting to rename it to the name of the parent folder.

In that project, there handlers for "dialogSchema" which I am not familiar with, and this is causing it to catch the sdk.schema file and rename it to dialogs/sdk/sdk.dialog.schema

**Comment by benbrown** [comment]
Fixed in this commit: https://github.com/microsoft/BotFramework-Composer/pull/6526/commits/fe68602331886074dd655c03066373c2cb68a009

@luhan2017  can you please continue to verify?

**Comment by sgellock** [comment]
Shiproom - remaining issues are being tracked in #7373
