### ISSUE TITLE
Can't start bot after installing any packages 

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#7403]
## Describe the bug

Can't start my bot after install any packages like Microsoft.Bot.Components.Welcome dialog. 
It complains couldn't load dll, but actually those packages aren't even including dlls. 
Something must be wrong about the project setup.  

![image](https://user-images.githubusercontent.com/3829387/116228474-ec312780-a787-11eb-84d2-cc376333705d.png)

## Version

lastest main 4/27

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an empty bot
2. Install Microsoft.Bot.Compontents.Welcome or HelpAndCancel, or Graph
3. Start bot

**Comment by benbrown** [comment]
This is due a recent change where we used the tag `msbot-component` to determine which components should be added to the `component` key in the settings upon install.

This inadvertently included the content-only packages like Welcome and HelpAndCancel.

I will fix this momentarily - the resolution is to use more specific tags (msbot-trigger, msbot-action, etc) rather than the catch-all msbot-component.
