### ISSUE TITLE
New create flow telemetry events

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#7462]
Dewain has identified these additional telemetry events he would like to capture:

- [ ] * Track when the new bot dialog is opened
- [ ] * Track when the cancel button in the create flow is clicked
- [ ] * Track telemetry of Webapp vs Functions choice
- [ ] * Track telemetry of JS vs .NET choice
- [ ] * Track the success or failure status of new provision profiles.
- [ ] * Track the success or failure of publish attempts (with publish type pva or azure)
- [ ] * Maybe track the actual "GO" button in publish modal (only tracking toolbar button click)
- [ ] * Track click on "Need another template"
- [ ] * Track if user clicks the "take a tour" link in the "learning" tab of the rocket ship
- [ ] * Track if a user is creating a new resource group or using an existing resource group when  provisioning a new publishing profile

**Comment by sgellock** [comment]
Shiproom - approved

**Comment by pavolum** [comment]
Dewain has identified these additional telemetry events he would like to capture:

- [ ] * Track when the new bot dialog is opened;` 
  - `TelemetryClient.track('NewBotDialogOpened', {
                isSkillBot: boolean,
                fromAbsHandoff: boolean,
              }); `
- [ ] * Track when the creation modal is closed due to user clicking cancel or clicking outside the modal
  -     TelemetryClient.track('CreationCancelled');
- [ ] * Track telemetry of Webapp vs Functions choice
- [ ] * Track telemetry of JS vs .NET choice
  - `      TelemetryClient.track('creationExecuted', {
        runtimeChoice: dataToSubmit?.runtimeType,
        runtimeLanguage: dataToSubmit?.runtimeLanguage as FeedType,
        isPva: isImported,
        isAbs: !!dataToSubmit?.source,
      });`
- [ ] * Track the success or failure status of new provision profiles.
- [ ] * Track the success or failure of publish attempts (with publish type pva or azure)
- [ ] * Maybe track the actual "GO" button in publish modal (only tracking toolbar button click)
- [ ] * Track click on "Need another template"
- [ ] * Track if user clicks the "take a tour" link in the "learning" tab of the rocket ship
- [ ] * Track if a user is creating a new resource group or using an existing resource group when  provisioning a new publishing profile
