### ISSUE TITLE
Bot Composer is not waiting for action to be completed in adaptive cards

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#7586]
## Version

![image](https://user-images.githubusercontent.com/26645750/116963528-9df4ba80-ac98-11eb-8b8f-f44e9a53a6a7.png)

## Browser

- [ ] Chrome

- [ ] Edge

## OS

- [ ] Windows

## To Reproduce

1. Create a adaptive card with four buttons, and button action (arranged in clumn sets)
2. call the card from "Send Response" in Bot Dialog
3. The Bot is not waiting for response from adaptive card buttons and it is moving to subsequent steps

## Expected behavior

Expecting the Bot to wait and take response before moving to next step 
(In .NET framework bot, we have await reply option, anything like this here)

**Comment by peta** [comment]
Same here, can confirm.

**Comment by dmvtech** [comment]
Hi @aparnaji 

Are you doing a `Send a response` action only, or is it part of a prompt? It needs to be part of a prompt (`Ask a Question`) for the bot to do anything with response from the user (using the card).
https://docs.microsoft.com/en-us/composer/concept-memory#set-properties-with-prompts

If that's not it, I might need a bit more info to understand/troubleshoot. Are you able to share your adaptive card or your bot? (either the bot in a repo, or at least a screenshot of the dialog or trigger)

**Comment by peta** [comment]
Hello @dmvtech , 
Thanks four your reply. 
You are right, we can provide an Adaptive Card as attachment to `Ask a question` response activity, but this does mean the user is, in addition to entering the Adaptive Card form and pressing the according `Action.Submit` button, prompted for user input yet a second time (Text, Number, Confirmation asf.). And from a conversational design perspective, this would be slightly distracting.
 
I think this issue is related to #1820  which was raised almost 1,5years ago and where the actual subject matter was already the same: How to use Adaptive Cards for gathering structured user input in an intuitive way (both, for bot authors and bot endusers).

Any ideas?

Peter

**Comment by iMicknl** [comment]
@peta, I faced a similar issue lately and I was able to resolve it using the 'Ask a Question -> Text'.

If you add an id to the Input fields of your Adaptive Card, you can read them using @id. So for `"id": "age"` you would use @age. The only downside of the User Input (Text) in Composer is that you can only set one value, but you could save the values to properties in the next step.

In the end, you could also add multiple validation rules, so that it will make sure that all input fields are present. `=!empty(@age)` etc. And if you have multiple buttons, you can capture the id or data fields of these buttons as well.

Does this help you in the right direction?

**Comment by aparnaji** [comment]
Thanks, This helps,Ask a Question -> Text helped me with both Form type and button type adaptive , and Carousel , I tried with separate regex trigger., Other references that I used for help are #1820 which @peta pointed out.
Also issue #1820 suggested that there is enhancement planned for adaptive cards which is supposed to come up by March 2020. Composer team , please let know if any inputs on that

**Comment by dmvtech** [comment]
Hi @aparnaji Did you get it working using the suggestions above and from the other issue? At this time there are not further enhancements planned for this scenario that are not already there.

**Comment by aparnaji** [comment]
Yes it helped, Thanks

**Comment by dmvtech** [comment]
Great closing as resolved.
