### ISSUE TITLE
Node runtime telemetry doesn't generate InstanceId

### ISSUE THREAD

**Issue by Dan-Bai** [microsoft/BotFramework-Composer#7594]
I have been using InstanceId from WaterfallDialog style Bots to generate reporting and noticed that this ID is missing for AdaptiveDialog. Is there an equivalent ID I can use as substitute? If not, how could I implement this ID in my Node runtime?

**Comment by v-kydela** [comment]
Thank you for the post, @Dan-Bai 

As you've seen, adaptive dialogs work a bit differently from waterfall dialogs. If you'd like your adaptive dialogs to generate unique instance ID's, you could generate the ID in the first step of each dialog on a case-by-case basis or you could export the runtime and try writing code that does it automatically.

We do prefer to have how-to questions asked on [Stack Overflow](https://stackoverflow.com/questions/ask) instead of GitHub. This reaches a larger audience, allowing more people to possibly answer the question and more people to be helped by the answer. If you use the [`botframework`](https://stackoverflow.com/questions/tagged/botframework) tag then my team will be sure to see the question.

I'll go ahead and close this here.
