### ISSUE TITLE
Functions bots do not work when running locally (LUIS, QNA and other settings are not properly received)

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7691]
## Describe the bug
Dotnet function bots throw an invalid LUIS subscription key error when trying to call LUIS

## Version
Version:  2.0.0-nightly.243234.8264ac4
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

**Updated**
1. create empty dotnet bot
2. add and wire up echo intent
3. create provisioning profile and publish bot (step that was missing)
4. start bot
5. send intent message

## Expected behavior
The call should go through

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/117376418-efae6800-ae85-11eb-8f3a-3ed86b316778.png)

## Additional context
The fix for this issue is probably similar to the fix for [this issue](https://github.com/microsoft/BotFramework-Composer/issues/7602) since the errors are fairly similar.

**Comment by sgellock** [comment]
Shiproom - I am not able to repo this with the currently nightly.  let's get a second opinion to see if we an repro the issue

**Comment by sgellock** [comment]
Shiproom - @benbrown will try and repro this a.m.

**Comment by Virtual-Josh** [comment]
ahh slightly modified set of setps

1. create empty dotnet bot
2. add and wire up echo intent
3. **create provisioning profile and publish bot** (step that was missing)
4. start bot
5. send intent message

This repos with today's build. 

![image](https://user-images.githubusercontent.com/50158775/117491171-b2e57e00-af24-11eb-98e6-bb44b04254f5.png)

**Comment by Virtual-Josh** [comment]
As one additional piece, if you test the bot in azure the bot doesn't respond if you try to invoke LUIS, but does respond if it stays local. The weird thing is web chat doesn't produce the `invalid luis subscription` error that happens locally.
![image](https://user-images.githubusercontent.com/50158775/117492786-f214ce80-af26-11eb-9098-ed9032f5832e.png)

**Comment by benbrown** [comment]
I *CAN* reproduce this.

**Comment by benbrown** [comment]
When running locally, Composer passes sensitive settings like the LUIS endpoint key, QNA endpoint key, and Microsoft App Password via command line arguments to the runtime, for example: (pseudocode) `dotnet start mybot.csproj --luis:endpoint=123`

see code here: https://github.com/microsoft/BotFramework-Composer/blob/0c914b22f1dc7d3c54357b423a1f32dece7b8393/extensions/localPublish/src/index.ts#L409

This works fine for normal dotnet apps, that accept these parameters and use them.

However, the `func` runtime does NOT pass these parameters into the running app, and thus they are missing and the app errors.

The proposed workaround is that developers using the func runtime locally create an `appsettings.development.json` file with these values.

**Comment by Virtual-Josh** [comment]
For an additional piece of context, a similar issue is happening for Node function bots. The error presented is different, but initial investigation would suggest it's ultimately pointing towards the same issue of the app settings being inaccurate.

![image](https://user-images.githubusercontent.com/50158775/117512998-9443af00-af45-11eb-92db-bb75c5d99d6d.png)

**Comment by peterinnesmsft** [comment]
@sgellock @tracyboehrer per request, updating issue with investigation findings. I have identified a potential solution to supporting this in Composer. @benbrown @joshgummersall please review the below:

---

The Azure Functions runtime by default makes use of environment variables for the purposes of supplying configuration to the application. For local development using the Azure Functions CLI, `local.settings.json` is provided as a means of providing environment variables when running locally.

The CLI provides an API, `func settings`, with operations for adding and removing environment variables to this file without having to manually manipulate it.

Following the repro steps above, I was able to successfully get my bot running by issuing the following commands manually when in the same directory containing `local.settings.json`:

```
PS C:\Users\peinnes\source\repos\Empty\Empty\bin\Debug\netcoreapp3.1> func settings add MicrosoftAppPassword ___
PS C:\Users\peinnes\source\repos\Empty\Empty\bin\Debug\netcoreapp3.1> func settings add luis:endpointKey ___
PS C:\Users\peinnes\source\repos\Empty\Empty\bin\Debug\netcoreapp3.1> func settings add qna:endpointKey ___
PS C:\Users\peinnes\source\repos\Empty\Empty\bin\Debug\netcoreapp3.1> func settings add SkillHostEndpoint http://127.0.0.1:3980/api/skills
```

For sanity, here is web chat showing successful dialog for .NET Functions in Composer:

![image](https://user-images.githubusercontent.com/53846082/117522720-c961f880-af69-11eb-9c4f-98ce437c9feb.png)

...and here is JS Functions in Composer:

![image](https://user-images.githubusercontent.com/53846082/117522792-1c3bb000-af6a-11eb-98bb-847628879869.png)

To that extent, making the assumption that it has access to the corresponding secrets, I believe that we can update the runtime extensions logic in Composer to simply invoke the `func settings add` API to register these settings in `local.settings.json`. This file is already scaffolded by the templates. Additionally, running add multiple times will override a setting if it is already specified.

Finally, as last sanity check, per the Azure Functions [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash#local-settings-file), values in local.settings.json will only apply when being run locally - in other words, this should not clobber the contents of our appsettings.json values in a deployed context.

**N.B.:** For .NET, since the app runs from the context of the build output directory (`/bin/Debug/netcoreapp3.1`), the `local.settings.json` in the project root would need to be updated **BEFORE** executing `dotnet build` to ensure that the values are in place of the executing location.

**Comment by sgellock** [comment]
Shiproom - let's see what a PR would look like and assess for R13

**Comment by sgellock** [comment]
Shiproom - approved - functions with services is P0
