### ISSUE TITLE
[MCS-DE-GO] Bug on LUIS results in child dialog

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#7696]
When having a conversation within a child dialog, the UserInput is processed by the child dialog LUIS model as well as the root dialog LUIS model.

The "turn.recognized.intent" does not contain the highest scoring value but actually the result from the root dialog LUIS model.

Also it seems that the child dialog LUIS model is always called twice.

It appears as if only the last result from the LUIS calls is stored and not all results are considered when evaluating which has the highest score.

Is there a way to configure this via the Bot Design settings or the appsettings?

Here the details from Emulator:

![image](https://user-images.githubusercontent.com/31212469/117434359-de6c6680-af2c-11eb-8125-5dda91e83a4c.png)

Child dialog 1st LUIS call (1st. LUIS result):
```json
{
  "recognizerResult": {
    "alteredText": null,
    "entities": {},
    "intents": {
      "Intent_ConfirmationUnsubscribed": {
        "score": 0.96476275
      }
    },
    "text": "ist abgemeldet"
  }
}
```

Child dialog 2nd LUIS call (2nd LUIS result):
```json
{
  "recognizerResult": {
    "alteredText": null,
    "entities": {},
    "intents": {
      "Intent_ConfirmationUnsubscribed": {
        "score": 0.96476275
      }
    },
    "text": "ist abgemeldet"
  }
}
```

Root dialog LUIS result (3rd LUIS result):
```json
{
  "recognizerResult": {
    "alteredText": null,
    "entities": {},
    "intents": {
      "Intent_None": {
        "score": 0.31199825
      }
    },
    "text": "ist abgemeldet"
  }
}
```

Result in ${turn.recognized} output:
![image](https://user-images.githubusercontent.com/31212469/117434897-841fd580-af2d-11eb-8ef9-a8137e6e3d7d.png)

**There is a second issue. The child dialog LUIS model is always queried twice which does not make sense.**

**I would like to add that there should be more best practice guidance on how to best configure and train LUIS Models. Having a separate LUIS Model per Dialog is decreasing overall performance and increasing LUIS cost plus adds complexity to the Bot maintenance.**

@joaollq @goergenj @garypretty @benbrown @cwhitten

**Comment by goergenj** [comment]
@garypretty @benbrown @cwhitten Any update on this?

**Comment by tonyanziano** [comment]
@taicchoumsft can you take a look at this / comment?

**Comment by taicchoumsft** [comment]
Hi @goergenj , I think the root dialog is being consulted because you've got the `allow interruptions` flag on for this user input, and there is no trigger that was hit in the child dialog.  There are hopefully some helpful details [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-dialog-interruptions?view=azure-bot-service-4.0#handling-interruptions-globally).

So if you create a trigger in the child dialog called `Intent_ConfirmationUnsubscribed`, and fill it out with the same lu data from the userinput, this will prevent the root dialog from being consulted when this trigger is hit. Inside the new `Intent_ConfirmationUnsubscribed` trigger in the child dialog, `$turn.recognized} is populated correctly with the correct intent.

I'm investigating the child recognizer being consulted twice, I can repro this always when using interruptions.  I'll need some time to trace the events in the SDK to see why we're doing this.

**Comment by goergenj** [comment]
@taicchoumsft If I get you correctly this would mean I need to maintain manually in all child LUIS files all the Intents from the main dialog LUIS as well. This is not a feasible approach for maintaining and extending the Bots.

If that is the case, the composer should do an automatic reference to the root LU-File to automatically add these utterances in the child LU-Files similar to how it is done with the "common.lg".

Further we do not want to initiate a trigger as an interruption but simply access and evaluate the "turn.recognized.intent" result properly within the dialog. Since this is the result in the Bot memory it would be more logical in my opinion, if this object has the highest scoring result from all LUIS inquiries so that you can work with a proper LUIS-model-hierarchy without creating double maintenance on the LU-file content.

**Comment by taicchoumsft** [comment]
Hi @goergenj , thanks for the feedback here.  Does not using interruptions work for this particular dialog?  Not using interruptions here simultaneously solves the unexpected "turn.recognized.intent" coming from the root dialog, and also doesn't consult the root dialog at all, no wasted traffic. 

@Stevenic , do you have some feedback for us here on what we can do? Thanks Steve.

**Comment by goergenj** [comment]
@taicchoumsft Let's discuss in our call on Friday. Not using interruptions would work but that is not the design we need as we need interruptions in general.

Thanks for opening a separate issue for the double hit in the child recognizers. Will be easier to track these separately.

**Comment by taicchoumsft** [comment]
Hey @goergenj , the double recognizer hit to LUIS (specifically LUIS) has been fixed by @cosmicshuai and @boydc2014  [here](https://github.com/microsoft/botbuilder-dotnet/issues/5593).  Thanks for reporting this and helping us to identify how it repro'd.

There is now a "Best Practices" [guide](https://docs.microsoft.com/en-us/composer/concept-best-practices?tabs=v2x), but it does not cover the really advanced scenarios you were looking for (None/Unknown,  consultation mechanism, trigger processing order etc.).  There are people working on this, some based on some of the discussion we had.  

Thanks @goergenj .

**Comment by goergenj** [comment]
@taicchoumsft Thanks for the update.

Regarding the local interruption handling we now adopted the guidance to add local triggers without actions to make sure the interruptions are handled correctly although it's not optimal from a maintenance perspective but it seems to work.

Regarding the best practices we have some working designs so we are good for now. Would be good to align on these however. @garypretty We can discuss this in our regular sync.

**Comment by taicchoumsft** [comment]
Closing this ticket, feel free to reopen if something still needs to be addressed.
