### ISSUE TITLE
[UI bug] [Export as skill] Confirm skill endpoints is blank when publish profile is imported from existing

### ISSUE THREAD

**Issue by vivekkshankar** [microsoft/BotFramework-Composer#7751]
Export as a skill->Create a new publish profile-> import from existing

Issue 1:
The confirm skill end point UI turns up blank, 
![image](https://user-images.githubusercontent.com/67671676/117869166-500b2400-b24f-11eb-9d09-addad531c357.png)

Issue 2 : 
Back button should take the user back to the publishing step but instead it takes the user back to the allowed caller selection

**Comment by luhan2017** [comment]
@vivekkshankar, 
For issue1, are you importing a valid publishing profile? If the publish profile is not valid, it would be shown in the dropdown.  Should we just show every publish profile in the dropdown and mark the invalid ones with a warning sign? Maybe we can have a sync offline to talk about the design.

For issue2, I am afraid it is not easy to do that. Because the new provision wizard is a branching process. After It is done is returns to the main process of the creating skill manifest flow. So in the main flow the Back button should go to the AllowCaller page.

**Comment by vivekkshankar** [comment]
For issue 1 - We should not allow the user to proceed with invalid publish profile.
Also, I am seeing this blank select end point URL screen momentarily even if i use a correct publishing proifle..

**Comment by hatpick** [comment]
@vivekkshankar would you please comment on the UX of the associated PR that addresses this issue?

**Comment by luhan2017** [comment]
@vivekkshankar , do you think we should mark this issue as P0 and R13? we had a PR ready as we discussed.
The PR is to give an error and disable the generate and publish button. There will be a follow up PR for R14 to direct user to create another publish profile or select another valid one if any.

**Comment by sgellock** [comment]
Shiproom - let's review the PR and see if we want to recall Composer to take this.  regardless, if we decide to take this we need to merge and product a new nightly immediately thereafter.

**Comment by sgellock** [comment]
Shiproom - moved out of R13.
