### ISSUE TITLE
Skill manifest urls aren't actually published

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7776]
## Describe the bug
Might be related to/a dupe of #7655, but the steps are different.

~Exporting bots as skills doesn't actually create the manifest.~
The generated skill manifest that is included in the deployment isn't being served.

## Version
Version:  2.0.0-nightly.244572.8406071
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an empty dotnet function bot
2. Create an publishing profile
3. Add a echo dialog and trigger
4. export as a skill
5. Only select the echo dialog and trigger
6.. Enter the manifest url into the browser

## Expected behavior
This should work

## Additional context
In the previous ticket the issue was exporting as a skill before creating the manifest. Here I created the profile before publishing. Also I should add only my dotnet web app skill works. Dotnet function, node wa, and node function don't work. Not sure if that's the source of the issue, but maybe.

Here's all of the manifest urls I'm using

https://DWAEcho512.azurewebsites.net/manifests/DotnetWAEcho512-2-1-manifest.json (works)
https://DFEcho512.azurewebsites.net/manifests/DotnetFunction512-2-1-manifest.json (currently works with work around described below)
https://NWAEcho512.azurewebsites.net/manifests/NodeWA512-2-1-manifest.json
https://NFEcho512.azurewebsites.net/manifests/NodeFunction512-2-1-manifest.json (currently works with the work around described below)

**Comment by cwhitten** [comment]
@Virtual-Josh once you author the manifest, are you publishing the bot again that should include the new file?

**Comment by Virtual-Josh** [comment]
Previously I probably provisioned and exported before I published the bot. However publishing the bot then re-exporting as a skill doesn't resolve the issue. 

However Peter and I found the source of 2 of the 3 issues. For dotnet functions the main application directory has a `wwwroot` folder (this is the 2nd wwwroot folder starting from the top). If you rename this `wwwroot` folder to `www` then the manifest pulls up in the browser as expected.

Node functions have the same issue, however you rename the `wwwroot` folder to `public` and then it works.

However this fix doesn't work for node web apps. We tired `public` and `www` and neither works. According to Peter there's 2 ways to fix this. Composer can handle this, or the generators can. @peterinnesmsft  can you chime in here about the differences here? 

This provides a manual work around for testing deployed skills in 3 of the 4 scenarios. However somethings to be done about this.

**Comment by cwhitten** [comment]
I had a conversation with @joshgummersall on April 13th around mounting the `public` folder in the node environment, but mapping `wwwroot` into it. Josh should weigh in here as well

**Comment by peterinnesmsft** [comment]
Thanks @Virtual-Josh. From what I gather, the manifests are being placed into the `wwwroot/manifests/` dir at the root of the publish folder.

From my understanding of the world, `wwwroot` is an ASP.NET construct that is used as the default location from which to serve static file content. So this is why it works when deploying .NET Core Web App-based bots.

Functions as a whole is a very different kettle of fish. When we deploy any variant of Azure Functions, we are not really deploying an app - we are deploying static content (in the case of .NET, this also includes dlls and such) into the underlying Functions host application that is running on the provisioned resource. If you open Kudu console, you'll see that the published zip's contents are all placed in `site/wwwroot`.

When the .NET Functions integration was done, we specifically opted against searching in `wwwroot` due to concerns that this may cause confusion (since you'd essentially be looking at `site/wwwroot/wwwroot`), and so opted for `www` instead. This can be adjusted as it is defined in the trigger implementation. The same explanation is also applicable for JS Functions, but instead is looking for `public`. I think it should be aligned between .NET and JS Functions implementation to be the same, but I would still opt against going with `wwwroot` due to the nature of Azure Functions as a whole.

On the JS Web App side of things, it is also looking for the `public` dir in the application root. @joshgummersall may be able to provide context on the precedence behind this, but again, I think it is valid for this to not be `wwwroot` on the basis that it's an ASP.NET concept.

---

To the point above, there are two ways this can go I believe:

1) We can adjust the Composer publishing logic to place the manifests in a different directory that is dependent upon the runtime selected for the bot; or
2) We can update the .NET Functions and JS Functions generators, as well as JS SDK, to use `wwwroot`.

**Comment by GeoffCoxMSFT** [comment]
In deploy.ts the wwwroot is hard coded for skills starting at line 127.  We can certainly conditionally change the path based on the runtime if we know the right paths.  @luhan2017 added an updating of the skill manifest files post copy to set the host endpoint for the app to `https://${hostname}.azurewebsites.net/api/messages;`.  Does the host endpoint need to vary based on the runtime type (app vs. functions)?  

```
// COPY MANIFESTS TO wwwroot/manifests
// eslint-disable-next-line security/detect-non-literal-fs-filename
if (await project.fileStorage.exists(path.join(pathToArtifacts, 'manifests'))) {
  await copyDir(
    path.join(pathToArtifacts, 'manifests'),
    project.fileStorage,
    path.join(pathToArtifacts, 'wwwroot', 'manifests'),
    project.fileStorage
  );
  // Update skill endpoint url in skill manifest.
  await this.updateSkillSettings(
    profileName,
    hostname,
    settings.MicrosoftAppId,
    path.join(pathToArtifacts, 'wwwroot', 'manifests')
  );
}
```

**Comment by joshgummersall** [comment]
My suggestion is to encode the static directory in `appsettings.json` similar to how we encode the `start` command (i.e. `npm run dev` for node, `dotnet ...` for, well, .NET). Then, Composer could consume the setting. To me, this holds with our principle of extracting language-specific details outside of Composer and into the component templates.

If we decide to change this in the SDK(s), for JS it'll require a patch release (which we are prepping for as I type this, to be fair).

**Comment by peterinnesmsft** [comment]
> In deploy.ts the wwwroot is hard coded for skills starting at line 127. We can certainly conditionally change the path based on the runtime if we know the right paths. @luhan2017 added an updating of the skill manifest files post copy to set the host endpoint for the app to `https://${hostname}.azurewebsites.net/api/messages;`. Does the host endpoint need to vary based on the runtime type (app vs. functions)?
> 
> ```
> // COPY MANIFESTS TO wwwroot/manifests
> // eslint-disable-next-line security/detect-non-literal-fs-filename
> if (await project.fileStorage.exists(path.join(pathToArtifacts, 'manifests'))) {
>   await copyDir(
>     path.join(pathToArtifacts, 'manifests'),
>     project.fileStorage,
>     path.join(pathToArtifacts, 'wwwroot', 'manifests'),
>     project.fileStorage
>   );
>   // Update skill endpoint url in skill manifest.
>   await this.updateSkillSettings(
>     profileName,
>     hostname,
>     settings.MicrosoftAppId,
>     path.join(pathToArtifacts, 'wwwroot', 'manifests')
>   );
> }
> ```

The host part of the URI shouldn't need to vary at all, it's just the path in the request that essentially needs to take it into account.

@joshgummersall probably has the right idea of this coming from settings, but we can wait for shiproom's input.

**Comment by boydc2014** [comment]
Proposed one alternative in the email thread started by @cwhitten

**Comment by sgellock** [comment]
Shiproom - lets determine if wwwroot can be standardized across the languages and hosting environments, and if so, go with that option as a low right R13 fix.  We can open this up as a configurable option post R13 if necessary.

**Comment by joshgummersall** [comment]
https://github.com/microsoft/botbuilder-js/pull/3682

**Comment by sgellock** [comment]
Shiproom - connect with @Virtual-Josh to get a test matrix update

**Comment by sgellock** [comment]
Shiproom - RC14 of NBTs should have the last fix to enable JS built bots.  we need to validate that this morning

**Comment by sgellock** [comment]
Shiproom - RC14 of NBTs fixed this.  verified yesterday with a full test pass
