### ISSUE TITLE
Publish error

### ISSUE THREAD

**Issue by nathanvv** [microsoft/BotFramework-Composer#7783]
## Describe the bug

Running into the following error while publishing 
Exception during 'WindowsIntegratedAuthExchange' converted from Unexpected to InteractionRequired. Original context: 'Couldn't parse a windows transport endpoint from the MEX document'
Happens during both "Create new Azure resources" or "Import existing azure resource"

Started happened starting last week after updating to v1.4.1

## Version

![image](https://user-images.githubusercontent.com/11080029/118086427-949ada80-b389-11eb-8fc2-4245b31dcbc9.png)

## Browser

![image](https://user-images.githubusercontent.com/11080029/118086408-8cdb3600-b389-11eb-8aaf-d4dfe3b630d6.png)

## OS
- [ ] Windows

## Expected behavior

Expecting the composer to publish the project

## Screenshots

"Create new Azure resources"
![image](https://user-images.githubusercontent.com/11080029/118086630-e6436500-b389-11eb-8a39-9dc830cc0244.png)

 "Import existing azure resource"
![image](https://user-images.githubusercontent.com/11080029/118086656-ec394600-b389-11eb-9bca-7312974f97b6.png)

**Comment by tonyanziano** [comment]
I heard back from the OneAuth team and they said that this is a pretty standard error.

On the Composer side, we need to handle the `InteractionRequired` status of an auth response and try to sign the user in interactively. We _should_ have code that already does this, but it seems to be bypassed in this scenario.

**Comment by johnataylor** [comment]
@tonyanziano what are the next steps with this one. Seems like you think it is an issue in the product that needs fixing, can you clarify?

**Comment by tonyanziano** [comment]
@johnataylor correct, it is a Composer issue that needs to be fixed.

Inside the authentication flow that fetches an ARM token for a specific tenant, we need to handle an unsuccessful authentication request with the `InteractionRequired` status, and reprompt the user to sign-in interactively.

You can see an example of that same handling logic here: [Source](https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/electron-server/src/auth/oneAuthService.ts#L165)

We need to find an owner for this, because I am currently assigned on other R14 work. I might be able to get to it afterwards.

**Comment by srinaath** [comment]
We are trying to resolve this in R14.

**Comment by benbrown** [comment]
The fix for this has just merged into main!
