### ISSUE TITLE
No option to develop custom action in latest bot framework composer version

### ISSUE THREAD

**Issue by kundurmutt** [microsoft/BotFramework-Composer#7829]
The documentation@ https://docs.microsoft.com/en-us/composer/how-to-add-custom-action?tabs=csharp to created custom actions does not seem to  relate to or be relevant in the context of the latest bot framework composer v2.x - works for v1.4.1.
Could someone please guide or advise on how to develop custom actions for the latest version of composer. 
Thanks

**Comment by sgellock** [comment]
Shiproom - Big Dog, can you track

**Comment by dmvtech** [comment]
Hi @kundurmutt 

BotComponent (vs ComponentRegistration) are the new route for custom actions (in `2.0.x`). You can follow the directions [here][1]. The two things you will _likely_ have to change are:

 - Update/add a newer package for `Microsoft.Azure.KeyVault.Core`. I went with `3.0.5` for both projects.
 - Use `"components":[{"name":"MultiplyDialog"}]` instead of `"components":[{"name":"CustomAction.MultiplyDialog"}]`. 

On point #2, I was getting a build error (`FileNotFoundException: Could not load file or assembly 'CustomAction.MultiplyDialog`) and therefore did the above to resolve. Odd thing here is that once I was able to build in VS, then run and test in Composer, it's once again back to `CustomAction.MultiplyDialog`, but it works. Not sure what is going on there, please let me know if you get the same or have more findings.

My assumption is this documentation should make it's way to the Composer documentation once `2.0` is released, but @Kaiqb should be able to confirm.

  [1]: https://github.com/microsoft/botframework-components/blob/main/docs/extending-with-code.md

**Comment by kundurmutt** [comment]
Thank you all, for the revised guidance. Will give this a try.

**Comment by aparnaji** [comment]
Thanks, I tried and this worked with 2.0.X Composer, and  for components, it worked with  "components": [
      {
        "name": "CustomAction"
      }]

**Comment by kundurmutt** [comment]
Good to know.

**Comment by srinaath** [comment]
From my testing, It seems like the name of csproj file is the name to be added inside components array.
@peterinnesmsft Is this by design? Typically, we would look at the namespace or className right?
