### ISSUE TITLE
Node WA skill parents have a stack overflow exception when writing to stroage accounts

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7854]
## Describe the bug
Currently the parent bot throws circular JSON reference error when attempting to write bot state to storage when using skills. 

## Version
Version:  2.0.0-nightly.246099.8fa93
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a node web app bot with an echo trigger and dialog
2. create provision and skill manifest
3. create a node wa parent and provision (make sure you include cosmosdb in the provision)
4. update the appsettings of the parent to use cosmosDB 
5. Add the skill as a local bot and wire it up
6. Launch the bots and send a message to the parent to trigger the skill

## Expected behavior
Storage (CosmosDB and blob have been confirmed broken)

## Additional context
Josh G and I have already done some initial digging, here's what we know. 

It's unclear if the issue is in the SDK, Composer, Cosmos, skills specifically, or some combination of all of the above. It's less likely the issue is entirely with Cosmos since the odds that 0 customers are using JS and Cosmos is effectively 0%. 

Here's the error:

[onTurnError] unhandled error { TypeError: [Maximum nesting depth of 127 exceeded. This is most likely caused by recursive component dialogs. Try reworking your dialog code to make sure it does not keep dialogs on the stack that it's not using. For example, consider using replaceDialog instead of beginDialog.] Converting circular structure to JSONat JSON.stringify (<anonymous>)at javaScriptFriendlyJSONStringify (C:\home\site\wwwroot\node_modules\@azure\cosmos\dist\index.js:7250:17)at bodyFromData (C:\home\site\wwwroot\node_modules\@azure\cosmos\dist\index.js:7257:16)at C:\home\site\wwwroot\node_modules\@azure\cosmos\dist\index.js:7920:35at Generator.next (<anonymous>)at C:\home\site\wwwroot\node_modules\@azure\cosmos\node_modules\tslib\tslib.js:117:75at new Promise (<anonymous>)at Object.__awaiter (C:\home\site\wwwroot\node_modules\@azure\cosmos\node_modules\tslib\tslib.js:113:16)
at request (C:\home\site\wwwroot\node_modules\@azure\cosmos\dist\index.js:7918:18)at C:\home\site\wwwroot\node_modules\@azure\cosmos\dist\index.js:7220:20name: 'DialogContextError',message:'[Maximum nesting depth of 127 exceeded. This is most likely caused by recursive component dialogs. Try reworking your dialog code to make sure it does not keep dialogs on the stack that it\'s not using. For example, consider using replaceDialog instead of beginDialog.] Converting circular structure to JSON',dialogContext:{ activeDialog:'BeginSkill[\'=settings.skill[\'nodeEchoWa517\'].msAppId\',\'\']',parent: 'NodeWAParent517',stack: [ [Object], [Object] ] } }
Exception caught in sendErrorMessage Error: Error "Converting circular structure to JSON" occurred in serializing the payload - "Activity".at serializeRequestBody (C:\home\site\wwwroot\node_modules\@azure\ms-rest-js\dist\msRest.node.js:3564:19)at ConnectorClient.ServiceClient.sendOperationRequest (C:\home\site\wwwroot\node_modules\@azure\ms-rest-js\dist\msRest.node.js:3518:13)at Conversations.replyToActivity (C:\home\site\wwwroot\node_modules\botframework-connector\lib\connectorApi\operations\conversations.js:54:28)
at CoreBotAdapter.<anonymous> (C:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:845:71)at Generator.next (<anonymous>)at C:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:15:71at new Promise (<anonymous>)at __awaiter (C:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:11:12)at CoreBotAdapter.sendActivities (C:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:812:16)at Proxy.<anonymous> (C:\home\site\wwwroot\node_modules\botbuilder-core\lib\turnContext.js:377:54)

**Comment by joshgummersall** [comment]
This was a fun one! There were two very subtle cases of JSON serialization cycles.

1. The app insights telemetry client (not the null telemetry client) fails `JSON.stringify` with a cycle error once you've tracked an event (it must hold references to tracked events, thus introducing a cycle). Generally not a problem, but it is included in [trace events](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-ai/src/luisRecognizerOptionsV3.ts#L223) (via `options`) which are serialized
2. CosmosDbPartitionedStorage fails `JSON.stringify` with a cycle error after initialization (`this.client`), which is problematic because it is included in dialog state by the [begin skill action](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-dialogs-adaptive/src/actions/beginSkill.ts#L197) (via `conversationState`) which is serialized

The "simple" fix is to write [custom `toJSON`](https://javascript.info/json#custom-tojson) methods for these types that yield a simplified object when serialized. I've verified this fix works locally. We never attempt to ["revive"](https://javascript.info/json#using-reviver) these types after serialization, so I can't think of a reason this would be problematic.

**Comment by sgellock** [comment]
Shiproom - approved.  need to get a 4.13.3 patch for JS SDK.  Need to understand the NBT implications and whether we need to cut RC14 of these

**Comment by joshgummersall** [comment]
Should be resolved with `4.13.4`

**Comment by sgellock** [comment]
Shiproom - fix was verified with 4.13.4 release
