### ISSUE TITLE
Move LG away from common and to one .lg file per dialog

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#796]
@cwhitten @yochay @boydc2014 @hibrenda - If possible, we should get this slotted for Ignite. 

- [ ] Remove common.lg 
- [ ] Add one .lg file per dialog
- [ ] Verify ability to cross reference/ include other .lg content by dialog name
    e.g. [Include dialog A](dialogA) - here, dialogA should be resolved by the file resolver to map to dialogA's .lg file. 
- [ ] Each dialog can have at most one .lg file.
- [ ] Migration plan: once we have this in: try to look for a template in common.lg, if we find it, serialize it in to the dialog's .lg file.

**Comment by hibrenda** [comment]
**Need to support one .lg file per dialog and support importing lg file feature.**

Following is the new LG file structure. Keep common.lg, so other LG file could reference to this .
\MyBots\<botname>\ComposerDialogs>\Common\common.lg
\MyBots\<botname>\ComposerDialogs>\Main\main.dialog
\MyBots\<botname>\ComposerDialogs>\Main\main.lg
\MyBots\<botname>\ComposerDialogs>\A\a.dialog
\MyBots\<botname>\ComposerDialogs>\A\a.lg
\MyBots\<botname>\ComposerDialogs>\B\b.dialog
\MyBots\<botname>\ComposerDialogs>\B\b.lg
\MyBots\<botname>\ComposerDialogs>\C\c.dialog
\MyBots\<botname>\ComposerDialogs>\C\c.lg
 
Samples for LG files with importing lg file feature
 ```
Main.lg
#mainTemplate
-I am in mainTemplate 
 
#mainTemplateWithPara(para1,para2)
-I am in mainTemplate @{para1} and @{para2}
 
a.lg
[import](Main.lg)
 
# bfdprompt-123456
-I am in aLG and reference @{mainTemplate()}
 
```
**Supported Scenarios**
 
**_CRUD LG files_**
•	Lg file will be created automatically in "new dialog" step, lg file name is same as dialog file name. User cannot create a new lg file in lg all up view. If user create the lg file by himself under the same project name space but does not go through the composer UX, importing such lg file will not generate any runtime error but user cannot edit and view it in LG all up view.
•	Lg file will be deleted automatically in "delete dialog" step, if this lg file is referenced into other lg file, before user delete it, check the reference, and pop up warning for end user. If user still want to delete it, error & warning will be show up in notification page (linting and validation) before user start the bot.
 
**_LG all up view editing_**
•	In LG all up, user can browse all LG templates by "display view" and can edit each template in "edit view" if user switch to different LG files.
•	In display view, all lg files will be listed as left side, user can switch to different file to view the templates defined in each lg file. (Just like what we displayed for LU files)
•	In edit view, user could edit a lg file and add/update/delete the lg template and could update the "import file" as well. 
•	User create or update a lg template. If the template name was updated, composer should check lg template name across all lg files and make sure no duplicate lg template name. If user reference an existing template which defined in other lg file, user need to update the reference "import file" as well, otherwise it will complain errors.
•	User delete a template and template is referenced in other template(same lg file) or referenced in other lg file, once user delete it , error & warning will be show up inline and notification page will roll up all the errors before user starts the bot.
 
**_Inline LG editing_**
•	Composer supports inline LG editing in prompts and response.
•	User no need to define the template name if user add a prompts or response. composer will auto-generate template name for each inline lg editor and should also import corresponding lg file as well if user reference the lg template which does not exist in current dialog. User could directly edit the inline lg like following:
```
 -I am in aLG and reference @{mainTemplate()}
 ```

a.lg will be updated as following:            
  ```   
          [import](Main.lg)
 
         # bfdprompt-123456
         -I am in aLG and reference @{mainTemplate()}
``` 
•	User could delete the prompts and response through "delete" action. The corresponding lg template will be removed from lg file as well. If this template referenced by other template, error notification will be rolled up and showed to user before user starts the bot. If this template reference other template which not defined in this dialog, delete this template will also check whether the "import file" is still valid, if not, delete it as well.
 
**_Hook LG all up view editing with inline LG editing_**
•	**[Composer Gap]** As user could not update the default name of lg template in inline lg editing, if user delete the lg template or update the lg template name in LG all up view, the corresponding prompts and response will be broken as well.
If user just update the lg template content. Both LG all up view and inline LG editor will be updated as well.
•	**[Composer Gap]** Composer does not support dialog rename. If later rename feature delivered, we need to take care renaming impact for LG.

**Comment by cwhitten** [comment]
Requires ongoing discussion with @vishwacsena

**Comment by mareekuh** [comment]
@hibrenda and @sangwoohaan  - we need an overall issue about the nav for User Input and Bot Response. They are not optimized for the UX and are an odd match with the nav for the Design page

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/1861
