### ISSUE TITLE
Unable to call a multiple choice option using 2 conditions

### ISSUE THREAD

**Issue by jessthorne** [microsoft/BotFramework-Composer#8080]
I have created a multiple choice input in my dialog saying
 "When was the bill issued?" The multiple choice options are either 1. Less than 6 months, 2. Between 6 and 12 months 3. Over 12 months
I want to provide the customer with the choice of either selecting the multiple choice value (e.g. "Between 6 and 12 months") or entering a number and then providing the correct response based off that number. (E.g. customer inputs "8 months" and it goes to open 2)
I am not able to add both these conditions as an option one value.  

I am using the desktop version of Composer version 2.0.0 on macOS

Steps to reproduce the behaviour: (see the bug description). Excepted behaviour: being able to add multiple different conditions to one value

**Comment by dmvtech** [comment]
Hi @jessthorne 

Choice number recognition, as well as ordinal, should be enabled by default. Just set your choices as you want above. Then numbers and ordinals should work.

![image](https://user-images.githubusercontent.com/43397658/122131588-3df04880-cdee-11eb-8889-4bafc4cf552e.png)

Let me know if that answers your question or if I misunderstood the ask.

**Comment by jessthorne** [comment]
Hi,

Thank you for your response. I think you might have misunderstood slightly. There are 2 different scenarios I want the bot to be able to handle

**Scenario 1:** 

The question is: When was the bill issued?
the User input (Choice) is: 
- Less than 6 months
- Between 6-12 months
- Over 12 months ago

**Action:** 
The user selects one of those options and is provided the relevant response

**Scenario 2:** 

The question is: When was the bill issued?
the User input (Choice) is: 
- Less than 6 months
- Between 6-12 months
- Over 12 months ago

**Action:** 
Rather than selecting one of those options, the user just types in the words "8 months". Given 8 months is between 6 and 12 months, the bot should respond with the answer to choice number 2 
<img width="754" alt="Screenshot 2021-06-16 at 10 20 08" src="https://user-images.githubusercontent.com/49563377/122193535-7a728180-ce8c-11eb-8f5a-7ef20899e120.png">

**Comment by dmvtech** [comment]
@jessthorne Unfortunately choice prompt is not flexible enough to accomplish this goal. It is designed to use choice matching against a set amount of choices. The better way is to use language understanding/LUIS. Probably easiest done with sending [Suggested Actions](https://docs.microsoft.com/en-us/azure/bot-service/language-generation/language-generation-structured-response-template?view=azure-bot-service-4.0#definition) (instead of a choice prompt), then handling the response with LUIS. 

Something like:
```
# AskForAge.prompt
[Activity
    Text = When was the bill issued?
    SuggestedActions = Less than 6 months | Between 6-12 months | Over 12 months ago
]
```

This would be a prompt for text. You could have expected responses set up something _like_:

```
- Over {@lastbillperiod = 12 months ago}
- Between {@lastbillperiod = 6-12 months}
- Less than {@lastbillperiod = 6 months}
- 8 months

@ ml lastbillperiod datetimeV2
```

You can then use logic on the resolution. (Simple thing would be to get the entity as `${@lastbillperiod}`). All that being said, you have to work with LUIS and make sure you have logic to handle aspects of the resolution from LUIS. Out of the 4 above utterances, 3 came back with datetime types as `duration` and one came back as `date` ("Over 12 months ago").


Here's a bit of how to use the .lu format:
https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lu-file-format?view=azure-bot-service-4.0

You could still use a choice prompt, set the max turns to 0, then use language understanding/LUIS to handle it. But that's more convoluted and involved than needed. Suggested Actions is a cleaner and simpler route.
