### ISSUE TITLE
Selecting "JS community packages" from package manager filter dropdown causes an error

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#8118]
## Describe the bug
Selecting a package filter from the package manager UI displays an error

## Version
Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch composer
2. Create a new C# bot, or open an existing C# bot
3. Navigate to package manager
4. From the dropdown, select "JS community packages"
5. Note the error message.  see screenshot below

## Expected behavior
Package manager results should be updated to reflect the query.  if not results are returned, then I would expect the list of results to tell me so with a reasonably understood message in the list, not produce a modal.

## Screenshots
<img width="883" alt="Screen Shot 2021-06-16 at 4 22 01 PM" src="https://user-images.githubusercontent.com/733559/122307401-1f0db700-cebf-11eb-8b4e-c53125700201.png">

**Comment by benbrown** [comment]
This was due to out of date data in Scott's config file. This feed should not be present for users who did not consume the nightly builds pre-2.0

If this occurs to others, the solution is to delete the Package Manager preferences found in the `~/BotFrameworkComposer/extension-data/package-manager.json` file.
