### ISSUE TITLE
Jumping between triggers in the same dialog

### ISSUE THREAD

**Issue by BellaDunnett** [microsoft/BotFramework-Composer#8195]
It's not currently possible to jump between triggers within the same dialog. There's an option to 'Begin a dialog', but not to direct the user to a specific trigger within that dialog. It is also not possible to jump to a different trigger within the same dialog. This means that if a conversation flow ends and the user needs to be directed to a secondary conversation flow, this is only possible via custom events. If I use custom events, then they will not function as an 'intent recognized' trigger and other users will not be able to access the flow directly. Equally, if multiple intents need to trigger a single dialog, there is no clear way to handle this. How would you suggest handling these scenarios without activating triggers within the dialog? Is there a way to 'override' the user input and send the bot a message that would trigger an intent journey?

**Comment by dmvtech** [comment]
Hi @BellaDunnett I apologize for the delay. 

The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/blob/master/README.md) repos are the preferred platform for submitting **bug fixes** and **feature requests**.

However, let me comb through your scenario to confirm whether there are any bugs or gaps, or if it can be accomplished. I may have more questions for you, but I will let you know. Thank you for your patience.

**Comment by BellaDunnett** [comment]
@dmvtech Thank you, would you be able to see if there is a workaround for this scenario? Or if there is a bug?

**Comment by tonyanziano** [comment]
@dmvtech any comments on this?

**Comment by dmvtech** [comment]
hi @BellaDunnett 

Forgive me if I'm not fully understanding the scenario. If you can provide more specific scenarios (or a bot example shared in a repository), that would help. 

As you know, triggers are something that fire on certain events happen (most often by something done by the user). Typically if you need to 'direct' the user, you would use something like a suggested action. Meaning, if you need the user to give some sort of input back to the bot.  Otherwise, the logic of the bot should handle that (by beginning a dialog, or whatever. 

[Here](https://docs.microsoft.com/en-us/composer/concept-events-and-triggers?tabs=v2x) is more info on triggers if needed.

> Equally, if multiple intents need to trigger a single dialog, there is no clear way to handle this. 

There is the `Duplicated intents recognized` trigger. Have you looked into that?

> Is there a way to 'override' the user input and send the bot a message that would trigger an intent journey?

Again; I don't think I understand the scenario/ask here. If you have a more concrete example, I can suggest something.

**Comment by dmvtech** [comment]
@BellaDunnett I'm closing this as I believe I have answered the questions around the situation. If you still have further questions or need assistance; please comment and I will reopen.
