### ISSUE TITLE
User unable to add LUIS or QnA resource from composer

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#8212]
## Describe the bug

 customer is using bot framework composer 2.0.0, when he tries to add LUIS for the project, he gets the login page, after successfully login.

he could see the azure directory and subscription, however the LUIS resource never displays like following:

while i dont have this issue in my lab, not sure if this is related with the sponsorship sub?

Please see ICM issue:
https://portal.microsofticm.com/imp/v3/incidents/details/247570921/home

## Version

2.0.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

See ICM

**Comment by benbrown** [comment]
@Dewain27 is there a way for us to get access to a "Sponsorship sub" to see if we can recreate this issue? It may be a permission issue as @luhan2017 mentioned in the ICM.

**Comment by luhan2017** [comment]
@benbrown, there are the cases that one developer doesn't have the permission to all the resources under the subscription (they may have the permission only for his own resource group.)  @zhixzhan had a PR to fix this issue, #8160 . The fix is that we just ignore and don't show the resources which user have no permissions to list keys. This fix applies both for luis and qna.
