### ISSUE TITLE
Publish PVA causes issue, when using Switch Option (multiple options) in a dialog

### ISSUE THREAD

**Issue by tamasschmolcz** [microsoft/BotFramework-Composer#8319]
## Describe the bug

As soon as add at least one Case in "Branch: Switch" - Option in the dialog, I'll get the publish error "Publish failed. Plase check logs". Without a case publishing is successfully. Tried several case values with "" or '' or without.

Unfortunately I cannot find any local log files in the directory file to troubleshoot. 
## Version

2.0.0.0

## Browser

- [X] Edge

## OS

[X] Windows10

## Expected behavior

Able to publish the Composer dialog to PVA.

## Screenshots

![image](https://user-images.githubusercontent.com/48097252/125314444-7c6a1c00-e336-11eb-9021-c724eb55a6c3.png)

**Comment by tonyanziano** [comment]
Hello @tamasschmolcz ,

If you go to the "Publish" page of Composer, after your publish fails, do you see an error message in the "Message" column?

![image](https://user-images.githubusercontent.com/3452012/125336310-7a866580-e302-11eb-823d-a2d9962ad3c0.png)

**Comment by tamasschmolcz** [comment]
Hi @tonyanziano , no - just "the publishing failed as stated"-message as stated above.

Meanwhile I could fix the issue by deleting the Bot directory and re-download the PVA bot + inserting the modifcations again.

However, I would be curious where I could find the logfile for the next issue I encounter.. :-)

**Comment by tonyanziano** [comment]
@tamasschmolcz glad to hear you got around the issue!

To see the logs, you actually need to make sure that Composer is wide enough to display a button in the publish UI that will show more information about each publish job:

![image](https://user-images.githubusercontent.com/3452012/125353281-305baf00-e317-11eb-8309-e747590eb4a5.png)

![image](https://user-images.githubusercontent.com/3452012/125353345-48cbc980-e317-11eb-96e6-1cddd96f63bc.png)

This is a visual bug that we need to address so that it is visible when Composer is at a smaller width, but for now, maximizing Composer should show the button.

**Comment by tamasschmolcz** [comment]
@tonyanziano Thanks, I totally overlooked it!

**Comment by tonyanziano** [comment]
@tamasschmolcz not your fault! We need to fix the UI so that the button shows responsively at all widths. :)
