### ISSUE TITLE
watch: I can't always watch complex objects

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#8356]
I can watch properties of a complex object (in this case dialog.result.name) but I can't always watch a whole object. In fact the intelisense picker won't even let me select a root object:

![image](https://user-images.githubusercontent.com/698939/125357375-6b141600-e31c-11eb-888a-b0eaa2a7cffd.png)

**Comment by Stevenic** [comment]
This is after completing that run... So I was able to inspect `user.profile` but not `dialog.result`.

![](https://user-images.githubusercontent.com/698939/125357738-e07fe680-e31c-11eb-906d-7a5f6397c6c0.png)

**Comment by tonyanziano** [comment]
@Stevenic can you reproduce this, and show me the inspected Bot State traces in the "Web Chat" pane with the `dialog.result` object populated?

![image](https://user-images.githubusercontent.com/3452012/125535858-98c3211b-ef25-42c0-a3cc-cf9fbbf1b94f.png)

I'm curious to see what the bot state trace shows for you in this case.

I was able to see it render the object view for the `dialog.result` object when prompting me for my age after collecting my name.

**Comment by tonyanziano** [comment]
Regarding the second issue of not being able to select an object in the picker with child properties, I'm currently looking into the possibility of adding that to the current style of context menu we use.

There are some challenges with this. The current style we use has a chevron icon with its own click target on expandable menu items, however, these icons are currently not focusable via keyboard navigation. This means that we would have to add the ability to focus the icons with the keyboard and make sure that it retains the correct screen reader behavior.

Alternatively, we could consider switching to one of the other Fluent Contextual Menu styles -- which uses split buttons, that already have built-in accessibility and keyboard navigation for the menu item and a second button that expands the sub menu:

![image](https://user-images.githubusercontent.com/3452012/125674593-b0b0fe74-c003-4604-8b00-5cc684e769b9.png)

However, this visual model would be quite different from what we currently have, because the sub menus would expand outward horizontally instead of vertically within the menu pane.

@mewa1024

**Comment by mewa1024** [comment]
hmm. It looks like we use the flyout menu in other places in Composer, like the prebuilt function picker (this example doesn't have the split button):
![image](https://user-images.githubusercontent.com/39317542/125710946-ceb83cd3-6465-4f0c-972c-8941f4a4f339.png)

so I'm okay with switching to that component if that is easier to build and maintain.

**Comment by tonyanziano** [comment]
It actually looks like it will require a lot of code to switch to the Split Button / flyout model, so I'm going to try and fix what we already have with the proper focusing and keyboard navigation.

Plan B will be to switch to the other model.
