### ISSUE TITLE
Unexpected error: Cannot read property ‘startsWith’ of undefined

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#8368]
## setup
* simple node.js empty bot
* add qna kb's luis dialog, orchestrator on top
* few simple language intents, triggers

## repro
Hit the duplicated intent recognized condition and then that error showed up (see visual below)

## error in emulator

![image](https://user-images.githubusercontent.com/8867670/125363836-39a04800-e326-11eb-932e-ff599c3d4c1d.png)

## bot general structure

![image](https://user-images.githubusercontent.com/8867670/125364108-c0edbb80-e326-11eb-9e4e-c9d5bb39ffe8.png)

**Comment by taicchoumsft** [comment]
The root cause was located in `getTopScoringIntent`, where it is possible in the nodejs version to return an `undefined` value. In the dotnet implementation the function always returns a string.

At some point, the CTRS (crosstrainedrecognizerset) `IsRedirect` function is called, which expects a string, causing the uncaught exception.
