### ISSUE TITLE
No way to disable public repo access

### ISSUE THREAD

**Issue by bradrlaw** [microsoft/BotFramework-Composer#8477]
Working with a large financial client that has a common industry security practice of filtering and blocking public repo access.  There is no method to turn off the default public repo access and Composer always attempts to access the repo locations at startup / going to the package manager.  For this client, this causes a security exception to be thrown on the developer's machine.

There needs to be a way to completely disable access or remove the public repo locations.

**Comment by tonyanziano** [comment]
@benbrown can you please take a look at this?

**Comment by benbrown** [comment]
@bradrlaw thank you for your feedback. The current version of Composer uses the public package management tools like npm and nuget to deliver new bot templates as well as their related dependencies.  There is not currently a way to replace the new bot template feed with a private version.

HOWEVER, you can add private feeds to package manager in order to install components from alternate sources.

I will highlight your request to the PM team!

**Comment by pavolum** [comment]
@bradrlaw I assume since they cannot connect to public npm then they not only have the issue (error modal) on start but also have no templates in the template selection view since those are sourced from npm. 

Couple questions for the client. 
- What is their current process for accessing public npm/nuget packages? Is there an internal private npm feed or artifactory were they host npm packages that have been approved for internal use? npm proxy? 
  - If so, can that internal package manager be indexed similar to how the npm registry can be indexed  (i.e. [sample registry api call](https://registry.npmjs.org/-/v1/search?text=generator+keywords:bf-template+scope:microsoft))
- What happens if they are working on a node project that has other node dependencies and they run `npm install` will this also fail due to not having access to public npm where the dependencies are sourced?
- What happens if they are working on a dotnet project that has nuget dependencies and they run `dotnet restore` will this also fail due to not having access to public nuGet where the dependencies are sourced?

Please check out this [issue](https://github.com/microsoft/BotFramework-Composer/issues/8525) where I have outlined a potential workaround to unblock users between now and when the patch release with the solution is shipped. 

I am happy to get on a call tomorrow to review this issue and can join a call with the client if needed. Cheers!

**Comment by bradrlaw** [comment]
Need to re-open this request.  The fix takes care of the template access but not the package management.  Clients need to be able to disable the public repo feeds and have only their private feeds enabled.

**Comment by benbrown** [comment]
It is possible to remove the default feeds from Package Manager by editing the configuration file.  @bradrlaw would that be doable?

If so:

1. Find the configuration file in the `~/BotFrameworkComposer/extension-data/package-manager.json` file (on a Mac) or the `USER\AppData\Roaming\BotFrameworkComposer\extension-data\package-manager.json` file on a PC.
2. Inside this file, remove any of the feeds you do not want to appear.
