### ISSUE TITLE
Error when I use GetConversationMembers In MS Teams

### ISSUE THREAD

**Issue by Uggi** [microsoft/BotFramework-Composer#8615]
## Describe the bug

when running a bot from MS Teams, when I attempt to call GetConversationMembers component to get the name of the people
I get the following error "GetConversationMembersAsync() only works with BotFrameworkAdapter"
Am I missing a setting? is there something I need to enable?

## Version

![image](https://user-images.githubusercontent.com/4349731/131146076-90be2bd2-d38c-43ac-bdde-b7f4908ebe05.png)

## Browser

Edge Browser

## OS

Windows

## To Reproduce

1. Add the GetConversationMembers component to any BeginDialog

![image](https://user-images.githubusercontent.com/4349731/131146431-f9c5098c-378d-43fe-8d89-681e3f898ea7.png)

![image](https://user-images.githubusercontent.com/4349731/131146396-ad103d4a-b9a2-4327-9c2e-fa2126316ccb.png)

## Expected behavior
Get the details of the MS teams user in a private chat which includes their email address.

## Screenshots

![image](https://user-images.githubusercontent.com/4349731/131146620-a03b474f-ff68-4f7a-98ea-7334948f94aa.png)

**Comment by LeeParrishMSFT** [comment]
@Uggi Thanks fore reporting this. I'm setting up a repro and will report back what I find as soon as I can track something down.

**Comment by LeeParrishMSFT** [comment]
@Uggi based on my investigation it seems that this function was missed during a code refactoring and it will require a fix in a future SDK to get this enabled again. There may be a workaround using some custom code until that can be done, are you needing this now for a production bot, or are you prototyping or doing some investigation for now?

**Comment by Uggi** [comment]
Hi @LeeParrishMSFT, Thanks for investigating the issue. We need it for a production bot which we plan to release mid-september. Guidance for a work around would be much appreciated.

**Comment by LeeParrishMSFT** [comment]
@Uggi  I've created a sample here: [GetMembersBot](https://github.com/LeeParrishMSFT/GetMembersBot)  that has the code needed in a Custom Action (documented here: [Create custom actions](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions) ) that will provide the same results as the built in GetConversationMembers. You can clone the sample repo and add the GetConversationMembersDialog to your Composer solution, and then follow all the other required steps in the instructions for creating a custom action to get it registered to your solution, or you can just follow the instructions for creating a custom action and replace where the source for the MultiplyDialog is referenced with the source for the new GetConversationMembersDialog. I've logged an issue against the SDK runtime to get this fixed in the next release, but that may be in October, so this should get you going until then.

**Comment by Uggi** [comment]
Great. Thanks @LeeParrishMSFT

**Comment by srinaath** [comment]
@Uggi Closing this ticket as the feature has been merged and would be avaialable in our next SDK release.
