### ISSUE TITLE
Give user an option to change his answer

### ISSUE THREAD

**Issue by elibery** [microsoft/BotFramework-Composer#8666]
We are trying to migrate our bot from V3 to V4 using composer and there are 2 functionalities that we are using and could not find if those options are available in V4:

1) "Back" - In V3 if user provides back, the bot asks previous question again and allows the user to change his answer. I could not find anything regarding this in docs. If there is no way to do this in composer for now  it would be great because if the user makes a mistake in one of the questions then he would need to start the form from the beginning to change his answer.

Example:
![image](https://user-images.githubusercontent.com/68510456/133419390-04043e95-e5cf-4f22-9b0a-583353a57599.png)

2) "Confirm" - In V3 there is an option at the end of the form to ask user's confirmation if all the answers he provided are good, and if there is one answer that is a mistake, he has an option to change only that answer. Is this option also available in V4 composer?

Example:
![image](https://user-images.githubusercontent.com/68510456/133419808-5d379e00-d3d4-4b95-bc9d-2923d106938c.png)

**Comment by stevkan** [comment]
This can be achieved thru the tools already available in Composer. I have attached a bot that demonstrates this. The bot's construction includes:

- Separating out each question into its own dialog so the question can be repeated, when necessary
- One "parent" dialog that each question dialog is a child of. User input in the child dialogs are returned to the parent dialog and stored
- In the various input prompts, setting the 'max turn count' to 0 so the question itself is repeated immediately on failed validation
- Not necessary for the demonstration, but inclusion of input validation to verify the user's answers are at least in the realm of appropriate for the question
- Setting the input prompt to store a default `null` value in case no value is somehow provided
- Set always prompt to `true` so a repeated question will always ask for and store a new value
- The inclusion of a confirmation prompt after user input so the user can verify their own response. If not acceptable, then the question is repeated. Otherwise, the conversation moves on to the next question / end of dialog.

Not included in the demo, but you could also enable interruptions. Then create triggers that, for example, when the user says 'enter new age' would bring them back thru the age dialog. When the interruption finishes, it should return the user where they had exited (unless you redirect as part of the interruption).

I'm closing this as resolved as this solution should meet your needs.

[ChangeAnswerOption.zip](https://github.com/microsoft/BotFramework-Composer/files/7206538/ChangeAnswerOption.zip)
