### ISSUE TITLE
Using Adaptive card as input form is not working throwing object references not set to an instance

### ISSUE THREAD

**Issue by mohd-ismail-siddiqui** [microsoft/BotFramework-Composer#8692]
Hi @luhan2017 @srinaath, I am facing another issue while developing a Bot. I want to send an adaptive input form to the user and want to collect some information and then send that object to a rest api.

But getting issue while sending adaptive card form. Also can you please tell me how can I submit this data to some external resource.

![image](https://user-images.githubusercontent.com/87179559/134487342-2922b14e-6d50-4aa4-9bbc-5b1330bd2302.png)

Please find the attached code.[Adaptive Card Form](https://github.com/mohd-ismail-siddiqui/VirtualTravelAssistantLuis)

**Comment by dmvtech** [comment]
HI @mohd-ismail-siddiqui The link you gave is invalid (is it a private repo you forgot to make public?).

**Comment by mohd-ismail-siddiqui** [comment]
@dmvtech , Thanks to point out. I have made it public. Now you can access it.

**Comment by dmvtech** [comment]
Hi @mohd-ismail-siddiqui 

> I want to send an adaptive input form to the user and want to collect some information and then send that object to a rest api. But getting issue while sending adaptive card form. 

The issue here is that you are using an `Attachment Prompt` instead of a `Text Prompt`. You don't want to _receive_ an attachment, you want to receive text (_**kind of**_. See below for more info/explanation.), even though you are _sending_ an attachment (the card). 

```json
        {
          "$kind": "Microsoft.TextInput",
          "$designer": {
            "id": "iTlIUW"
          },
          "maxTurnCount": 0,
          "alwaysPrompt": false,
          "allowInterruptions": false,
          "unrecognizedPrompt": "",
          "invalidPrompt": "",
          "prompt": "${AttachmentInput_Prompt_JR6rYJ()}"
        },
```

Once you change the prompt you may notice that after filling out the form, you will get prompted for the card again. This is because even though the card being sent back is of type `message`, it contains no `text` value. Since this is null, you get prompted again. This can be remedied by setting the `maxTurnCount` to 0 as I have done (above). Further, since there is no text value from this text prompt; `turn.value` will be null after the prompt. BUT, you should still be able to retrieve your value from the turn activity as you have done with `=turn.activity.value.Country`.


> Also can you please tell me how can I submit this data to some external resource.

You can use the [Send an HTTP request](https://docs.microsoft.com/en-us/composer/how-to-send-http-request?tabs=v2x) action.

**Comment by dmvtech** [comment]
Hi @mohd-ismail-siddiqui Did the above help at all? Are you able to get it working the way you expect/desire?

**Comment by mohd-ismail-siddiqui** [comment]
Hi @dmvtech , I have tried what you have said but facing now another issue.

`
"actions": [
        {
          "$kind": "Microsoft.TextInput",
          "$designer": {
            "id": "i7FAty"
          },
          "disabled": false,
          "maxTurnCount": 0,
          "alwaysPrompt": false,
          "allowInterruptions": false,
          "unrecognizedPrompt": "",
          "invalidPrompt": "",
          "defaultValueResponse": "",
          "prompt": "${AttachmentInput_Prompt_JR6rYJ()}",
          "property": "user.TravelRequest.DestinationCountry"
        },

Error : TravelRequestForm.en-us.lg:[Error] inline content: [__temp__68bd8d7ce4804048a5dcf72b6e8b55a7]Error occurred when parsing expression ‘AttachmentInput_Prompt_JR6rYJ()’. AttachmentInput_Prompt_JR6rYJ does not have an evaluator, it’s not a built-in function or a custom function., TravelRequestForm.en-us.lg:[Error] inline content: [__temp__2c5e9fe8e50249d0976c5801e74d914e]Error occurred when parsing expression ‘AttachmentInput_Prompt_JR6rYJ()’. AttachmentInput_Prompt_JR6rYJ does not have an evaluator, it’s not a built-in function or a custom function.
`

**Comment by dmvtech** [comment]
@mohd-ismail-siddiqui  This is most likely something that just didn't get lined up correctly during a change. Please check the code view of your dialog as well as the LG (Bot Responses) to find out what may be mis-matched. 

I'm guessing that `AttachmentInput_Prompt_JR6rYJ()` no longer exists as you removed the attachment prompt, but the new text prompt (`Microsoft.TextInput`) didn't switch over to the right template/response.
