### ISSUE TITLE
Suddenly I cannot log in to composer using my office credentials

### ISSUE THREAD

**Issue by csmuthukuda** [microsoft/BotFramework-Composer#8846]
## Describe the bug

![image](https://user-images.githubusercontent.com/22663629/145531865-9e23e7f0-5716-4734-b30e-fb787ad221ba.png)

as you can see in the above screen shot, This error appears whenever I tried to log in to Azure using my office credentials. It was working previously and suddenly today I ended up with this error.

## Version

Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Chrome

## OS

- [ ] Windows

## To Reproduce

1. Go to composer and tried to log in using office credentials

**Comment by schmargi** [comment]
Same here....

**Comment by rolandbodenstaff** [comment]
I have the same issue cannot signin with my work credentials anymore

**Comment by pscompa** [comment]
It's the same for me!  
(Yesterday it worked fine)

![image](https://user-images.githubusercontent.com/34023729/145589951-4c3da2d7-5b40-4d7f-a1a4-87880d6a47e9.png)

**Comment by gabog** [comment]
Hi @tdurnford, could you take a look at this one and see what the issue could be?

**Comment by tonyanziano** [comment]
@carlosscastro and I have reached out to the OneAuth time and are investigating the issue. We will provide more details as we get them.

**Comment by tonyanziano** [comment]
For anyone experiencing this issue, it would be incredibly helpful to our investigation if you could enable Composer's debug mode before reproducing this issue, and then sending us the logs generated.

In order to do this (On Windows):

1. Navigate to Composer's installation location (`C:\Users\<user>\AppData\Local\Programs\Bot Framework Composer` on my machine)
2. Open a command line window or preferred terminal window in the Composer directory
3. run `set DEBUG=composer*` command in the window
4. Start Composer from the window by typing `"Bot Framework Composer.exe"

You should now see messages in the terminal window prefixed with `composer:<some:other:path>`. If you do, that means you have enabled debug mode successfully.

Now, try to reproduce the issue, and after you have successfully run into the issue, please copy **all** the output from the terminal window, paste it into a text document, and post it here, or feel free to send it directly to my email toanzian@microsoft.com and we will forward this internally to the OneAuth team.

Thanks all!

**Comment by tonyanziano** [comment]
Turns out this is an issue with the authentication library we are using that is affecting multiple apps -- not just the Emulator. That team is currently investigating the issue.

**Comment by csmuthukuda** [comment]
Hi @tonyanziano..now it's working as expected..I can log in without any issues..thank you for your effort

**Comment by benbrown** [comment]
Thanks for the follow-up @csmuthukuda. Glad to hear it has cleared up as expected when the upstream problem was resolved.

**Comment by infyrohan** [comment]
Hi @tonyanziano,

I am getting same error from today, while logging into Bot composer with work email. Can you please check it and get resolved earliest?

**Comment by tonyanziano** [comment]
Hi @rohan081296 ,

What version of Composer are you using, and what OS are you running it on?

**Comment by rohan081296** [comment]
Hi @tonyanziano ,

I am using Composer v2.1.1 on windows. It not worked for two days when I reported issue. After that, automatically it started working. Currently, It is working properly.

Thanks you for your consideration. Really appreciated.

**Comment by tonyanziano** [comment]
Glad to hear it!
