### ISSUE TITLE
Need to get the base64 content of files attached by user

### ISSUE THREAD

**Issue by RamkumarManavalan** [microsoft/BotFramework-Composer#8911]
I have a requirement to get files from users and send its content to my backend which accepts filecontent as base64 encoded. 

I used the "File or Attachment" input to get the file attached by user in the chat window. This returned a json as below:

[{"contentType":"application/octet-stream","contentUrl":"https://smba.trafficmanager.net/apis/v3/attachments/0-sa-d4-6e8441b1dfa41f0bf317b67a50c52fa9/views/original","thumbnailUrl":"https://smba.trafficmanager.net/apis/v3/attachments/0-sa-d4-6e8441b1dfa41f0bf317b67a50c52fa9/views/thumbnail","name":"output-6.json"}]

Then I did a GET of the contentUrl. I see two issues here:

1. For text files like json, I got an array of ascii values, which I am not able to convert to a base64 encoded format.
2. For PDFs, I got non-readable format, which again I am not able to convert to a base64 encoded format.

Please suggest a way for me to get the base64 encoded format of files that are attached by users in the chat window. I need support for PDF, csv, json, txt, xls, doc.

I use the below version:
Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by anishprasad01** [comment]
The [Handling Attachments sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/15.handling-attachments) (C# linked, but samples in the other 3 supported languages are also available) shows how to get attachments from users and convert them to base64. Most languages, including those used by the Bot Framework, support base64 conversion with built-in standard library functions (the sample shows this in use). You might also want to double check in your code what kind of files your users are inputting and validate them to ensure your bot can handle them. You could for example prevent your bot from trying to process a corrupted or otherwise unreadable format and instruct the user to upload a valid file. 

Furthermore, The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). This issue will be closed, but if you have a bug or feature request, please feel free to open a new issue in the appropriate repository.

**Comment by RamkumarManavalan** [comment]
Thank you. However, I am using the bot framework composer and I have not written any custom code. So, does it mean that there are no pre-built functions to accomplish what I need and that I should write custom code to achieve this?

**Comment by anishprasad01** [comment]
Oh sorry, I thought this was an SDK bot. Composer is a bit different. Here are the [docs](https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input?tabs=v2x) for getting user input in Composer, one of which is attachments. 

If your file type isn't natively supported, custom actions are a valid option.

**Comment by RamkumarManavalan** [comment]
Yes, I am using the user input you have quoted. The issue I face is mentioned below. Or, please point me to a good documentation that explains how I can write custom actions in Node and use the same in Composer.

I used the "File or Attachment" input to get the file attached by user in the chat window. This returned a json as below:

[{"contentType":"application/octet-stream","contentUrl":"https://smba.trafficmanager.net/apis/v3/attachments/0-sa-d4-6e8441b1dfa41f0bf317b67a50c52fa9/views/original","thumbnailUrl":"https://smba.trafficmanager.net/apis/v3/attachments/0-sa-d4-6e8441b1dfa41f0bf317b67a50c52fa9/views/thumbnail","name":"output-6.json"}]

Then I did a GET of the contentUrl. I see two issues here:
- For text files like json, I got an array of ascii values, which I am not able to convert to a base64 encoded format.
- For PDFs, I got non-readable format, which again I am not able to convert to a base64 encoded format.

Please suggest a way for me to get the base64 encoded format of files that are attached by users in the chat window. I need support for PDF, csv, json, txt, xls, doc.

**Comment by anishprasad01** [comment]
Here is the documentation for [custom actions](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions). The docs are in C#, but there is also a [Node sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/composer-samples/javascript_nodejs/projects/custom-action/multiply-dialog-package).

**Comment by RamkumarManavalan** [comment]
I did look at those and downloaded the same too. In the  [custom actions](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions)  doc, the section "Setup the component project" talks about instructions in C# bot using Visual Studio, whereas my main composer bot is in node. So, I need to know how to how to add the customaction (node) to my node composer bot using Visual Studio Code.

**Comment by anishprasad01** [comment]
There are corresponding files in the Node sample, which is why I linked it. For example, the `package.json` [file](https://github.com/microsoft/BotBuilder-Samples/blob/main/composer-samples/javascript_nodejs/projects/custom-action/multiply-dialog-package/package.json) has the list of dependencies that the `sln` file contains in C#

**Comment by anishprasad01** [comment]
Please direct all further **how to** questions to [Stack Overflow](http://stackoverflow.com/search?q=%23botframework).
