### ISSUE TITLE
Conversation loops back to input prompt after interruption

### ISSUE THREAD

**Issue by yulsa** [microsoft/BotFramework-Composer#8993]
## Describe the bug

- InputText prompt is set to allow interruption
- When user types a text that is interrupted by an intent in the main dialog, the conversation shifts there.  However, after the triggered action is processed, the conversation comes back and requests the same user input again.
- Expected behaviour -> the conversation closes the dialogs that were interrupted and continues along the path of interruption

## Version

composer version: 2.1.1

## To Reproduce

1. create dialog with text input prompt, set to interruption = true
2. in the main dialog create an intent with trigger such as 'lawsuit', with basic send response (you activated intent 'lawsuit'
3. start a conversation, and when encounter the text input prompt, type 'lawsuit'
4. the send response will appear, followed by text input prompt again

## Expected behavior
- expecting not to go back to the text input again

## Screenshots
<img width="637" alt="Screen Shot 2022-02-12 at 11 27 53 AM" src="https://user-images.githubusercontent.com/30275275/153719864-7c370cc8-a87d-484d-a69f-587f522483af.png">

**Comment by stevkan** [comment]
@yulsa, this is by design and is expected behavior. If you are wanting the interruption to not return to the original dialog, then you need to add the "Cancel all active dialogs" action to the interrupting dialog's flow.

![image](https://user-images.githubusercontent.com/18403946/154144348-85798551-08af-4121-84b4-4970b2e67e36.png)

As you can read in the docs regarding [Ending dialogs](https://docs.microsoft.com/en-us/composer/how-to-control-conversation-flow?tabs=v2x#ending-dialogs),
> Any dialog called will naturally end and return control to its parent dialog when it reaches the last action in its flow.

For additional understanding, you can refer to the [Use intents to enable interruptions](https://docs.microsoft.com/en-us/composer/how-to-define-intent-entity?tabs=v2x#use-intents-to-enable-interruptions) doc.

**Comment by yulsa** [comment]
@stevkan thank you for your response.  I looked into the 'cancel all active dialogs' option and the issue is that the new triggered dialogs branch out in too many ways.  Finding all end points to each resulting flow is highly prone to human error, and in an enterprise level bot with many triggers and conditional flows it is virtually impossible to get right.  

On the other hand placing 'cancel all active dialogs' right after a new intent is triggered stops the bot from processing that trigger. 

Is it possible to close all dialogs except the triggered one?  Or is there some setting that allows to get back to the triggered activity after dialogs were closed?  Basically looking for some way to do equivalent of 'stop what you were doing and forget about it, and follow this new path now for good' without manually tracing all the possible end points of the new path.
