### ISSUE TITLE
Error posting activity to bot in web chat

### ISSUE THREAD

**Issue by rschuetzler** [microsoft/BotFramework-Composer#9019]
## Describe the bug

I am unable to test a bot on a Mac. I have tried C# and Node bots with and without LUIS capabilities, and even the base bot is unable to chat in the Web Chat window. 
## Version

* Version:  2.1.2
* Electron: 8.2.4
* Chrome: 80.0.3987.165
* NodeJS: 12.13.0
* V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot using the templates
2. Run the bot
3. Open web chat and send a message
4. Message fails with an internal server error:

```
[09:57:39 AM]POST201/v3/conversations
[09:57:39 AM]POST500/v3/directline/conversations/8d8197af-071a-4462-be5d-9700f0b63aec%7Clivechat/activities
An error occurred posting activity to the bot. Internal Server Error
[09:57:42 AM]POST500/v3/directline/conversations/8d8197af-071a-4462-be5d-9700f0b63aec%7Clivechat/activities
An error occurred posting activity to the bot. Internal Server Error
[09:59:30 AM]POST500/v3/directline/conversations/8d8197af-071a-4462-be5d-9700f0b63aec%7Clivechat/activities
An error occurred posting activity to the bot. Internal Server Error
```
## Expected behavior

Be able to chat with a bot

## Screenshots

Node bot without language:

<img width="1300" alt="Screen Shot 2022-03-01 at 10 01 59 AM" src="https://user-images.githubusercontent.com/600775/156214255-c34c2d6b-d6c1-4dc5-ab93-f2199cfef43b.png">

Node bot with language:

<img width="1300" alt="Screen Shot 2022-03-01 at 10 02 58 AM" src="https://user-images.githubusercontent.com/600775/156214495-702b50bf-3145-4e00-a5f5-62876c962cbc.png">

**Comment by rschuetzler** [comment]
I have confirmed that the same bot works on Windows (using the same Git repo).

**Comment by anishprasad01** [comment]
Hi @rschuetzler,

Are you using MacOS Monterey? A change was made in that version of the OS that claimed port 5000 for a Mac feature, which in turn caused this bug in Composer. A [fix](https://github.com/microsoft/BotFramework-Composer/issues/8956) was made and rolled out in a nightly release, but I'm not sure if that's made it to stable yet.

You could try enabling preview versions of Composer in the interim. Otherwise, the Windows and Linux versions should also work fine.

![image](https://user-images.githubusercontent.com/33945547/156247855-959bf5f9-9bc9-4dd9-a8ed-7261e9aa3156.png)

**Comment by rschuetzler** [comment]
That was the issue, and the pre-release fixed it. Thank you!
