### ISSUE TITLE
Error when signing in on Bot Framework Composer

### ISSUE THREAD

**Issue by jmlp1** [microsoft/BotFramework-Composer#9066]
## Describe the bug

Error when trying ot sign in on Bot Framework Composer with my Azure AD Account

## Version

Release: 2.1.2

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Top Corner and click on the User icon, Sign in to your Azure Account'
3. Approved the signing on MS Authenticator
4. See error below

## Expected behavior

Expect to sign in on the app with my Azure Account

## Screenshots

![image](https://user-images.githubusercontent.com/11055362/160009202-342179b3-e2e1-42ba-b9e6-b6b5e751be55.png)

## Additional context

N/A

**Comment by jmlp1** [comment]
Updated to Release: 2.1.2-nightly.297306.7333498, same issue

**Comment by ramfattah** [comment]
Hi @jmlp1 ,

There have been several known sign-in issues related to tenant not being found in the latest release. Have you tried going back to 2.1.1 to see if this issue is resolved?

Download composer [2.1.1 here ](https://github.com/microsoft/BotFramework-Composer/releases/tag/v2.1.1)and try to sign in again.
Let me know if this worked. Thanks
