### ISSUE TITLE
Get the user information in emulator , teams and SharePoint list/website using Bot framework composer without authenticating user 

### ISSUE THREAD

**Issue by karthik22920** [microsoft/BotFramework-Composer#9078]
Can Anyone  walk me through entire process please i am new to bot composer .
Requirement :
1 To get user name and user id(email) without authenticating user(without using graph api ) i need to get user name .For now we are planning to deploy it to our SharePoint list/teams i need a way to make it work in both the channels ???
2 to greet user with user name Irrespective of channel i may publish
Example: Hello (name of the user)

**Comment by anishprasad01** [comment]
Hi @karthik22920,

If I understand your question correctly, you want your bot to address the user by name from the beginning without authentication? This is not possible. Without *some* mechanism of identifying the user, the bot has no idea who the user is, nor what name to address them by. 

Since you do not wish to use any form of user auth, you would need to:
- Establish a conversation with the bot.
- Explicitly ask the user for their name and email address in a dialog
- Manually store this information in some sort of permanent data store
- Query and re-use this information as needed

However, since you are deploying to Teams, it is important to note that Teams **does not** perform the expiration and reconnection of conversations that you might do in other channels. Once the user establishes a conversation with the bot, that single conversation remains in play. After the initial connection, the bot will never "welcome" the user again unless you program an explicit card or command into the bot to redo the welcome flow. 

Why do you want to avoid Graph? Using Microsoft authentication mechanisms for a Teams bot appears to be the appropriate solution for your scenario.

**Comment by karthik22920** [comment]
@anishprasad01 thanks for responding .
1 SharePoint :
Lets take an example if we are deploying our bot in SharePoint list .The user who has access to it has already been authenticated while accessing the SharePoint .so if i deploy the bot in SharePoint list i no need to authenticate user again . I am trying to figure a way where i can fetch the details from their .
2 Teams :
 In teams whoever wants to use bot are  already signed in user (so he/she is already authenticated ) why to authenticate again 
Is their an other way ?
3 Lets say  i store it in cosmos dB/ Blob storage (on Azure) .I might prompt user for email and and name  and log their details .
How do i fetch it back from cosmos dB/ Blob storage to Bot Composer and use it
