### ISSUE TITLE
How to access azure app config keys from bot composer?

### ISSUE THREAD

**Issue by Deekshatm** [microsoft/BotFramework-Composer#9154]
Currently ,in bot composer, we are connecting to azure resources by directly passing the keys in the application settings from the GUI, which in-turn generates an applicationSettings.json in the solution

![image](https://user-images.githubusercontent.com/51149590/167081500-c9aad5a9-1706-43e0-ba6a-8e7ee2fc5096.png)

In our traditional bot framework dotnet solution we load the azure configuration dynamically using azureAppconfig Api by passing in the connection string. We would like to load the azure config in the composer in the same way.

**Comment by lauren-mills** [comment]
Hi @Deekshatm, can you share a bit more about what changes you needed to make to your Bot Framework v4 project to support loading the keys from the connection string? Composer Bots have a lot of specific logic for loading keys and managing resources in startup.cs that may be difficult for you to customize in this way, but we can tell you more once we get a better idea of what your current bot does here.

**Comment by Keshavnemeli** [comment]
Hi @lauren-mills, In Composer project, We would like to load azure config keys dynamically instead of storing them in appSettings.json.  We are following a similar approach in a different Dotnet Framework project using ```Microsoft.Extensions.Configuration.AzureAppConfiguration``` package and this [method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.webhostbuilder.configureappconfiguration?msclkid=00a1fc1acf6411eca763c3b827926075&view=aspnetcore-6.0). We would like to load the keys and access them in one of the composer [memory scopes](https://docs.microsoft.com/en-us/composer/ref-memory-variables?msclkid=70727568cf6311ec860ae01e7af51692&tabs=v2x). 

For Example: We would like to load third party application secret to call their apis.

**Comment by dmvtech** [comment]
Hi @Keshavnemeli 

> We would like to load azure config keys dynamically instead of storing them in appSettings.json

You will need to modify the runtime and load them through the API.

> We would like to load the keys and access them in one of the Composer [memory scopes](https://docs.microsoft.com/en-us/composer/ref-memory-variables?msclkid=70727568cf6311ec860ae01e7af51692&tabs=v2x)

Once the runtime is started with them loaded, then you can use the `settings.` memory scope  (as you're aware). 


 
 #
The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/blob/master/README.md) repos are the preferred platform for submitting **bug fixes** and **feature requests**. If you need further help with implementing this, an example, etc; please share what you have already tried in a question on Stack Overflow.
