### ISSUE TITLE
Provisioning Script is expensive to run (without warning).

### ISSUE THREAD

**Issue by Parakleta** [microsoft/BotFramework-Composer#9211]
I had some trouble getting the key settings to load in the Bot Framework Composer (some header error, sorry I didn't note down the exact message) so I rummaged around and came across this https://docs.microsoft.com/en-us/composer/how-to-provision-azure-resources document.

I followed the instructions there and was able to provision the resources, but was unable to test the bot because the instructions here https://docs.microsoft.com/en-us/composer/how-to-host-composer#update-start-bot-emulator-links reference a file that doesn't exist.  At this point I gave up intending to come back when I had more time in the future.

Then 6 days later my Azure student access was disabled because I was out of credit.

The provisioning script activates a set of services that consumed around AU$140 in credit in just 6 days.  There really should be a warning both on the documentation page and in the script itself.

To add insult to injury, your support personnel have refused to reactivate my account unless I put in credit card details, and there is no way in hell I'm doing that.  And so ends my exploration of your Bot service...

**Comment by anishprasad01** [comment]
I'm sorry to hear you had a poor experience.

Except for those resources which fall under the [free tier](https://azure.microsoft.com/en-au/pricing/free-services/), all Azure resources require payment to use, the pricing for which you can find on the [Azure pricing](https://azure.microsoft.com/en-au/pricing/#product-pricing) page. Monitoring your spend is a crucial part of commercial cloud usage. One important tool that may help in the future is setting up [budgets](https://docs.microsoft.com/en-au/azure/cost-management-billing/costs/tutorial-acm-create-budgets) to control spend and notifying you when you are about to reach spending thresholds.

The first document you referenced is the documentation for deploying resources for IT admins. Here is the [quickstart](https://docs.microsoft.com/en-au/composer/quickstart-create-bot) for creating Composer bots for new individual users, including how to test locally. Some bot applications (but not all) can be tested locally without deploying to Azure.

The second document you referenced are the instructions for hosting the Composer application itself in the cloud, as opposed to a bot built with Composer. Here is the documentation for how to [deploy a bot to Azure from Composer](https://docs.microsoft.com/en-au/composer/how-to-publish-bot?tabs=v2x).

These docs also list [which resources are created](https://docs.microsoft.com/en-au/composer/how-to-provision-azure-resources#share-resource-details). The Azure for Students sign-up page also lists the [pricing and service availability](https://azure.microsoft.com/en-au/free/students/) for student accounts. In the future, this information can help you decide what budgets to create and how much of a resource you can use before encountering charges. Please note that the free Azure resources on offer as a student and those offered in general are *not* the same. When your student access expires, please make sure to update your budgets accordingly.

One final tip for all cloud service usage: remember to **immediately** delete *any* resources you do not wish to use to avoid being charged unnecessarily. 

Unfortunately, since your credit has expired, the only ways to reactivate your account would be to add a payment method or to wait a year for your student account to renew (assuming you are still a student) when you will get another allotment of free credit.
