### ISSUE TITLE
Issues Validating Single Tenant Bot

### ISSUE THREAD

**Issue by nickfrancis** [microsoft/BotFramework-Composer#9300]
Hi
Have built a bot in Framework Composer. It is provisioning successfully, but I've noticed that the web chat in composer isn't working & neither is testing the bot in Emulator.

I have followed troubleshooting steps [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0&tabs=csharp). I came across an error when validating the bot ID & password. When running the curl command I would get this error:

_"Application with identifier 'xxxxxxxxxxx' was not found in the directory 'Bot Framework'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant."_

I found this fix [here](https://stackoverflow.com/questions/71031057/microsoft-bot-framework-bot-missing-from-bot-framework-tenant-how-to-add) for resolving the curl command:

_"Just ran into the same issue. It looks like you have your bot registered into your tenant (and not the global bot framework). So you can get the access token by changing the URL to the following (replacing with your tenant id):

https://login.microsoftonline.com/YOUR-TENANT-ID/oauth2/v2.0/token
Just tested this and was able to get an access token."_

I have noticed in Bot Composer Web Chat I am getting the same error message. I've checked [Dev Bot Frameework](https://dev.botframework.com/) & that shows no bots listed either.

Any thoughts/ideas/input please?

**Comment by anishprasad01** [comment]
Hi @nickfrancis,

This is actually expected behavior. The emulator [does not support](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok?view=azure-bot-service-4.0) single tenant bots.

A regular multi-tenant bot works by creating the App Registration in the Bot Framework directory (the Azure resources remain in whatever tenant they are created in), thus allowing other applications from other tenants to find it. What's happening here is that a single tenant bot explicitly forbids this by registering the application inside the owner's tenant, rather than the Bot Framework directory. Thus, the error message `Application was not found in the directory 'Bot Framework'` is what we would expect from a single tenant bot.

However, if you use the "Test in Web Chat" blade under your Azure Bot resource, you should be able to talk to a published bot. If you wish to test the bot locally through Azure, the easiest way would be to create a second multi-tenant bot resource (no need for a duplicate App Service), and use something like ngrok or another tunneling tool to connect to a locally running bot.

Does that make sense?

**Comment by nickfrancis** [comment]
Hi @anishprasad01
That does make sense - thank you. I have tried testing in Web Chat and getting no response - just "There was an error sending this message to your bot: HTTP status code GatewayTimeout".

I thought that was linked to the single tenant bot registration but clearly not.

From what I can see all is set up correctly. I believe my messaging endpoint is correct. E.g. if my bot address is:

https://abcdefg.azurewebsites.net/

then my endpoint should be:

https://abcdefg.azurewebsites.net/api/messages

I need to have a look around the application insights & see what I can find.

**Comment by nickfrancis** [comment]
This can be closed.

Web chat not working was resolved by following post in this [thread](https://github.com/Microsoft/BotFramework-Emulator/issues/1068)
