### ISSUE TITLE
Not able to launch Bot Framework Composer from Power Virtual Agent 

### ISSUE THREAD

**Issue by VishalWankhede** [microsoft/BotFramework-Composer#9335]
**Issue :** Power Virtual Agent giving us one link to open Bot Framework Composer on machine. After pasting that link in Browser I am getting below error. Even the app is present in the System.

![image](https://user-images.githubusercontent.com/110682761/183107917-4c132ef4-f5d1-46a2-a06c-0a9f4d2f921b.png)

 
**Expected Behavior :** That link should directly launch Bot Framework Composer as it is available in system. 

**Note:**  To import Power Virtual Agent bot in BF Composer. Link is the only way to connect. 

But if my collogue  try to follow same steps on same server, he is able to launch Composer using that link.
So can someone help me to resolve this issue.

**Comment by munozemilio** [comment]
Hello @VishalWankhede... could you please provide the steps to get that link?
What I tried on my end is launching Composer from the Topics View
![Composer_from_PVA](https://user-images.githubusercontent.com/43281931/184020119-21be039a-8f4f-49c4-824e-ba77992e92cb.JPG)
In order to make it work I had to manually install composer.
The documentation can be found [here](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer).

**Comment by VishalWankhede** [comment]
Hello @munozemilio ... After clicking on "Open in Bot Framework Composer" you will get popup which contains "copy link" button. Please see the attachment for your reference.
![image](https://user-images.githubusercontent.com/110682761/184075129-07080e14-b7ac-45dc-a33d-548f83ae019b.png)

**Comment by johnataylor** [comment]
@VishalWankhede did you get this working? have you installed Bot Framework Composer as @munozemilio indicated?
