### ISSUE TITLE
In virtual assitent ,IBotFrameworkHttpAdapter.Adapter.Processasync menthod render the error :"Error invoking the skill id: error code 401."

### ISSUE THREAD

**Issue by Utkarsh-Patni-1** [microsoft/BotFramework-Composer#9378]
We are trying to create virtual assistant bot for Microsoft teams. When we are trying to send request to skill bot from root bot using SkillClient.PostActivityAsync method, while debugging request hits botcontroller of skill bot. But it returns 401 unauthorized error. How can we resolve this unauthorized error?
When we use root bot with the simple skill bot (not having any ClientApp), it is working. but when we use app having client app (for tabs and Messaging extensions built using react) and additional authorization required for it. at that time, it is throwing the above error.

Thanks!

**Comment by stevkan** [comment]
@Utkarsh-Patni-1, As the bot and skill work when left alone but fails when other code is added suggests that this is not a Composer issue. Nor is it specifically a bot issue. Because of this I will be closing this issue.

Clearly, though, some bit of code you have introduced is interfering with the bot's ability to run. As I see you have a matching [question](https://stackoverflow.com/questions/73688661) to this one on Stack Overflow, I will see if I am able to help you there.

----------

The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotFramework-SDK/) repo is the preferred platform for information on submitting **bug fixes** and **feature requests**.
