### ISSUE TITLE
How to connect Bot to the new QnA

### ISSUE THREAD

**Issue by adrwh** [microsoft/BotFramework-Composer#9427]
I created an empty nodejs bot using composer.  I started to add a qna, but it said don't do it, use the new language studio and create a question answer project over there instead.  So i did that.  Now how do i "connect" my knowledge base from Language Studio into my Bot?

I have tried the "import existing kb" but as i go through the wizard, i always end up at there are `No existing QnA Maker resources were found in this subscription. Select a different subscription, or click “Back” to create a new resource or generate a resource request to handoff to your Azure admin.` which in some ways is correct.  I cannot find the QnA resource anywhere in the Azure Portal, because its over in the Language Studio.

Where do i get these values from to try patch it together manually, seeing as it can't do it using the Composer features?

```
"qna": {
    "hostname": "",
    "knowledgebaseid": "",
    "qnaRegion": "",
    "endpointKey": {
      "message": "Waiting for QnA Maker"
    },
    "subscriptionKey": ""
  }
```

**Comment by anishprasad01** [comment]
Hi @adrwh,

Since QnA maker is being deprecated, the ability to create new QnA resources in Azure has been turned off. This means that new Composer bots will be unable to deploy QnA maker resources.

There is work in progress regarding the path forward for Composer and the new language resources, but for now, they are not natively supported, and there is no easy way to "patch it together", so to speak.

You could look into creating a custom action or middleware as a stopgap solution. See [this post](https://github.com/microsoft/BotFramework-Composer/issues/9400) for more information about future plans for Composer and Cognitive Services for Language.

**Comment by fausttiger** [comment]
ADRWH

You can do an HTTP post to send questions to your Custom Question Answering language resource...    but you have to process the return package in code, including any followthru-prompts.

![image](https://user-images.githubusercontent.com/905135/205926389-9b0e8291-2a54-4021-974e-e6bcd0d6ecf6.png)

> I created an empty nodejs bot using composer. I started to add a qna, but it said don't do it, use the new language studio and create a question answer project over there instead. So i did that. Now how do i "connect" my knowledge base from Language Studio into my Bot?
> 
> I have tried the "import existing kb" but as i go through the wizard, i always end up at there are `No existing QnA Maker resources were found in this subscription. Select a different subscription, or click “Back” to create a new resource or generate a resource request to handoff to your Azure admin.` which in some ways is correct. I cannot find the QnA resource anywhere in the Azure Portal, because its over in the Language Studio.
> 
> Where do i get these values from to try patch it together manually, seeing as it can't do it using the Composer features?
> 
> ```
> "qna": {
>     "hostname": "",
>     "knowledgebaseid": "",
>     "qnaRegion": "",
>     "endpointKey": {
>       "message": "Waiting for QnA Maker"
>     },
>     "subscriptionKey": ""
>   }
> ```

**Comment by fausttiger** [comment]
@adrwh

From Custom Question Answering project,  you can   CREATE BOT (after you do your first Deploy) which wizard will help generate resources in Azure.

The knowledgbase will be active in Azure,  you can use WebChat in Azure to test.

However... the issue is publishing your   Composer Bot code to that Azure Bot... as it still looks for LUIS.  Still attempting to resolve.

when I set   QNA : {}   in  appsettings.json it didn't look for QnA resources.



> ADRWH
> 
> You can do an HTTP post to send questions to your Custom Question Answering language resource... but you have to process the return package in code, including any followthru-prompts.
> 
> ![image](https://user-images.githubusercontent.com/905135/205926389-9b0e8291-2a54-4021-974e-e6bcd0d6ecf6.png)
> 
> > I created an empty nodejs bot using composer. I started to add a qna, but it said don't do it, use the new language studio and create a question answer project over there instead. So i did that. Now how do i "connect" my knowledge base from Language Studio into my Bot?
> > I have tried the "import existing kb" but as i go through the wizard, i always end up at there are `No existing QnA Maker resources were found in this subscription. Select a different subscription, or click “Back” to create a new resource or generate a resource request to handoff to your Azure admin.` which in some ways is correct. I cannot find the QnA resource anywhere in the Azure Portal, because its over in the Language Studio.
> > Where do i get these values from to try patch it together manually, seeing as it can't do it using the Composer features?
> > ```
> > "qna": {
> >     "hostname": "",
> >     "knowledgebaseid": "",
> >     "qnaRegion": "",
> >     "endpointKey": {
> >       "message": "Waiting for QnA Maker"
> >     },
> >     "subscriptionKey": ""
> >   }
> > ```
