### ISSUE TITLE
Package Manager remains disabled for a PVA integrated Bot

### ISSUE THREAD

**Issue by abhishekkumar717** [microsoft/BotFramework-Composer#9461]
Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

I want to utilize the pre- built packages for my PVA integrated bot, but the package manager remains disabled. It is to be noted that package manager is enabled for a bot created on Bot Framework Composer, but it remains disabled for a PVA integrated bot. Could you pls help me in this regard.
![PVA_Integrated](https://user-images.githubusercontent.com/120561285/210379948-ed4e2179-641b-4972-ae5e-c1c9b87fe90e.JPG)
![BFC_Bot](https://user-images.githubusercontent.com/120561285/210380116-f2ab32e6-bd6a-4d8e-bacf-9dc6675b7dd7.JPG)

**Comment by ramfattah** [comment]
Thanks @abhishekkumar717, we are investigating.

**Comment by ramfattah** [comment]
Thanks @abhishekkumar717,

It appears I'm able to repro.
If I opened the PVA bot with Composer 2.1.2, the package manager is also disabled from my end.

<img src="https://user-images.githubusercontent.com/38049078/211358906-abb56744-a46b-4731-b26b-bcdf080a916e.png" width="500"/>

I'm not sure if this is by design or a bug, I will discuss with the engineering team and report back.
Thanks.

**Comment by tracyboehrer** [comment]
This is by design.  A Composer bot in the context of PVA cannot execute code in a package.  If this is required, a Composer bot using the stand-alone version should be used to create a Skill, which is called by PVA.
