### ISSUE TITLE
Handle events in Skills in Bot Composer

### ISSUE THREAD

**Issue by Akhila9** [microsoft/BotFramework-Composer#9466]
Hi Team, I was able to make a successful connection to a skill bot from a root bot.

The initial connection was made through an event only. Let say after that the control  is in skill bot now, now if any messages are passed they are handled correctly(skill bot) but if any external event is being triggered, it goes to the root bot rather than the skill bot.

Is it the expected behavior? Any thoughts on this ?

**Comment by dmvtech** [comment]
Hi @Akhila9 

Can you expand what you mean by _**external**_ event? What is an example event that you are dealing with?

With normal messages/text; once the conversation is handed over to the skill, it continues there until there is an interruption (if configured) or the skill completes. I'm not quite sure on the events if should work the same or as you are experiencing (what is exactly the expected behavior).  I'm investigating and will update when I have more findings.

**Comment by Akhila9** [comment]
External event is just the normal event activity we deal with in the framework. I mentioned it as external as it comes from a different software. { type =event, name= exampleeventname, value={…}}.

One more observation which we found can help you in your further investigation is that if there is no Event received activity trigger configured in the root bot, the control goes to the event received activity in the skill. So what I assume is the priority is given to the root bot in this scenario. 

Please look into this and let us know the expected behavior as well as good approach to proceed.

**Comment by dmvtech** [comment]
> External event is just the normal event activity we deal with in the framework. I mentioned it as external as it comes from a different software. { type =event, name= exampleeventname, value={…}}.

Understood. I assumed that but I wanted to confirm.


> if there is no Event received activity trigger configured in the root bot, the control goes to the event received activity in the skill. So what I assume is the priority is given to the root bot in this scenario.

So, to clarify; you have an event received activity in the root/consumer bot as well? What is that being used for? Is the root bot a skill as well (for other root/consumer bots)?

**Comment by Akhila9** [comment]
Yes, we have event received activity in both the bots. Ours is a voice bot and so some events like DTMF, nouserinput will be triggered which should be available in both root and skill bot. Root bot is not acting as a skill for other bots.

**Comment by dmvtech** [comment]
Hi @Akhila9 Sorry for the delay. I still have a bit more to check out. Hope to have some findings for you shortly.

**Comment by dmvtech** [comment]
hi @Akhila9 

Sorry for the delay. I can confirm this is expected behavior. When the bot hands off to the skill, everything is still going through the root bot (although interruptions, automatic ending of dialogs, etc. can make this appear differently). So, if both the root and skill bot handle events of the same name, then events received to the root bot will always be handled even though the 'control' is at the skill. If you have other properties of the event that can be checked/evaluated on, then you can customize the `Condition` field of the Event Received activity.

**Comment by Akhila9** [comment]
Thank you @dmvtech for the understanding.

**Comment by Akhila9** [comment]
@dmvtech Can you please let me know the behaviour for EndOfConversation activity?

Let say if EoC Activity hits the root bot, we close the connection in the root bot, but the skill instances will be running  right? Wont that cause a problem?
