### ISSUE TITLE
Error 401 accessing a remote skill

### ISSUE THREAD

**Issue by lsacera** [microsoft/BotFramework-Composer#9512]
Hello,
I am trying to connect a bot from Bot Framework composer to a bot I have developed in a totally different technology (teneo.ai, a java application).
To add the skill to my bot in composer, I select the option "Add-->Connect to a skill". 
Then I put my manifest.json file and the bot registers the new skill.

Then, to test the skill I have created a trigger (unknown intent) to use the action "Connect to a skill".

The problem is when I try to access the skill I get a 401 error from the bot.

I guess the problem could be the "allowed callers" property in my skill. However, as I have created the connection to the skill using the manifest in a zip file, I do not have access to that configuration page as my skill does not "exists" in bot framework composer.

However, I have my skill deployed in Azure so I have access to azure resources. To have my skill working I had to create:
- App Registration
- Azure bot (this has the webchat and directline channel enabled)
- Azure App Service (this is the actual web application serving the endpoint

I am totally stuck with this as I do not know what to change, any help will be more than welcome.

**Comment by anishprasad01** [comment]
Hi @lsacera,

I believe there's some confusion here about how skills work. When a Bot Framework caller invokes a skill, it sends a specially formatted activity to the skill which passes the conversation context, allowing the skill to continue the interaction with the user. To service this request, the skill bot must define a Bot Framework skill handler. Thus, for this to work, both the calling bot *and* the skill bot must be Bot Framework bots. If either bot is built with a different framework (such as teneo.ai), the skill bot system will not work.

In order to connect the two bots together, you will need to use some other communication mechanism, such as REST calls or some form of middleware or adapter.
