### ISSUE TITLE
After uploads image in composer its throwing 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by BhogiSupriya** [microsoft/BotFramework-Composer#9563]
I am trying to use the prompt for a file/attachment to upload an image but after uploading an image it's throwing the exception 'Object reference not set to an instance of an object.' 
please refer below images

<img width="956" alt="Screenshot 2023-04-22 230728" src="https://user-images.githubusercontent.com/131548272/233798810-72844722-fec0-4fda-870c-5272c3e4bf06.png">

<img width="729" alt="image" src="https://user-images.githubusercontent.com/131548272/233798859-68703935-7e6a-45fc-8616-9110af1a474d.png">

**Comment by anishprasad01** [comment]
@BhogiSupriya,

When the output format is set to `all`, `dialog.attachments` is an *array*, not a single object. The array does not have a `contentUrl` value, which is why you're getting a null exception. Use `dialog.attachments[0]` to access the first element instead. This is also shown in the [docs page](https://learn.microsoft.com/en-us/composer/how-to-ask-for-user-input?tabs=v2x#file-or-attachment-input) on file input.
