### ISSUE TITLE
bool('false') converts to true

### ISSUE THREAD

**Issue by dawwa** [microsoft/BotFramework-Composer#9584]
bool expression does not work properly

This is what I have in the expression
<img width="281" alt="image" src="https://github.com/microsoft/BotFramework-Composer/assets/44714043/11589ce6-7b17-45c2-8832-3cb9d07ce97c">

This is what it resolves, basically bool('false') converts to true
<img width="240" alt="image" src="https://github.com/microsoft/BotFramework-Composer/assets/44714043/040e19cd-2f57-4dee-a8e2-e123de2ec369">

**Comment by dmvtech** [comment]
Hi @dawwa 

Are you using .NET/C# runtime or NodeJS?

**Comment by dmvtech** [comment]
Also; what version of Adaptive Expressions are you running?

I ran some quick tests and confirmed that Node will turn any text into boolean `true`.

Using LG/Expression:
```
False false: ${bool(false)}
False text: ${bool('false')}
False zero: ${bool(0)}
True true: ${bool(true)}
True text: ${bool('true')}
True one: ${bool(1)}
```

Results:


## Node
"version": "4.14.1"

False false: false
False text: true
False zero: false
True true: true
True text: true
True one: true

"version": "4.19.3"

False false: false
False text: true
False zero: false
True true: true
True text: true
True one: true

## .NET
Version="4.17.2" 

False false: False
False text: False
False zero: False
True true: True
True text: True
True one: True

**Comment by JhontSouth** [comment]
Hi @dawwa , @dmvtech,
After some tests, we noticed that this issue is reproducible only when enclosing the string value in single quotes.
As the variable is already of type string, these extra quotes are included in the parsing, causing the error.
If we set the string without the quotes, the result is False.

The following images show the results that we obtained using the simple quotes and removing it.
![image](https://github.com/microsoft/BotFramework-Composer/assets/122501764/6b785c49-6d49-4bd7-94fc-fea232752784)
![image](https://github.com/microsoft/BotFramework-Composer/assets/122501764/e34a3f34-a89d-4579-8336-f79045cc52b4)

**Comment by dmvtech** [comment]
Thanks @JhontSouth 

So, anything put inside the parenthesis of `bool()` is essentially going to be a string already (whether it's 1, or `true` or even `'true'`. The latter will just not be able to successfully converted to a Boolean due to the quotes, correct?  And if it's not a string (converted from an object set as value type of `int` or `bool`), then it will convert correctly.

**Comment by JhontSouth** [comment]
Hi @dmvtech,
The bool function will take the type of the variable you set. In this case, the property was of type string and adding the extra quotes was causing the conversion error. You could pass an integer or a bool to the function and it will work.

![image](https://github.com/microsoft/BotFramework-Composer/assets/122501764/a5957a02-92bd-40be-8ef3-fba512e19d03)
