### ISSUE TITLE
Publish failing as we cannot create LUIS resource anymore

### ISSUE THREAD

**Issue by pramilgawande** [microsoft/BotFramework-Composer#9629]
As LUIS is retiring we cannot create LUIS resource anymore and hence cannot publish the bot to Azure.

## Version

Release: 2.1.2

## Browser

- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Go and create a new publish profile with new resources to deploy

## Expected behavior

The provisioning of LUIS will fail.

## Screenshots

![image](https://github.com/microsoft/BotFramework-Composer/assets/11131241/4bb3c627-c437-4313-8382-c7fbc8d2e5bd)

![image](https://github.com/microsoft/BotFramework-Composer/assets/11131241/166a1d33-ea63-47eb-b68f-b4f834fe01d9)

**Comment by ramfattah** [comment]
Thanks @pramilgawande, I'm investigating this issue.

**Comment by ramfattah** [comment]
Hi @anug777,

Please use [ConversationLanguageUnderstanding](https://github.com/microsoft/botframework-components/tree/main/packages/Recognizers/ConversationLanguageUnderstanding) recognizer package that helps you add CLU recognizer to an empty bot built with Bot Framework Composer in order to use Azure [Conversational Language Understanding](https://learn.microsoft.com/en-us/azure/ai-services/language-service/conversational-language-understanding/overview) in place of the now deprecated Luis.
