### ISSUE TITLE
Cannot open bot created with Language Studio

### ISSUE THREAD

**Issue by Lory1990** [microsoft/BotFramework-Composer#9646]
## Describe the bug
I created a Langiage model using AzureAI language service, created a bot and cannot open and edit it
## Version
Latest - 2.
## OS
- [X ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

* I created a Custom Question Answering Project with Azure AI Language Studio
* Configured all the stuff
* Deployed
* Clicked on "Create a Bot"
![image](https://github.com/microsoft/BotFramework-Composer/assets/7715601/c451aa12-10dc-46cd-a981-c6e0fc1103f3)
* Bot has been created 
* Clicked on download SRC
* ![image](https://github.com/microsoft/BotFramework-Composer/assets/7715601/aca069fa-6e0a-4196-bf45-4df6e4ede78f)
* Cannot open with Azure Bot Framework composer

## Expected behavior

Can open the project and add actions / triggers /...

**Comment by stevkan** [comment]
@Lory1990 - Bots created via the Language Studio are code-first (aka SDK) bots and are not readable by the BotFramework Composer application. Composer creates and runs bots that utilize an adaptive dialog runtime that, while dependent on the BotFramework SDK, it does not openly reference it.

If you want to create a CQA bot using Composer then you will need to, first, create a Composer bot. Once done, click on the Package Manager option on the left sidebar, search for 'Microsoft.Bot.Components.Recognizers.CustomQuestionAnsweringRecognizer' and install it. Then open the 'View documentation' [link](https://github.com/microsoft/botframework-components/tree/main/packages/Recognizers/CustomQuestionAnswering/dotnet) in the package description and follow the instructions for implementing.

As you have already created a Language Studio resource, you can reference the resource rather than create a new one when provisioning. Additionally, you can reference the Composer [docs](https://learn.microsoft.com/en-us/composer/introduction?tabs=v2x) for more insight into creating bots using Composer.

As this should resolve your issue, I am closing this. If you continue to receive error messages, please feel free to reopen this issue. However, 'how-to' type questions should be posted to the Stack Overflow [community](https://stackoverflow.com/questions/ask).
