### ISSUE TITLE
ConversationLanguageUnderstandingRecognizer not shown

### ISSUE THREAD

**Issue by TWDevLead** [microsoft/BotFramework-Composer#9683]
## Describe the bug

I am following the installation guide to add CLU Support to the composer:
https://github.com/Microsoft/botframework-components/tree/main/packages/Recognizers/ConversationLanguageUnderstanding/dotnet

I did install the CLU Recoginzer package
![image](https://github.com/microsoft/BotFramework-Composer/assets/143957890/c8f69746-db83-474e-a1fa-4ca9abfd4302)

However, the search for ConversationLanguageUnderstandingRecognizer is not successfull. 
![image](https://github.com/microsoft/BotFramework-Composer/assets/143957890/8e382aaf-ef75-47a8-a8a6-63a7c75b090d)

## Version

Release: 2.1.3-nightly.364675.1a93f21
as
Release 2.1.2 has the certificate error

## To Reproduce
See above,
install the CLU Recoginzer package, start with the emty bot template and try to find the package to install. 

Thank you

**Comment by rampaged** [comment]
Hi @TWDevLead, 

I'm able to reproduce. Thanks for reporting this issue.

The [ConversationLanguageUnderstanding](https://github.com/microsoft/botframework-components/tree/main/packages/Recognizers/ConversationLanguageUnderstanding) readme mentions:

> 3. Search for `ConversationLanguageUnderstandingRecognizer` and install the package.


In Composer's package manager, searching for `ConversationLanguageUnderstandingRecognizer` indeed does not show any packages:

![Screenshot from 2024-01-17 14-43-02](https://github.com/microsoft/BotFramework-Composer/assets/38049078/cb5087b4-2938-4693-8187-ffdc4d060770)

#

I think this is a documentation issue in [ConversationLanguageUnderstanding](https://github.com/microsoft/botframework-components/tree/main/packages/Recognizers/ConversationLanguageUnderstanding) readme. 

To install the [CLU recognizer package](https://www.nuget.org/packages/Microsoft.Bot.Components.Recognizers.CLURecognizer) in Composer, the [ConversationLanguageUnderstanding](https://github.com/microsoft/botframework-components/tree/main/packages/Recognizers/ConversationLanguageUnderstanding) readme documentation should mention the actual CLU package name `Microsoft.Bot.Components.Recognizers.CLURecognizer` instead of `ConversationLanguageUnderstandingRecognizer`
