### ISSUE TITLE
Composer Package Manager Error HelpAndCancel

### ISSUE THREAD

**Issue by jgblouin** [microsoft/BotFramework-Composer#9690]
## Describe the bug

Can not install Microsoft.Bot.Components.HelpAndCancel. I receive an Install Error message. Tried installing version 1.4.0 and then tried previous versions with the same result. See attached screenshot.
![Screenshot 2024-01-18 112029](https://github.com/microsoft/BotFramework-Composer/assets/7523840/0d71b07d-1ea3-45da-815b-7f3e81216135)

## Version

Bot Framework SDK 4.12.0
## Browser

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Package manager'
2. Click on 'Microsoft.Bot.Components.HelpAndCancel'
3. Click on 'Install 1.4.0'

## Expected behavior

No idea, never got there. :(

## Screenshots

See above.

**Comment by OEvgeny** [comment]
First of all, please ensure, you're using the latest niglty release of the Composer app.

This may happen because of NPM giving notice about a new version available and Composer Package manager treats this as an error. As a workaround try updating NPM to the latest version. Run the command in the WIndows Terminal app:

```bash
npm i -G npm@latest
```

After this is done, I was able to install the package:

![image](https://github.com/microsoft/BotFramework-Composer/assets/2841858/d6dc6671-39f9-4128-a537-10486f828d3f)
![image](https://github.com/microsoft/BotFramework-Composer/assets/2841858/a0826328-18a0-4816-89a3-e363bc79f0bf)

**Comment by dmvtech** [comment]
Closing as likely resolved. If you are still having issues, please comment and we can reopen and continue.
